// packages/react/src/components/command/Command.tsx
'use client';

import React, {
	createContext,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useReducer,
	useRef,
} from 'react';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useHotkeys } from '@/hooks/use-hotkeys';
import { useId } from '@/hooks/use-id';
import type {
	CommandContextValue,
	CommandEmptyProps,
	CommandFilter,
	CommandGroupContextValue,
	CommandGroupProps,
	CommandInputProps,
	CommandItemProps,
	CommandListProps,
	CommandRootProps,
	CommandSeparatorProps,
} from './Command.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CommandContext = createContext<CommandContextValue | null>(null);
const CommandGroupContext = createContext<CommandGroupContextValue | null>(null);

function useCommandContext() {
	const ctx = useContext(CommandContext);
	if (!ctx) throw new globalThis.Error('Command sub-components must be used within Command.Root');
	return ctx;
}

const defaultFilter: CommandFilter = (value, search, keywords) => {
	if (!search) return true;
	const haystack = `${value} ${keywords.join(' ')}`.toLowerCase();
	return haystack.includes(search.trim().toLowerCase());
};

interface RegistryEntry {
	keywords: string[];
	disabled: boolean;
	groupId?: string;
	onSelectRef: React.MutableRefObject<((value: string) => void) | undefined>;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, CommandRootProps>(
	(
		{
			searchValue,
			defaultSearchValue = '',
			onSearchChange,
			filter = defaultFilter,
			onSelect,
			loop = true,
			open,
			defaultOpen,
			onOpenChange,
			shortcut,
			className,
			children,
			...rest
		},
		ref,
	) => {
		const [query, setQueryState] = useControllableState<string>({
			value: searchValue,
			defaultValue: defaultSearchValue,
			onChange: onSearchChange,
		});

		const managed = open !== undefined || defaultOpen !== undefined || !!shortcut;
		const [isOpen, setOpen] = useControllableState<boolean>({
			value: open,
			defaultValue: defaultOpen ?? !shortcut,
			onChange: onOpenChange,
		});

		useHotkeys(shortcut ? { [shortcut]: () => setOpen(!isOpen) } : {}, {
			enabled: !!shortcut,
			enableInInputs: true,
		});

		const registryRef = useRef<Map<string, RegistryEntry>>(new Map());
		const [version, bump] = useReducer((x: number) => x + 1, 0);
		const [activeRaw, setActiveRaw] = React.useState<string | null>(null);

		const registerItem = useCallback((value: string, item: RegistryEntry) => {
			registryRef.current.set(value, item);
			bump();
			return () => {
				registryRef.current.delete(value);
				bump();
			};
		}, []);

		const visible = useMemo(() => {
			const result: string[] = [];
			// Reading the item registry during render is intentional: `version` bumps on
			// every register/unregister, forcing this memo to recompute.
			// eslint-disable-next-line react-hooks/refs
			const registry = registryRef.current;
			for (const [value, entry] of registry) {
				if (filter(value, query, entry.keywords)) result.push(value);
			}
			return result;
			// eslint-disable-next-line react-hooks/exhaustive-deps
		}, [query, filter, version]);

		// Derive the effective active item so a filtered-out item never stays active.
		const activeValue = activeRaw && visible.includes(activeRaw) ? activeRaw : visible[0] ?? null;

		const setActiveValue = useCallback((value: string) => setActiveRaw(value), []);

		const moveActive = useCallback(
			(delta: number) => {
				const len = visible.length;
				if (len === 0) return;
				const startIndex = activeValue ? visible.indexOf(activeValue) : -1;
				let i = startIndex;
				// Step in `delta` direction, skipping disabled options, until an enabled
				// one is found or we run out of candidates.
				for (let step = 0; step < len; step++) {
					let nextIndex = i + delta;
					if (nextIndex < 0) nextIndex = loop ? len - 1 : 0;
					else if (nextIndex >= len) nextIndex = loop ? 0 : len - 1;
					if (nextIndex === i) break; // hit a non-looping boundary
					i = nextIndex;
					if (!registryRef.current.get(visible[i])?.disabled) {
						setActiveRaw(visible[i]);
						return;
					}
				}
			},
			[visible, activeValue, loop],
		);

		const setActiveEdge = useCallback(
			(edge: 'first' | 'last') => {
				const ordered = edge === 'first' ? visible : [...visible].reverse();
				const found = ordered.find((value) => !registryRef.current.get(value)?.disabled);
				if (found) setActiveRaw(found);
			},
			[visible],
		);

		const close = useCallback(() => {
			if (managed) setOpen(false);
		}, [managed, setOpen]);

		const onSelectRef = useRef(onSelect);
		useEffect(() => {
			onSelectRef.current = onSelect;
		});

		const selectItem = useCallback(
			(value: string) => {
				const entry = registryRef.current.get(value);
				if (!entry || entry.disabled) return;
				entry.onSelectRef.current?.(value);
				onSelectRef.current?.(value);
				if (managed) setOpen(false);
			},
			[managed, setOpen],
		);

		const baseId = useId('command');
		const listboxId = `${baseId}-list`;
		const getItemId = useCallback((value: string) => `${baseId}-item-${encodeURIComponent(value)}`, [baseId]);

		const groupHasVisible = useCallback(
			(groupId: string) => visible.some((v) => registryRef.current.get(v)?.groupId === groupId),
			[visible],
		);

		const ctx = useMemo<CommandContextValue>(
			() => ({
				query,
				setQuery: setQueryState,
				searching: query.trim().length > 0,
				visible,
				activeValue,
				setActiveValue,
				moveActive,
				setActiveEdge,
				registerItem,
				selectItem,
				isVisible: (value) => visible.includes(value),
				isActive: (value) => value === activeValue,
				groupHasVisible,
				listboxId,
				getItemId,
				close,
			}),
			[
				query,
				setQueryState,
				visible,
				activeValue,
				setActiveValue,
				moveActive,
				setActiveEdge,
				registerItem,
				selectItem,
				groupHasVisible,
				listboxId,
				getItemId,
				close,
			],
		);

		if (managed && !isOpen) return null;

		return (
			<CommandContext.Provider value={ctx}>
				<div
					ref={ref}
					className={className}
					data-command-root=''
					{...rest}>
					{children}
				</div>
			</CommandContext.Provider>
		);
	},
);

Root.displayName = 'Command.Root';

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

const Input = React.forwardRef<HTMLInputElement, CommandInputProps>(({ className, onKeyDown, ...rest }, ref) => {
	const ctx = useCommandContext();
	const activeId = ctx.activeValue ? ctx.getItemId(ctx.activeValue) : undefined;

	return (
		<input
			ref={ref}
			type='text'
			role='combobox'
			autoComplete='off'
			autoCorrect='off'
			spellCheck={false}
			aria-expanded
			aria-controls={ctx.listboxId}
			aria-activedescendant={activeId}
			value={ctx.query}
			className={className}
			{...rest}
			onChange={(e) => ctx.setQuery(e.target.value)}
			onKeyDown={(e) => {
				onKeyDown?.(e);
				if (e.defaultPrevented) return;
				if (e.key === 'ArrowDown') {
					e.preventDefault();
					ctx.moveActive(1);
				} else if (e.key === 'ArrowUp') {
					e.preventDefault();
					ctx.moveActive(-1);
				} else if (e.key === 'Home') {
					e.preventDefault();
					ctx.setActiveEdge('first');
				} else if (e.key === 'End') {
					e.preventDefault();
					ctx.setActiveEdge('last');
				} else if (e.key === 'Enter' && ctx.activeValue) {
					e.preventDefault();
					ctx.selectItem(ctx.activeValue);
				} else if (e.key === 'Escape') {
					e.preventDefault();
					ctx.close();
				}
			}}
		/>
	);
});

Input.displayName = 'Command.Input';

// ---------------------------------------------------------------------------
// List
// ---------------------------------------------------------------------------

const List = React.forwardRef<HTMLDivElement, CommandListProps>(({ className, children, ...rest }, ref) => {
	const ctx = useCommandContext();
	return (
		<div
			ref={ref}
			role='listbox'
			id={ctx.listboxId}
			className={className}
			{...rest}>
			{children}
		</div>
	);
});

List.displayName = 'Command.List';

// ---------------------------------------------------------------------------
// Group
// ---------------------------------------------------------------------------

const Group = React.forwardRef<HTMLDivElement, CommandGroupProps>(
	({ heading, className, children, ...rest }, ref) => {
		const ctx = useCommandContext();
		const groupId = useId('command-group');
		const hasVisible = ctx.groupHasVisible(groupId);
		const headingId = `${groupId}-heading`;

		return (
			<CommandGroupContext.Provider value={{ groupId }}>
				<div
					ref={ref}
					role='group'
					aria-labelledby={heading ? headingId : undefined}
					hidden={!hasVisible ? true : undefined}
					className={className}
					{...rest}>
					{heading != null && (
						<div
							id={headingId}
							data-command-group-heading=''
							aria-hidden='true'>
							{heading}
						</div>
					)}
					{children}
				</div>
			</CommandGroupContext.Provider>
		);
	},
);

Group.displayName = 'Command.Group';

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

const Item = React.forwardRef<HTMLDivElement, CommandItemProps>(
	({ value, keywords, disabled = false, onSelect, className, children, onClick, onPointerMove, ...rest }, ref) => {
		const ctx = useCommandContext();
		const group = useContext(CommandGroupContext);
		const onSelectRef = useRef(onSelect);
		useEffect(() => {
			onSelectRef.current = onSelect;
		});

		const keywordsKey = (keywords ?? []).join('');
		const { registerItem } = ctx;
		const groupId = group?.groupId;
		useEffect(() => {
			return registerItem(value, { keywords: keywords ?? [], disabled, groupId, onSelectRef });
			// keywordsKey captures the array contents; onSelectRef is stable.
			// eslint-disable-next-line react-hooks/exhaustive-deps
		}, [registerItem, value, keywordsKey, disabled, groupId]);

		if (!ctx.isVisible(value)) return null;
		const active = ctx.isActive(value);

		return (
			<div
				ref={ref}
				role='option'
				id={ctx.getItemId(value)}
				aria-selected={active}
				aria-disabled={disabled || undefined}
				data-active={active ? '' : undefined}
				data-disabled={disabled ? '' : undefined}
				className={className}
				{...rest}
				onPointerMove={(e) => {
					if (!disabled) ctx.setActiveValue(value);
					onPointerMove?.(e);
				}}
				onClick={(e) => {
					if (!disabled) ctx.selectItem(value);
					onClick?.(e);
				}}>
				{children}
			</div>
		);
	},
);

Item.displayName = 'Command.Item';

// ---------------------------------------------------------------------------
// Separator
// ---------------------------------------------------------------------------

const Separator = React.forwardRef<HTMLDivElement, CommandSeparatorProps>(({ className, ...rest }, ref) => {
	const ctx = useCommandContext();
	// Separators are noise while filtering.
	if (ctx.searching) return null;
	// `role="separator"` is not an allowed child of `role="listbox"` (per the ARIA
	// listbox spec, which permits only `option` and `group`). The divider is purely
	// a visual cue between groups, so it is presentational and carries no semantics.
	return (
		<div
			ref={ref}
			role='none'
			className={className}
			{...rest}
		/>
	);
});

Separator.displayName = 'Command.Separator';

// ---------------------------------------------------------------------------
// Empty
// ---------------------------------------------------------------------------

const Empty = React.forwardRef<HTMLDivElement, CommandEmptyProps>(({ className, children, ...rest }, ref) => {
	const ctx = useCommandContext();
	if (ctx.visible.length > 0) return null;
	return (
		<div
			ref={ref}
			role='presentation'
			className={className}
			{...rest}>
			{children}
		</div>
	);
});

Empty.displayName = 'Command.Empty';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Command = {
	Root,
	Input,
	List,
	Group,
	Item,
	Separator,
	Empty,
};

// Named exports expose the sub-components to Storybook's react-docgen (public API stays `Command.*`).
export { Root, Input, List, Group, Item, Separator, Empty };

// packages/solid/src/components/command/Command.tsx
'use client';

import {
	createContext,
	createMemo,
	createSignal,
	onCleanup,
	Show,
	splitProps,
	useContext,
	type JSX,
} from 'solid-js';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createHotkeys } from '@/primitives/create-hotkeys';
import { createId } from '@/primitives/create-id';
import type {
	CommandContextValue,
	CommandEmptyProps,
	CommandFilter,
	CommandGroupContextValue,
	CommandGroupProps,
	CommandInputProps,
	CommandItemProps,
	CommandListProps,
	CommandRootProps,
	CommandSeparatorProps,
} from './Command.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CommandContext = createContext<CommandContextValue | null>(null);
const CommandGroupContext = createContext<CommandGroupContextValue | null>(null);

function useCommandContext() {
	const ctx = useContext(CommandContext);
	if (!ctx) throw new Error('Command sub-components must be used within Command.Root');
	return ctx;
}

const defaultFilter: CommandFilter = (value, search, keywords) => {
	if (!search) return true;
	const haystack = `${value} ${keywords.join(' ')}`.toLowerCase();
	return haystack.includes(search.trim().toLowerCase());
};

interface RegistryEntry {
	keywords: string[];
	disabled: boolean;
	groupId?: string;
	getOnSelect: () => ((value: string) => void) | undefined;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: CommandRootProps) {
	const [local, rest] = splitProps(props, [
		'searchValue',
		'defaultSearchValue',
		'onSearchChange',
		'filter',
		'onSelect',
		'loop',
		'open',
		'defaultOpen',
		'onOpenChange',
		'shortcut',
		'class',
		'children',
	]);

	const filter = () => local.filter ?? defaultFilter;
	const loop = () => local.loop ?? true;

	const [query, setQueryState] = createControllableState<string>({
		get value() {
			return local.searchValue;
		},
		defaultValue: local.defaultSearchValue ?? '',
		get onChange() {
			return local.onSearchChange;
		},
	});

	const managed = () => local.open !== undefined || local.defaultOpen !== undefined || !!local.shortcut;

	const [isOpen, setOpen] = createControllableState<boolean>({
		get value() {
			return local.open;
		},
		// `defaultValue` is an initial value only — read once at setup, intentionally.
		// eslint-disable-next-line solid/reactivity
		defaultValue: local.defaultOpen ?? !local.shortcut,
		get onChange() {
			return local.onOpenChange;
		},
	});

	// `shortcut` is treated as static config; the map is built once at setup.
	// eslint-disable-next-line solid/reactivity
	const hotkeyMap = local.shortcut ? { [local.shortcut]: () => setOpen(!isOpen()) } : {};
	createHotkeys(hotkeyMap, {
		get enabled() {
			return !!local.shortcut;
		},
		enableInInputs: true,
	});

	// A reactive registry: a signal holding the Map, bumped on every mutation so
	// derived computations (visible list, group visibility) re-run.
	const registry = new Map<string, RegistryEntry>();
	const [version, setVersion] = createSignal(0);
	const bump = () => setVersion((x) => x + 1);

	const [activeRaw, setActiveRaw] = createSignal<string | null>(null);

	const registerItem = (value: string, item: RegistryEntry) => {
		registry.set(value, item);
		bump();
		return () => {
			registry.delete(value);
			bump();
		};
	};

	const visible = createMemo<string[]>(() => {
		version(); // track registry mutations
		const search = query() ?? '';
		const match = filter();
		const result: string[] = [];
		for (const [value, entry] of registry) {
			if (match(value, search, entry.keywords)) result.push(value);
		}
		return result;
	});

	// Derive the effective active item so a filtered-out item never stays active.
	const activeValue = createMemo<string | null>(() => {
		const raw = activeRaw();
		const list = visible();
		return raw && list.includes(raw) ? raw : list[0] ?? null;
	});

	const setActiveValue = (value: string) => setActiveRaw(value);

	const moveActive = (delta: number) => {
		const list = visible();
		const len = list.length;
		if (len === 0) return;
		const active = activeValue();
		let i = active ? list.indexOf(active) : -1;
		// Step in `delta` direction, skipping disabled options, until an enabled
		// one is found or we run out of candidates.
		for (let step = 0; step < len; step++) {
			let nextIndex = i + delta;
			if (nextIndex < 0) nextIndex = loop() ? len - 1 : 0;
			else if (nextIndex >= len) nextIndex = loop() ? 0 : len - 1;
			if (nextIndex === i) break; // hit a non-looping boundary
			i = nextIndex;
			if (!registry.get(list[i])?.disabled) {
				setActiveRaw(list[i]);
				return;
			}
		}
	};

	const setActiveEdge = (edge: 'first' | 'last') => {
		const list = visible();
		const ordered = edge === 'first' ? list : [...list].reverse();
		const found = ordered.find((value) => !registry.get(value)?.disabled);
		if (found) setActiveRaw(found);
	};

	const close = () => {
		if (managed()) setOpen(false);
	};

	const selectItem = (value: string) => {
		const entry = registry.get(value);
		if (!entry || entry.disabled) return;
		entry.getOnSelect()?.(value);
		local.onSelect?.(value);
		if (managed()) setOpen(false);
	};

	const baseId = createId('command');
	const listboxId = `${baseId}-list`;
	const getItemId = (value: string) => `${baseId}-item-${encodeURIComponent(value)}`;

	const groupHasVisible = (groupId: string) =>
		visible().some((v) => registry.get(v)?.groupId === groupId);

	const ctx: CommandContextValue = {
		get query() {
			return query() ?? '';
		},
		setQuery: setQueryState,
		get searching() {
			return (query() ?? '').trim().length > 0;
		},
		get visible() {
			return visible();
		},
		get activeValue() {
			return activeValue();
		},
		setActiveValue,
		moveActive,
		setActiveEdge,
		registerItem,
		selectItem,
		isVisible: (value) => visible().includes(value),
		isActive: (value) => value === activeValue(),
		groupHasVisible,
		listboxId,
		getItemId,
		close,
	};

	return (
		<CommandContext.Provider value={ctx}>
			<Show when={!managed() || isOpen()}>
				<div
					data-command-root=''
					class={local.class}
					{...rest}>
					{local.children}
				</div>
			</Show>
		</CommandContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

function Input(props: CommandInputProps) {
	const [local, rest] = splitProps(props, ['class', 'onKeyDown']);
	const ctx = useCommandContext();
	const activeId = () => (ctx.activeValue ? ctx.getItemId(ctx.activeValue) : undefined);

	const handleKeyDown: JSX.EventHandler<HTMLInputElement, KeyboardEvent> = (e) => {
		const userOnKeyDown = local.onKeyDown;
		if (typeof userOnKeyDown === 'function') {
			(userOnKeyDown as (event: typeof e) => void)(e);
		}
		if (e.defaultPrevented) return;
		if (e.key === 'ArrowDown') {
			e.preventDefault();
			ctx.moveActive(1);
		} else if (e.key === 'ArrowUp') {
			e.preventDefault();
			ctx.moveActive(-1);
		} else if (e.key === 'Home') {
			e.preventDefault();
			ctx.setActiveEdge('first');
		} else if (e.key === 'End') {
			e.preventDefault();
			ctx.setActiveEdge('last');
		} else if (e.key === 'Enter' && ctx.activeValue) {
			e.preventDefault();
			ctx.selectItem(ctx.activeValue);
		} else if (e.key === 'Escape') {
			e.preventDefault();
			ctx.close();
		}
	};

	return (
		<input
			type='text'
			role='combobox'
			autocomplete='off'
			autocorrect='off'
			spellcheck={false}
			aria-expanded={true}
			aria-controls={ctx.listboxId}
			aria-activedescendant={activeId()}
			value={ctx.query}
			class={local.class}
			{...rest}
			onInput={(e) => ctx.setQuery(e.currentTarget.value)}
			onKeyDown={handleKeyDown}
		/>
	);
}

// ---------------------------------------------------------------------------
// List
// ---------------------------------------------------------------------------

function List(props: CommandListProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	const ctx = useCommandContext();
	return (
		<div
			role='listbox'
			id={ctx.listboxId}
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Group
// ---------------------------------------------------------------------------

function Group(props: CommandGroupProps) {
	const [local, rest] = splitProps(props, ['heading', 'class', 'children']);
	const ctx = useCommandContext();
	const groupId = createId('command-group');
	const hasVisible = () => ctx.groupHasVisible(groupId);
	const headingId = `${groupId}-heading`;

	const groupCtx: CommandGroupContextValue = { groupId };

	return (
		<CommandGroupContext.Provider value={groupCtx}>
			<div
				role='group'
				aria-labelledby={local.heading != null ? headingId : undefined}
				hidden={!hasVisible() ? true : undefined}
				class={local.class}
				{...rest}>
				<Show when={local.heading != null}>
					<div
						id={headingId}
						data-command-group-heading=''
						aria-hidden='true'>
						{local.heading}
					</div>
				</Show>
				{local.children}
			</div>
		</CommandGroupContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

function Item(props: CommandItemProps) {
	const [local, rest] = splitProps(props, ['value', 'keywords', 'disabled', 'onSelect', 'class', 'children']);
	const ctx = useCommandContext();
	const group = useContext(CommandGroupContext);

	const disabled = () => local.disabled ?? false;

	// Registration captures identity (value/keywords/disabled) at setup; `onSelect`
	// is read lazily via the getter so it always sees the latest handler.
	/* eslint-disable solid/reactivity */
	const dispose = ctx.registerItem(local.value, {
		keywords: local.keywords ?? [],
		disabled: disabled(),
		groupId: group?.groupId,
		getOnSelect: () => local.onSelect,
	});
	/* eslint-enable solid/reactivity */
	onCleanup(dispose);

	const active = () => ctx.isActive(local.value);

	const callUserHandler = <E,>(handler: unknown, e: E) => {
		if (typeof handler === 'function') (handler as (event: E) => void)(e);
	};

	const handlePointerMove: JSX.EventHandler<HTMLDivElement, PointerEvent> = (e) => {
		if (!disabled()) ctx.setActiveValue(local.value);
		callUserHandler(rest.onPointerMove, e);
	};
	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		if (!disabled()) ctx.selectItem(local.value);
		callUserHandler(rest.onClick, e);
	};

	return (
		<Show when={ctx.isVisible(local.value)}>
			<div
				role='option'
				id={ctx.getItemId(local.value)}
				aria-selected={active()}
				aria-disabled={disabled() || undefined}
				data-active={active() ? '' : undefined}
				data-disabled={disabled() ? '' : undefined}
				class={local.class}
				{...rest}
				onPointerMove={handlePointerMove}
				onClick={handleClick}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Separator
// ---------------------------------------------------------------------------

function Separator(props: CommandSeparatorProps) {
	const [local, rest] = splitProps(props, ['class']);
	const ctx = useCommandContext();
	// Separators are noise while filtering.
	// `role="separator"` is not an allowed child of `role="listbox"` (per the ARIA
	// listbox spec, which permits only `option` and `group`). The divider is purely
	// a visual cue between groups, so it is presentational and carries no semantics.
	return (
		<Show when={!ctx.searching}>
			<div
				role='none'
				class={local.class}
				{...rest}
			/>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Empty
// ---------------------------------------------------------------------------

function Empty(props: CommandEmptyProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	const ctx = useCommandContext();
	return (
		<Show when={ctx.visible.length === 0}>
			<div
				role='presentation'
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Command = {
	Root,
	Input,
	List,
	Group,
	Item,
	Separator,
	Empty,
};

export { Root, Input, List, Group, Item, Separator, Empty };
