// packages/solid/src/components/tag/Tag.tsx
'use client';

import { splitProps } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type { TagLabelProps, TagRemoveProps, TagRootProps } from './Tag.types';

function Root(props: TagRootProps) {
	const [local, rest] = splitProps(props, ['disabled', 'class', 'children']);
	return (
		<span
			class={local.class}
			data-disabled={local.disabled ? '' : undefined}
			{...rest}>
			{local.children}
		</span>
	);
}

function Label(props: TagLabelProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<span
			class={local.class}
			{...rest}>
			{local.children}
		</span>
	);
}

function Remove(props: TagRemoveProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'aria-label']);
	const state = createInteractiveState();
	const merged = mergeProps(rest, state.handlers);
	const ariaLabel = () => local['aria-label'] ?? 'Remove';

	return (
		<button
			type='button'
			aria-label={ariaLabel()}
			class={local.class}
			{...state.dataAttributes}
			{...merged}>
			{local.children}
		</button>
	);
}

export const Tag = { Root, Label, Remove };

export { Root, Label, Remove };

// packages/react/src/components/tag/Tag.tsx
import React from 'react';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type { TagLabelProps, TagRemoveProps, TagRootProps } from './Tag.types';

const Root = React.forwardRef<HTMLSpanElement, TagRootProps>(
	({ disabled = false, className, children, ...rest }, ref) => (
		<span
			ref={ref}
			className={className}
			data-disabled={disabled ? '' : undefined}
			{...rest}>
			{children}
		</span>
	),
);
Root.displayName = 'Tag.Root';

const Label = React.forwardRef<HTMLSpanElement, TagLabelProps>(({ className, children, ...rest }, ref) => (
	<span
		ref={ref}
		className={className}
		{...rest}>
		{children}
	</span>
));
Label.displayName = 'Tag.Label';

const Remove = React.forwardRef<HTMLButtonElement, TagRemoveProps>(
	({ className, children, 'aria-label': ariaLabel = 'Remove', ...rest }, ref) => {
		const { handlers, dataAttributes } = useInteractiveState();
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		return (
			<button
				ref={ref}
				type='button'
				aria-label={ariaLabel}
				className={className}
				{...dataAttributes}
				{...merged}>
				{children}
			</button>
		);
	},
);
Remove.displayName = 'Tag.Remove';

export const Tag = { Root, Label, Remove };
