// packages/react/src/components/hover-card/HoverCard.tsx
import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef } from 'react';
import { useControllableState } from '@/hooks/use-controllable-state';
import type {
	HoverCardContentProps,
	HoverCardContextValue,
	HoverCardRootProps,
	HoverCardSide,
	HoverCardTriggerProps,
} from './HoverCard.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const HoverCardContext = createContext<HoverCardContextValue | null>(null);

function useHoverCardContext() {
	const ctx = useContext(HoverCardContext);
	if (!ctx) throw new globalThis.Error('HoverCard sub-components must be used within HoverCard.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = ({
	children,
	open: controlledOpen,
	defaultOpen = false,
	onOpenChange,
	openDelay = 300,
	closeDelay = 200,
}: HoverCardRootProps) => {
	const [open, setOpen] = useControllableState({
		value: controlledOpen,
		defaultValue: defaultOpen,
		onChange: onOpenChange,
	});

	const openTimer = useRef<ReturnType<typeof globalThis.setTimeout> | null>(null);
	const closeTimer = useRef<ReturnType<typeof globalThis.setTimeout> | null>(null);

	const clearTimers = useCallback(() => {
		if (openTimer.current) globalThis.clearTimeout(openTimer.current);
		if (closeTimer.current) globalThis.clearTimeout(closeTimer.current);
		openTimer.current = null;
		closeTimer.current = null;
	}, []);

	useEffect(() => clearTimers, [clearTimers]);

	const scheduleOpen = useCallback(() => {
		if (closeTimer.current) globalThis.clearTimeout(closeTimer.current);
		closeTimer.current = null;
		if (openTimer.current) return;
		openTimer.current = globalThis.setTimeout(() => {
			openTimer.current = null;
			setOpen(true);
		}, openDelay);
	}, [openDelay, setOpen]);

	const scheduleClose = useCallback(() => {
		if (openTimer.current) globalThis.clearTimeout(openTimer.current);
		openTimer.current = null;
		if (closeTimer.current) return;
		closeTimer.current = globalThis.setTimeout(() => {
			closeTimer.current = null;
			setOpen(false);
		}, closeDelay);
	}, [closeDelay, setOpen]);

	const openNow = useCallback(() => {
		clearTimers();
		setOpen(true);
	}, [clearTimers, setOpen]);

	const closeNow = useCallback(() => {
		clearTimers();
		setOpen(false);
	}, [clearTimers, setOpen]);

	const ctx = useMemo<HoverCardContextValue>(
		() => ({ open, scheduleOpen, scheduleClose, openNow, closeNow }),
		[open, scheduleOpen, scheduleClose, openNow, closeNow],
	);

	return (
		<HoverCardContext.Provider value={ctx}>
			<span style={{ position: 'relative', display: 'inline-block' }}>{children}</span>
		</HoverCardContext.Provider>
	);
};

Root.displayName = 'HoverCard.Root';

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLSpanElement, HoverCardTriggerProps>(
	({ children, onMouseEnter, onMouseLeave, onFocus, onBlur, ...rest }, ref) => {
		const ctx = useHoverCardContext();
		return (
			<span
				ref={ref}
				data-state={ctx.open ? 'open' : 'closed'}
				{...rest}
				onMouseEnter={(e) => {
					ctx.scheduleOpen();
					onMouseEnter?.(e);
				}}
				onMouseLeave={(e) => {
					ctx.scheduleClose();
					onMouseLeave?.(e);
				}}
				onFocus={(e) => {
					ctx.openNow();
					onFocus?.(e);
				}}
				onBlur={(e) => {
					ctx.closeNow();
					onBlur?.(e);
				}}>
				{children}
			</span>
		);
	},
);

Trigger.displayName = 'HoverCard.Trigger';

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function positionFor(side: HoverCardSide, offset: number): React.CSSProperties {
	switch (side) {
		case 'top':
			return { bottom: '100%', left: '50%', transform: 'translateX(-50%)', marginBottom: offset };
		case 'bottom':
			return { top: '100%', left: '50%', transform: 'translateX(-50%)', marginTop: offset };
		case 'left':
			return { right: '100%', top: '50%', transform: 'translateY(-50%)', marginRight: offset };
		case 'right':
			return { left: '100%', top: '50%', transform: 'translateY(-50%)', marginLeft: offset };
	}
}

const Content = React.forwardRef<HTMLDivElement, HoverCardContentProps>(
	({ side = 'bottom', sideOffset = 8, forceMount = false, className, children, style, onMouseEnter, onMouseLeave, ...rest }, ref) => {
		const ctx = useHoverCardContext();
		if (!forceMount && !ctx.open) return null;

		return (
			<div
				ref={ref}
				role='dialog'
				hidden={forceMount && !ctx.open ? true : undefined}
				data-state={ctx.open ? 'open' : 'closed'}
				data-side={side}
				className={className}
				style={{ position: 'absolute', zIndex: 50, ...positionFor(side, sideOffset), ...style }}
				{...rest}
				onMouseEnter={(e) => {
					ctx.scheduleOpen();
					onMouseEnter?.(e);
				}}
				onMouseLeave={(e) => {
					ctx.scheduleClose();
					onMouseLeave?.(e);
				}}>
				{children}
			</div>
		);
	},
);

Content.displayName = 'HoverCard.Content';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const HoverCard = {
	Root,
	Trigger,
	Content,
};

// packages/solid/src/components/hover-card/HoverCard.tsx
'use client';

import { createContext, splitProps, useContext, Show, type JSX } from 'solid-js';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createTimeout } from '@/primitives/create-timeout';
import type {
	HoverCardContentProps,
	HoverCardContextValue,
	HoverCardRootProps,
	HoverCardSide,
	HoverCardTriggerProps,
} from './HoverCard.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const HoverCardContext = createContext<HoverCardContextValue | null>(null);

function useHoverCardContext() {
	const ctx = useContext(HoverCardContext);
	if (!ctx) throw new Error('HoverCard sub-components must be used within HoverCard.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: HoverCardRootProps) {
	const [open, setOpen] = createControllableState<boolean>({
		get value() {
			return props.open;
		},
		defaultValue: props.defaultOpen ?? false,
		get onChange() {
			return props.onOpenChange;
		},
	});

	const openTimer = createTimeout(() => setOpen(true), () => props.openDelay ?? 300, { autoStart: false });
	const closeTimer = createTimeout(() => setOpen(false), () => props.closeDelay ?? 200, { autoStart: false });

	const scheduleOpen = () => {
		closeTimer.stop();
		if (openTimer.isPending()) return;
		openTimer.start();
	};

	const scheduleClose = () => {
		openTimer.stop();
		if (closeTimer.isPending()) return;
		closeTimer.start();
	};

	const openNow = () => {
		openTimer.stop();
		closeTimer.stop();
		setOpen(true);
	};

	const closeNow = () => {
		openTimer.stop();
		closeTimer.stop();
		setOpen(false);
	};

	const ctxValue: HoverCardContextValue = {
		get open() {
			return !!open();
		},
		scheduleOpen,
		scheduleClose,
		openNow,
		closeNow,
	};

	return (
		<HoverCardContext.Provider value={ctxValue}>
			<span style={{ position: 'relative', display: 'inline-block' }}>{props.children}</span>
		</HoverCardContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: HoverCardTriggerProps) {
	const [local, rest] = splitProps(props, ['children', 'onMouseEnter', 'onMouseLeave', 'onFocus', 'onBlur']);
	const ctx = useHoverCardContext();

	const callUserHandler = <E,>(handler: unknown, e: E) => {
		if (typeof handler === 'function') (handler as (event: E) => void)(e);
	};

	// Compose consumer-provided handlers with our internal ones — the consumer's
	// fires first, then ours.
	const handleMouseEnter: JSX.EventHandler<HTMLSpanElement, MouseEvent> = (e) => {
		callUserHandler(local.onMouseEnter, e);
		ctx.scheduleOpen();
	};
	const handleMouseLeave: JSX.EventHandler<HTMLSpanElement, MouseEvent> = (e) => {
		callUserHandler(local.onMouseLeave, e);
		ctx.scheduleClose();
	};
	const handleFocus: JSX.EventHandler<HTMLSpanElement, FocusEvent> = (e) => {
		callUserHandler(local.onFocus, e);
		ctx.openNow();
	};
	const handleBlur: JSX.EventHandler<HTMLSpanElement, FocusEvent> = (e) => {
		callUserHandler(local.onBlur, e);
		ctx.closeNow();
	};

	return (
		<span
			data-state={ctx.open ? 'open' : 'closed'}
			onMouseEnter={handleMouseEnter}
			onMouseLeave={handleMouseLeave}
			onFocus={handleFocus}
			onBlur={handleBlur}
			{...rest}>
			{local.children}
		</span>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function positionFor(side: HoverCardSide, offset: number): JSX.CSSProperties {
	const px = `${offset}px`;
	switch (side) {
		case 'top':
			return { bottom: '100%', left: '50%', transform: 'translateX(-50%)', 'margin-bottom': px };
		case 'bottom':
			return { top: '100%', left: '50%', transform: 'translateX(-50%)', 'margin-top': px };
		case 'left':
			return { right: '100%', top: '50%', transform: 'translateY(-50%)', 'margin-right': px };
		case 'right':
			return { left: '100%', top: '50%', transform: 'translateY(-50%)', 'margin-left': px };
	}
}

function Content(props: HoverCardContentProps) {
	const [local, rest] = splitProps(props, [
		'side',
		'sideOffset',
		'forceMount',
		'class',
		'children',
		'style',
		'onMouseEnter',
		'onMouseLeave',
	]);
	const ctx = useHoverCardContext();

	const side = () => local.side ?? 'bottom';
	const sideOffset = () => local.sideOffset ?? 8;

	const baseStyle = (): JSX.CSSProperties => ({
		position: 'absolute',
		'z-index': 50,
		...positionFor(side(), sideOffset()),
	});

	const mergedStyle = () => {
		const userStyle = local.style;
		if (typeof userStyle === 'string' || !userStyle) return baseStyle();
		return { ...baseStyle(), ...(userStyle as JSX.CSSProperties) };
	};

	const callUserHandler = <E,>(handler: unknown, e: E) => {
		if (typeof handler === 'function') (handler as (event: E) => void)(e);
	};

	const handleMouseEnter: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		callUserHandler(local.onMouseEnter, e);
		ctx.scheduleOpen();
	};
	const handleMouseLeave: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		callUserHandler(local.onMouseLeave, e);
		ctx.scheduleClose();
	};

	return (
		<Show when={local.forceMount || ctx.open}>
			<div
				role='dialog'
				hidden={local.forceMount && !ctx.open ? true : undefined}
				data-state={ctx.open ? 'open' : 'closed'}
				data-side={side()}
				class={local.class}
				style={mergedStyle()}
				onMouseEnter={handleMouseEnter}
				onMouseLeave={handleMouseLeave}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const HoverCard = {
	Root,
	Trigger,
	Content,
};

export { Root, Trigger, Content };
