// packages/solid/src/components/form/Form.tsx
import {
	children as resolveChildren,
	createContext,
	createEffect,
	createSignal,
	createUniqueId,
	onCleanup,
	Show,
	splitProps,
	useContext,
	type JSX,
} from 'solid-js';
import type {
	FormControlProps,
	FormDescriptionProps,
	FormErrorProps,
	FormFieldContextValue,
	FormFieldProps,
	FormLabelProps,
	FormRootProps,
} from './Form.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const FormFieldContext = createContext<FormFieldContextValue | null>(null);

function useFieldContext() {
	const ctx = useContext(FormFieldContext);
	if (!ctx) throw new Error('Form field components must be used within Form.Field');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: FormRootProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	return (
		<form
			class={local.class}
			noValidate
			{...rest}>
			{local.children}
		</form>
	);
}

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

function Field(props: FormFieldProps) {
	const [local, rest] = splitProps(props, ['name', 'invalid', 'required', 'disabled', 'children', 'class']);

	const uniq = createUniqueId();
	const id = () => (local.name ? `${local.name}-${uniq}` : uniq);
	const descriptionId = () => `${id()}-description`;
	const errorId = () => `${id()}-error`;

	const [hasDescription, setHasDescription] = createSignal(false);
	const [hasError, setHasError] = createSignal(false);

	const ctxValue: FormFieldContextValue = {
		get id() {
			return id();
		},
		get descriptionId() {
			return descriptionId();
		},
		get errorId() {
			return errorId();
		},
		get name() {
			return local.name;
		},
		get invalid() {
			return !!local.invalid;
		},
		get required() {
			return !!local.required;
		},
		get disabled() {
			return !!local.disabled;
		},
		get hasDescription() {
			return hasDescription();
		},
		get hasError() {
			return hasError();
		},
		registerDescription: setHasDescription,
		registerError: setHasError,
	};

	return (
		<FormFieldContext.Provider value={ctxValue}>
			<div
				class={local.class}
				data-invalid={local.invalid ? '' : undefined}
				data-required={local.required ? '' : undefined}
				data-disabled={local.disabled ? '' : undefined}
				{...rest}>
				{local.children}
			</div>
		</FormFieldContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Label
// ---------------------------------------------------------------------------

function Label(props: FormLabelProps) {
	const [local, rest] = splitProps(props, ['asChild', 'class', 'children']);
	const ctx = useFieldContext();

	// asChild is read once at setup — toggling it post-mount isn't supported.
	// eslint-disable-next-line solid/reactivity
	if (local.asChild) {
		// Solid evaluates JSX children to DOM nodes, so we mutate the child's
		// attributes / class imperatively rather than cloning.
		const resolved = resolveChildren(() => local.children);

		createEffect(() => {
			const el = resolved() as HTMLElement | null;
			if (!(el instanceof HTMLElement)) return;
			el.setAttribute('for', ctx.id);
			if (local.class) {
				const existing = el.getAttribute('class') ?? '';
				el.setAttribute('class', [existing, local.class].filter(Boolean).join(' '));
			}
			for (const [key, value] of Object.entries(rest)) {
				if (value === undefined || value === null || typeof value === 'function') continue;
				el.setAttribute(key, String(value));
			}
		});

		// eslint-disable-next-line solid/components-return-once
		return resolved() as unknown as JSX.Element;
	}

	return (
		<label
			for={ctx.id}
			class={local.class}
			data-invalid={ctx.invalid ? '' : undefined}
			data-required={ctx.required ? '' : undefined}
			data-disabled={ctx.disabled ? '' : undefined}
			{...rest}>
			{local.children}
		</label>
	);
}

// ---------------------------------------------------------------------------
// Control — mutates the single child element to inject id/aria-* attributes
// ---------------------------------------------------------------------------

function Control(props: FormControlProps) {
	const ctx = useFieldContext();
	const resolved = resolveChildren(() => props.children);

	createEffect(() => {
		const el = resolved() as HTMLElement | null;
		if (!(el instanceof HTMLElement)) return;

		el.setAttribute('id', ctx.id);
		if (ctx.name && !el.hasAttribute('name')) el.setAttribute('name', ctx.name);

		// Merge aria-describedby with whatever the child already has.
		const existingDescribedBy = el.getAttribute('aria-describedby') ?? '';
		const parts = [
			ctx.hasDescription ? ctx.descriptionId : null,
			ctx.hasError ? ctx.errorId : null,
			existingDescribedBy || null,
		].filter(Boolean);
		if (parts.length > 0) {
			el.setAttribute('aria-describedby', parts.join(' '));
		} else {
			el.removeAttribute('aria-describedby');
		}

		const setOrRemoveAttr = (key: string, on: boolean, value: string) => {
			if (on) el.setAttribute(key, value);
			else el.removeAttribute(key);
		};

		setOrRemoveAttr('aria-invalid', ctx.invalid, 'true');
		setOrRemoveAttr('aria-required', ctx.required, 'true');
		setOrRemoveAttr('data-invalid', ctx.invalid, '');
		setOrRemoveAttr('data-required', ctx.required, '');
		setOrRemoveAttr('data-disabled', ctx.disabled, '');

		if (ctx.disabled) {
			(el as HTMLInputElement).disabled = true;
		}
	});

	return resolved() as unknown as JSX.Element;
}

// ---------------------------------------------------------------------------
// Description
// ---------------------------------------------------------------------------

function Description(props: FormDescriptionProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	const ctx = useFieldContext();

	ctx.registerDescription(true);
	onCleanup(() => ctx.registerDescription(false));

	return (
		<div
			id={ctx.descriptionId}
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

function ErrorMessage(props: FormErrorProps) {
	const [local, rest] = splitProps(props, ['forceMount', 'class', 'children']);
	const ctx = useFieldContext();
	const visible = () => !!local.forceMount || ctx.invalid;

	createEffect(() => {
		ctx.registerError(visible());
	});
	onCleanup(() => ctx.registerError(false));

	return (
		<Show when={visible()}>
			<div
				id={ctx.errorId}
				role='alert'
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Form = { Root, Field, Label, Control, Description, Error: ErrorMessage };

// packages/react/src/components/form/Form.tsx
import React, { createContext, useContext, useMemo, useState } from 'react';
import { useId } from '@/hooks/use-id';
import type {
	FormControlProps,
	FormDescriptionProps,
	FormErrorProps,
	FormFieldContextValue,
	FormFieldProps,
	FormLabelProps,
	FormRootProps,
} from './Form.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const FormFieldContext = createContext<FormFieldContextValue | null>(null);

function useFieldContext() {
	const ctx = useContext(FormFieldContext);
	if (!ctx) throw new globalThis.Error('Form field components must be used within Form.Field');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLFormElement, FormRootProps>(({ children, className, ...rest }, ref) => (
	<form
		ref={ref}
		className={className}
		noValidate
		{...rest}>
		{children}
	</form>
));
Root.displayName = 'Form.Root';

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

const Field = React.forwardRef<HTMLDivElement, FormFieldProps>(
	({ name, invalid = false, required = false, disabled = false, children, className, ...rest }, ref) => {
		const id = useId(name ?? 'field');
		const descriptionId = `${id}-description`;
		const errorId = `${id}-error`;

		const [hasDescription, setHasDescription] = useState(false);
		const [hasError, setHasError] = useState(false);

		const ctx = useMemo<FormFieldContextValue>(
			() => ({
				id,
				descriptionId,
				errorId,
				name,
				invalid,
				required,
				disabled,
				hasDescription,
				hasError,
				registerDescription: setHasDescription,
				registerError: setHasError,
			}),
			[id, descriptionId, errorId, name, invalid, required, disabled, hasDescription, hasError],
		);

		return (
			<FormFieldContext.Provider value={ctx}>
				<div
					ref={ref}
					className={className}
					data-invalid={invalid ? '' : undefined}
					data-required={required ? '' : undefined}
					data-disabled={disabled ? '' : undefined}
					{...rest}>
					{children}
				</div>
			</FormFieldContext.Provider>
		);
	},
);
Field.displayName = 'Form.Field';

// ---------------------------------------------------------------------------
// Label
// ---------------------------------------------------------------------------

const Label = React.forwardRef<HTMLLabelElement, FormLabelProps>(
	({ asChild = false, className, children, ...rest }, ref) => {
		const ctx = useFieldContext();
		if (asChild && React.isValidElement(children)) {
			const child = children as React.ReactElement<Record<string, unknown>>;
			// cloneElement assigns the ref to the new element without reading ref.current.
			// eslint-disable-next-line react-hooks/refs
			return React.cloneElement(child, {
				...rest,
				htmlFor: ctx.id,
				className: [(child.props as { className?: string }).className, className].filter(Boolean).join(' '),
				ref,
			} as Record<string, unknown>);
		}
		return (
			<label
				ref={ref}
				htmlFor={ctx.id}
				className={className}
				data-invalid={ctx.invalid ? '' : undefined}
				data-required={ctx.required ? '' : undefined}
				data-disabled={ctx.disabled ? '' : undefined}
				{...rest}>
				{children}
			</label>
		);
	},
);
Label.displayName = 'Form.Label';

// ---------------------------------------------------------------------------
// Control — clones the single child input and injects id/aria-* attributes
// ---------------------------------------------------------------------------

const Control: React.FC<FormControlProps> = ({ children }) => {
	const ctx = useFieldContext();
	if (!React.isValidElement(children)) {
		throw new globalThis.Error('Form.Control requires exactly one React element child.');
	}

	const child = children as React.ReactElement<Record<string, unknown>>;
	const childProps = child.props as Record<string, unknown>;

	const describedBy = [
		ctx.hasDescription ? ctx.descriptionId : null,
		ctx.hasError ? ctx.errorId : null,
		childProps['aria-describedby'] as string | undefined,
	]
		.filter(Boolean)
		.join(' ') || undefined;

	return React.cloneElement(child, {
		id: ctx.id,
		name: ctx.name ?? (childProps.name as string | undefined),
		'aria-invalid': ctx.invalid || undefined,
		'aria-required': ctx.required || undefined,
		'aria-describedby': describedBy,
		disabled: ctx.disabled || (childProps.disabled as boolean | undefined),
		'data-invalid': ctx.invalid ? '' : undefined,
		'data-required': ctx.required ? '' : undefined,
		'data-disabled': ctx.disabled ? '' : undefined,
	} as Record<string, unknown>);
};
Control.displayName = 'Form.Control';

// ---------------------------------------------------------------------------
// Description
// ---------------------------------------------------------------------------

const Description = React.forwardRef<HTMLDivElement, FormDescriptionProps>(
	({ className, children, ...rest }, ref) => {
		const ctx = useFieldContext();
		React.useEffect(() => {
			ctx.registerDescription(true);
			return () => ctx.registerDescription(false);
		}, [ctx]);

		return (
			<div
				ref={ref}
				id={ctx.descriptionId}
				className={className}
				{...rest}>
				{children}
			</div>
		);
	},
);
Description.displayName = 'Form.Description';

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

const Error = React.forwardRef<HTMLDivElement, FormErrorProps>(
	({ forceMount = false, className, children, ...rest }, ref) => {
		const ctx = useFieldContext();
		const visible = forceMount || ctx.invalid;

		React.useEffect(() => {
			ctx.registerError(visible);
			return () => ctx.registerError(false);
		}, [ctx, visible]);

		if (!visible) return null;

		return (
			<div
				ref={ref}
				id={ctx.errorId}
				role='alert'
				className={className}
				{...rest}>
				{children}
			</div>
		);
	},
);
Error.displayName = 'Form.Error';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Form = { Root, Field, Label, Control, Description, Error };
