// packages/react/src/components/context-menu/ContextMenu.tsx
import React, {
	createContext,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useRef,
	useState,
} from 'react';
import { createPortal } from 'react-dom';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	ContextMenuContentProps,
	ContextMenuContextValue,
	ContextMenuItemProps,
	ContextMenuRootProps,
	ContextMenuSeparatorProps,
	ContextMenuTriggerProps,
} from './ContextMenu.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

interface ContextMenuInternalContext extends ContextMenuContextValue {
	contentRef: React.MutableRefObject<HTMLDivElement | null>;
}

const ContextMenuContext = createContext<ContextMenuInternalContext | null>(null);

function useContextMenuContext() {
	const ctx = useContext(ContextMenuContext);
	if (!ctx) throw new globalThis.Error('ContextMenu compound components must be used within ContextMenu.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, ContextMenuRootProps>(
	(
		{
			open: controlledOpen,
			defaultOpen = false,
			onOpenChange,
			disabled = false,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [uncontrolledOpen, setUncontrolledOpen] = useState<boolean>(defaultOpen);
		const isControlled = controlledOpen !== undefined;
		const open = isControlled ? (controlledOpen as boolean) : uncontrolledOpen;
		const [position, setPosition] = useState({ x: 0, y: 0 });

		const setOpen = useCallback(
			(next: boolean) => {
				if (!isControlled) setUncontrolledOpen(next);
				onOpenChange?.(next);
			},
			[isControlled, onOpenChange],
		);

		const openAt = useCallback(
			(x: number, y: number) => {
				setPosition({ x, y });
				setOpen(true);
			},
			[setOpen],
		);

		const close = useCallback(() => setOpen(false), [setOpen]);

		const internalRef = useRef<HTMLDivElement | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const setMergedRef = (el: HTMLDivElement | null) => {
			internalRef.current = el;
			if (typeof ref === 'function') ref(el);
			else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el;
		};

		// Close on any pointer activity outside the menu content. Clicks on the
		// trigger wrapper, surrounding container, or anywhere else on the page
		// all dismiss the menu. (Right-clicks elsewhere on a Trigger reopen at
		// the new position via the contextmenu handler.)
		useEffect(() => {
			if (!open) return;
			const handlePointer = (e: MouseEvent | TouchEvent) => {
				const target = e.target as Node | null;
				if (!target) return;
				// Only the portaled menu content keeps the menu open.
				if (contentRef.current?.contains(target)) return;
				close();
			};
			// `mousedown` runs before `contextmenu`, so re-right-clicking a Trigger
			// closes-then-reopens at the fresh cursor position.
			document.addEventListener('mousedown', handlePointer);
			document.addEventListener('touchstart', handlePointer);
			return () => {
				document.removeEventListener('mousedown', handlePointer);
				document.removeEventListener('touchstart', handlePointer);
			};
		}, [open, close]);

		useEffect(() => {
			const handle = (e: KeyboardEvent) => {
				if (e.key === 'Escape' && open) close();
			};
			window.addEventListener('keyup', handle);
			return () => window.removeEventListener('keyup', handle);
		}, [open, close]);

		// Block scroll inputs while open without hiding overflow — the scrollbar
		// stays in place (no layout shift), but mouse wheel, trackpad, touch, and
		// scroll keys all become no-ops outside the menu.
		useEffect(() => {
			if (!open) return;
			if (typeof document === 'undefined') return;

			const isInsideMenu = (target: EventTarget | null) =>
				target instanceof Node && !!contentRef.current?.contains(target);

			const preventWheel = (e: WheelEvent) => {
				if (isInsideMenu(e.target)) return;
				e.preventDefault();
			};

			const preventTouchMove = (e: TouchEvent) => {
				if (isInsideMenu(e.target)) return;
				e.preventDefault();
			};

			const SCROLL_KEYS = new Set([
				'ArrowUp',
				'ArrowDown',
				'ArrowLeft',
				'ArrowRight',
				'PageUp',
				'PageDown',
				'Home',
				'End',
				' ',
			]);
			const preventScrollKeys = (e: KeyboardEvent) => {
				if (!SCROLL_KEYS.has(e.key)) return;
				const target = e.target as HTMLElement | null;
				if (target) {
					// Let editable elements receive the key (typing, cursor movement).
					const tag = target.tagName;
					if (tag === 'INPUT' || tag === 'TEXTAREA' || target.isContentEditable) return;
					if (contentRef.current?.contains(target)) return;
				}
				e.preventDefault();
			};

			// passive: false is required for preventDefault to take effect on these.
			document.addEventListener('wheel', preventWheel, { passive: false });
			document.addEventListener('touchmove', preventTouchMove, { passive: false });
			document.addEventListener('keydown', preventScrollKeys);
			return () => {
				document.removeEventListener('wheel', preventWheel);
				document.removeEventListener('touchmove', preventTouchMove);
				document.removeEventListener('keydown', preventScrollKeys);
			};
		}, [open]);

		const ctx = useMemo(
			() => ({ open, disabled, position, openAt, close, contentRef }),
			[open, disabled, position, openAt, close],
		);

		return (
			<ContextMenuContext.Provider value={ctx}>
				<div
					ref={setMergedRef}
					className={className}
					data-state={open ? 'open' : 'closed'}
					{...rest}>
					{children}
				</div>
			</ContextMenuContext.Provider>
		);
	},
);
Root.displayName = 'ContextMenu.Root';

// ---------------------------------------------------------------------------
// Trigger (catches the contextmenu event)
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLDivElement, ContextMenuTriggerProps>(
	({ children, className, onContextMenu, ...rest }, ref) => {
		const ctx = useContextMenuContext();

		return (
			<div
				ref={ref}
				className={className}
				data-state={ctx.open ? 'open' : 'closed'}
				{...rest}
				onContextMenu={(e) => {
					if (!ctx.disabled) {
						e.preventDefault();
						ctx.openAt(e.clientX, e.clientY);
					}
					onContextMenu?.(e);
				}}>
				{children}
			</div>
		);
	},
);
Trigger.displayName = 'ContextMenu.Trigger';

// ---------------------------------------------------------------------------
// Content (positioned at the cursor)
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLDivElement, ContextMenuContentProps>(
	({ children, className, style, ...rest }, ref) => {
		const ctx = useContextMenuContext();

		const setMergedRef = (el: HTMLDivElement | null) => {
			ctx.contentRef.current = el;
			if (typeof ref === 'function') ref(el);
			else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el;
		};

		if (!ctx.open) return null;
		if (typeof document === 'undefined') return null;

		const node = (
			<div
				ref={setMergedRef}
				role='menu'
				className={className}
				data-state='open'
				style={{
					position: 'fixed',
					left: ctx.position.x,
					top: ctx.position.y,
					zIndex: 50,
					...style,
				}}
				{...rest}>
				{children}
			</div>
		);

		// Portal to <body> so the menu escapes any transformed/contained ancestor
		// (Storybook docs containers, addon wrappers, etc.) and `position: fixed`
		// resolves against the actual viewport.
		return createPortal(node, document.body);
	},
);
Content.displayName = 'ContextMenu.Content';

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

const Item = React.forwardRef<HTMLDivElement, ContextMenuItemProps>(
	({ disabled = false, onSelect, children, className, onClick, onKeyDown, ...rest }, ref) => {
		const ctx = useContextMenuContext();
		const { handlers, dataAttributes } = useInteractiveState({ disabled });
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		const select = () => {
			if (disabled) return;
			onSelect?.();
			ctx.close();
		};

		return (
			<div
				ref={ref}
				role='menuitem'
				tabIndex={disabled ? -1 : 0}
				aria-disabled={disabled || undefined}
				className={className}
				data-disabled={disabled ? '' : undefined}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					select();
					onClick?.(e);
				}}
				onKeyDown={(e) => {
					if (e.key === 'Enter' || e.key === ' ') {
						e.preventDefault();
						select();
					}
					onKeyDown?.(e);
				}}>
				{children}
			</div>
		);
	},
);
Item.displayName = 'ContextMenu.Item';

// ---------------------------------------------------------------------------
// Separator
// ---------------------------------------------------------------------------

const Separator = React.forwardRef<HTMLDivElement, ContextMenuSeparatorProps>(
	({ className, ...rest }, ref) => (
		<div
			ref={ref}
			role='separator'
			className={className}
			{...rest}
		/>
	),
);
Separator.displayName = 'ContextMenu.Separator';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const ContextMenu = { Root, Trigger, Content, Item, Separator };

// packages/solid/src/components/context-menu/ContextMenu.tsx
import { createContext, createEffect, createSignal, onCleanup, Show, splitProps, useContext, type JSX } from 'solid-js';
import { Portal } from 'solid-js/web';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	ContextMenuContentProps,
	ContextMenuContextValue,
	ContextMenuItemProps,
	ContextMenuRootProps,
	ContextMenuSeparatorProps,
	ContextMenuTriggerProps,
} from './ContextMenu.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const ContextMenuContext = createContext<ContextMenuContextValue | null>(null);

function useContextMenuContext() {
	const ctx = useContext(ContextMenuContext);
	if (!ctx) throw new Error('ContextMenu compound components must be used within ContextMenu.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: ContextMenuRootProps) {
	const [local, rest] = splitProps(props, [
		'open',
		'defaultOpen',
		'onOpenChange',
		'disabled',
		'children',
		'class',
	]);

	const [uncontrolledOpen, setUncontrolledOpen] = createSignal<boolean>(local.defaultOpen ?? false);
	const isControlled = () => local.open !== undefined;
	const open = () => (isControlled() ? (local.open as boolean) : uncontrolledOpen());
	const [position, setPosition] = createSignal({ x: 0, y: 0 });

	const setOpen = (next: boolean) => {
		if (!isControlled()) setUncontrolledOpen(next);
		local.onOpenChange?.(next);
	};

	const openAt = (x: number, y: number) => {
		setPosition({ x, y });
		setOpen(true);
	};

	const close = () => setOpen(false);

	let contentEl: HTMLDivElement | null = null;
	const setContentEl = (el: HTMLDivElement | null) => {
		contentEl = el;
	};
	const getContentEl = () => contentEl;

	// Close on any pointer activity outside the menu content.
	createEffect(() => {
		if (!open()) return;
		const handlePointer = (e: MouseEvent | TouchEvent) => {
			const target = e.target as Node | null;
			if (!target) return;
			if (contentEl?.contains(target)) return;
			close();
		};
		document.addEventListener('mousedown', handlePointer);
		document.addEventListener('touchstart', handlePointer);
		onCleanup(() => {
			document.removeEventListener('mousedown', handlePointer);
			document.removeEventListener('touchstart', handlePointer);
		});
	});

	createEffect(() => {
		const handle = (e: KeyboardEvent) => {
			if (e.key === 'Escape' && open()) close();
		};
		window.addEventListener('keyup', handle);
		onCleanup(() => window.removeEventListener('keyup', handle));
	});

	// Block scroll inputs while open without hiding overflow.
	createEffect(() => {
		if (!open()) return;
		if (typeof document === 'undefined') return;

		const isInsideMenu = (target: EventTarget | null) =>
			target instanceof Node && !!contentEl?.contains(target);

		const preventWheel = (e: WheelEvent) => {
			if (isInsideMenu(e.target)) return;
			e.preventDefault();
		};

		const preventTouchMove = (e: TouchEvent) => {
			if (isInsideMenu(e.target)) return;
			e.preventDefault();
		};

		const SCROLL_KEYS = new Set([
			'ArrowUp',
			'ArrowDown',
			'ArrowLeft',
			'ArrowRight',
			'PageUp',
			'PageDown',
			'Home',
			'End',
			' ',
		]);
		const preventScrollKeys = (e: KeyboardEvent) => {
			if (!SCROLL_KEYS.has(e.key)) return;
			const target = e.target as HTMLElement | null;
			if (target) {
				const tag = target.tagName;
				if (tag === 'INPUT' || tag === 'TEXTAREA' || target.isContentEditable) return;
				if (contentEl?.contains(target)) return;
			}
			e.preventDefault();
		};

		document.addEventListener('wheel', preventWheel, { passive: false });
		document.addEventListener('touchmove', preventTouchMove, { passive: false });
		document.addEventListener('keydown', preventScrollKeys);
		onCleanup(() => {
			document.removeEventListener('wheel', preventWheel);
			document.removeEventListener('touchmove', preventTouchMove);
			document.removeEventListener('keydown', preventScrollKeys);
		});
	});

	const ctxValue: ContextMenuContextValue = {
		get open() {
			return open();
		},
		get disabled() {
			return !!local.disabled;
		},
		get position() {
			return position();
		},
		openAt,
		close,
		setContentEl,
		getContentEl,
	};

	return (
		<ContextMenuContext.Provider value={ctxValue}>
			<div
				class={local.class}
				data-state={open() ? 'open' : 'closed'}
				{...rest}>
				{local.children}
			</div>
		</ContextMenuContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: ContextMenuTriggerProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onContextMenu']);
	const ctx = useContextMenuContext();

	const handleContextMenu: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		if (!ctx.disabled) {
			e.preventDefault();
			ctx.openAt(e.clientX, e.clientY);
		}
		const userOnContextMenu = local.onContextMenu;
		if (typeof userOnContextMenu === 'function') {
			(userOnContextMenu as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			{...rest}
			onContextMenu={handleContextMenu}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function Content(props: ContextMenuContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'style']);
	const ctx = useContextMenuContext();

	const mergedStyle = (): JSX.CSSProperties | string | undefined => {
		const ours: JSX.CSSProperties = {
			position: 'fixed',
			left: `${ctx.position.x}px`,
			top: `${ctx.position.y}px`,
			'z-index': 50,
		};
		const user = local.style;
		if (typeof user === 'string' || !user) return ours;
		return { ...ours, ...(user as JSX.CSSProperties) };
	};

	return (
		<Show when={ctx.open}>
			<Portal>
				<div
					ref={(el) => ctx.setContentEl(el)}
					role='menu'
					class={local.class}
					data-state='open'
					style={mergedStyle()}
					{...rest}>
					{local.children}
				</div>
			</Portal>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

function Item(props: ContextMenuItemProps) {
	const [local, rest] = splitProps(props, ['disabled', 'onSelect', 'children', 'class', 'onClick', 'onKeyDown']);
	const ctx = useContextMenuContext();
	const state = createInteractiveState({
		get disabled() {
			return !!local.disabled;
		},
	});
	const merged = mergeProps(rest, state.handlers);

	const select = () => {
		if (local.disabled) return;
		local.onSelect?.();
		ctx.close();
	};

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		select();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (e) => {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			select();
		}
		const userOnKeyDown = local.onKeyDown;
		if (typeof userOnKeyDown === 'function') {
			(userOnKeyDown as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			role='menuitem'
			tabIndex={local.disabled ? -1 : 0}
			aria-disabled={local.disabled || undefined}
			class={local.class}
			data-disabled={local.disabled ? '' : undefined}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}
			onKeyDown={handleKeyDown}>
			{local.children}
		</div>
	);
}

function Separator(props: ContextMenuSeparatorProps) {
	const [local, rest] = splitProps(props, ['class']);
	return (
		<div
			role='separator'
			class={local.class}
			{...rest}
		/>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const ContextMenu = { Root, Trigger, Content, Item, Separator };
