// packages/bare-ui/src/components/badge/Badge.tsx
import React from 'react';
import type { BadgeProps } from './Badge.types';

const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(({ count = 0, className, ...rest }, ref) => {
	const displayCount =
		count > 0 ?
			count > 9 ?
				'9+'
			:	count
		:	0;

	return (
		<span
			ref={ref}
			className={className}
			data-count={count}
			{...rest}>
			{displayCount}
		</span>
	);
});

Badge.displayName = 'Badge';

export { Badge };

// packages/vue/src/components/badge/Badge.vue
<script setup lang="ts">
defineOptions({ name: 'Badge' })

const props = withDefaults(
	defineProps<{
		count?: number
	}>(),
	{ count: 0 },
)

const displayCount = () => (props.count > 0 ? (props.count > 9 ? '9+' : props.count) : 0)
</script>

<template>
	<span :data-count="count">{{ displayCount() }}</span>
</template>
