// packages/react/src/components/citation/Citation.tsx
'use client';

import React, { createContext, useCallback, useContext, useMemo } from 'react';
import { useId } from '@/hooks/use-id';
import { sanitizeUrl } from '@/utils/sanitize-url';
import type {
	CitationContextValue,
	CitationListProps,
	CitationRefProps,
	CitationRootProps,
	CitationSource,
} from './Citation.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CitationContext = createContext<CitationContextValue | null>(null);

function useCitationContext() {
	const ctx = useContext(CitationContext);
	if (!ctx) throw new globalThis.Error('Citation.Ref/List must be used within Citation.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, CitationRootProps>(
	({ sources, className, children, ...rest }, ref) => {
		const baseId = useId('citation');

		const index = useMemo(() => {
			const map = new Map<string, number>();
			sources.forEach((s, i) => map.set(s.id, i + 1));
			return map;
		}, [sources]);

		const getSource = useCallback((id: string) => sources.find((s) => s.id === id), [sources]);
		const getIndex = useCallback((id: string) => index.get(id) ?? 0, [index]);
		const getRefId = useCallback((id: string) => `${baseId}-ref-${id}`, [baseId]);
		const getFootnoteId = useCallback((id: string) => `${baseId}-note-${id}`, [baseId]);

		const ctx = useMemo<CitationContextValue>(
			() => ({ sources, getSource, getIndex, getRefId, getFootnoteId }),
			[sources, getSource, getIndex, getRefId, getFootnoteId],
		);

		return (
			<CitationContext.Provider value={ctx}>
				<div
					ref={ref}
					className={className}
					{...rest}>
					{children}
				</div>
			</CitationContext.Provider>
		);
	},
);

Root.displayName = 'Citation.Root';

// ---------------------------------------------------------------------------
// Ref — inline marker
// ---------------------------------------------------------------------------

const Ref = React.forwardRef<HTMLAnchorElement, CitationRefProps>(
	({ for: forId, children, className, ...rest }, ref) => {
		const ctx = useCitationContext();
		const source = ctx.getSource(forId);
		if (!source) return null;

		const index = ctx.getIndex(forId);
		const label = source.label ?? String(index);
		const footnoteId = ctx.getFootnoteId(forId);

		return (
			<a
				ref={ref}
				id={ctx.getRefId(forId)}
				href={`#${footnoteId}`}
				role='doc-noteref'
				aria-describedby={footnoteId}
				data-citation=''
				data-index={index}
				className={className}
				{...rest}>
				{typeof children === 'function' ?
					children({ source, index })
				: children !== undefined ?
					children
				:	<sup>{label}</sup>}
			</a>
		);
	},
);

Ref.displayName = 'Citation.Ref';

// ---------------------------------------------------------------------------
// List — footnotes
// ---------------------------------------------------------------------------

const defaultFootnote = (source: CitationSource) => {
	const text = source.title ?? source.url ?? source.id;
	// Sanitize the destination so a malicious `source.url` can't smuggle a
	// `javascript:` payload into the footnote link; fall back to plain text.
	const href = sanitizeUrl(source.url);
	return href ?
		<a
			href={href}
			target='_blank'
			rel='noreferrer'>
			{text}
		</a>
	:	<span>{text}</span>;
};

const List = React.forwardRef<HTMLOListElement, CitationListProps>(({ children, className, ...rest }, ref) => {
	const ctx = useCitationContext();
	return (
		<ol
			ref={ref}
			className={className}
			{...rest}>
			{ctx.sources.map((source, i) => {
				const index = i + 1;
				return (
					<li
						key={source.id}
						id={ctx.getFootnoteId(source.id)}
						data-citation-source=''
						data-index={index}>
						{children ? children({ source, index }) : defaultFootnote(source)}
					</li>
				);
			})}
		</ol>
	);
});

List.displayName = 'Citation.List';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Citation = {
	Root,
	Ref,
	List,
};

// Named exports expose the sub-components to Storybook's react-docgen (public API stays `Citation.*`).
export { Root, Ref, List };

// packages/solid/src/components/citation/Citation.tsx
'use client';

import { createContext, createMemo, useContext, splitProps, Show, For, type JSX } from 'solid-js';
import { createId } from '@/primitives/create-id';
import { sanitizeUrl } from '@/utils/sanitize-url';
import type {
	CitationContextValue,
	CitationListProps,
	CitationRefProps,
	CitationRootProps,
	CitationSource,
} from './Citation.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CitationContext = createContext<CitationContextValue | null>(null);

function useCitationContext() {
	const ctx = useContext(CitationContext);
	if (!ctx) throw new Error('Citation.Ref/List must be used within Citation.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: CitationRootProps) {
	const [local, rest] = splitProps(props, ['sources', 'class', 'children']);
	const baseId = createId('citation');

	const index = createMemo(() => {
		const map = new Map<string, number>();
		local.sources.forEach((s, i) => map.set(s.id, i + 1));
		return map;
	});

	const getSource = (id: string) => local.sources.find((s) => s.id === id);
	const getIndex = (id: string) => index().get(id) ?? 0;
	const getRefId = (id: string) => `${baseId}-ref-${id}`;
	const getFootnoteId = (id: string) => `${baseId}-note-${id}`;

	const ctx: CitationContextValue = {
		get sources() {
			return local.sources;
		},
		getSource,
		getIndex,
		getRefId,
		getFootnoteId,
	};

	return (
		<CitationContext.Provider value={ctx}>
			<div
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</CitationContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Ref — inline marker
// ---------------------------------------------------------------------------

function Ref(props: CitationRefProps) {
	const [local, rest] = splitProps(props, ['for', 'children', 'class']);
	const ctx = useCitationContext();

	const source = () => ctx.getSource(local.for);
	const index = () => ctx.getIndex(local.for);
	const label = () => source()?.label ?? String(index());
	const footnoteId = () => ctx.getFootnoteId(local.for);

	return (
		<Show when={source()}>
			{(src) => (
				<a
					id={ctx.getRefId(local.for)}
					href={`#${footnoteId()}`}
					// `doc-noteref` is a valid ARIA DPUB role outside Solid's typed union.
					role={'doc-noteref' as JSX.AnchorHTMLAttributes<HTMLAnchorElement>['role']}
					aria-describedby={footnoteId()}
					data-citation=''
					data-index={index()}
					class={local.class}
					{...rest}>
					{typeof local.children === 'function' ?
						local.children({ source: src(), index: index() })
					: local.children !== undefined ?
						(local.children as JSX.Element)
					:	<sup>{label()}</sup>}
				</a>
			)}
		</Show>
	);
}

// ---------------------------------------------------------------------------
// List — footnotes
// ---------------------------------------------------------------------------

const defaultFootnote = (source: CitationSource) => {
	const text = source.title ?? source.url ?? source.id;
	// Sanitize the destination so a malicious `source.url` can't smuggle a
	// `javascript:` payload into the footnote link; fall back to plain text.
	const href = sanitizeUrl(source.url);
	return href ?
			<a
				href={href}
				target='_blank'
				rel='noreferrer'>
				{text}
			</a>
		:	<span>{text}</span>;
};

function List(props: CitationListProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useCitationContext();

	return (
		<ol
			class={local.class}
			{...rest}>
			<For each={ctx.sources}>
				{(source, i) => (
					<li
						id={ctx.getFootnoteId(source.id)}
						data-citation-source=''
						data-index={i() + 1}>
						{local.children ? local.children({ source, index: i() + 1 }) : defaultFootnote(source)}
					</li>
				)}
			</For>
		</ol>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Citation = {
	Root,
	Ref,
	List,
};

// Named exports expose the sub-components to Storybook's docgen (public API stays `Citation.*`).
export { Root, Ref, List };
