// packages/solid/src/components/list/List.tsx
import { splitProps } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import type { ListProps } from './List.types';

function List(props: ListProps) {
	const [local, rest] = splitProps(props, ['isOrdered', 'type', 'size', 'class', 'children']);
	const tag = () => (local.isOrdered ? 'ol' : 'ul');

	return (
		<Dynamic
			component={tag()}
			class={local.class}
			data-type={local.type}
			data-size={local.size}
			data-striped={local.type === 'striped' ? '' : undefined}
			data-divider={local.type === 'divider' ? '' : undefined}
			{...rest}>
			{local.children}
		</Dynamic>
	);
}

export { List };

// src/components/list/List.tsx
import React from 'react'
import type { ListProps } from './List.types'

const List = React.forwardRef<HTMLUListElement | HTMLOListElement, ListProps>(
	({ isOrdered = false, type, size, className, children, ...rest }, ref) => {
		const Tag = isOrdered ? 'ol' : 'ul'

		return (
			<Tag
				ref={ref as React.Ref<HTMLUListElement> & React.Ref<HTMLOListElement>}
				className={className}
				data-type={type}
				data-size={size}
				data-striped={type === 'striped' ? '' : undefined}
				data-divider={type === 'divider' ? '' : undefined}
				{...rest}
			>
				{children}
			</Tag>
		)
	},
)

List.displayName = 'List'

export { List }
