// packages/solid/src/components/drawer/Drawer.tsx
'use client';

import { createContext, Show, splitProps, useContext, type JSX } from 'solid-js';
import { Portal as SolidPortal } from 'solid-js/web';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createFocusTrap } from '@/primitives/create-focus-trap';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { createKeyboard } from '@/primitives/create-keyboard';
import { createMergedRefs } from '@/primitives/create-merged-refs';
import { createScrollLock } from '@/primitives/create-scroll-lock';
import { mergeProps } from '@/utils/merge-props';
import type {
	DrawerCloseProps,
	DrawerContentProps,
	DrawerContextValue,
	DrawerHeaderProps,
	DrawerOverlayProps,
	DrawerPortalProps,
	DrawerRootProps,
} from './Drawer.types';

const DrawerContext = createContext<DrawerContextValue | null>(null);

function useDrawerContext() {
	const context = useContext(DrawerContext);
	if (!context) {
		throw new Error('Drawer compound components must be used within Drawer.Root');
	}
	return context;
}

function Root(props: DrawerRootProps) {
	const [open, setOpen] = createControllableState<boolean>({
		get value() {
			return props.open;
		},
		defaultValue: props.defaultOpen ?? false,
		get onChange() {
			return props.onOpenChange;
		},
	});

	createKeyboard({
		Escape: () => {
			if (open()) setOpen(false);
		},
	});

	createScrollLock(() => open());

	const ctxValue: DrawerContextValue = {
		get open() {
			return open();
		},
		onOpenChange: (value: boolean) => setOpen(value),
	};

	return <DrawerContext.Provider value={ctxValue}>{props.children}</DrawerContext.Provider>;
}

function Portal(props: DrawerPortalProps) {
	const ctx = useDrawerContext();

	return (
		<Show when={ctx.open}>
			<SolidPortal mount={props.container}>{props.children}</SolidPortal>
		</Show>
	);
}

function Overlay(props: DrawerOverlayProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useDrawerContext();

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Content(props: DrawerContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick', 'ref']);
	const ctx = useDrawerContext();
	let contentEl: HTMLDivElement | undefined;
	const mergedRef = createMergedRefs<HTMLDivElement>(
		(el) => (contentEl = el),
		(el) => (local.ref as ((el: HTMLDivElement) => void) | undefined)?.(el),
	);

	createFocusTrap(() => contentEl, {
		get active() {
			return ctx.open;
		},
	});

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		e.stopPropagation();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			ref={mergedRef}
			role='dialog'
			aria-modal='true'
			tabIndex={-1}
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Header(props: DrawerHeaderProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	return (
		<div
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

function Close(props: DrawerCloseProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useDrawerContext();
	const state = createInteractiveState();
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			class={local.class}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

export const Drawer = {
	Root,
	Portal,
	Overlay,
	Content,
	Header,
	Close,
};

export { Root, Portal, Overlay, Content, Header, Close };

// packages/react/src/components/drawer/Drawer.tsx
import React, { createContext, useContext, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useFocusTrap } from '@/hooks/use-focus-trap';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { useKeyboard } from '@/hooks/use-keyboard';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import { useScrollLock } from '@/hooks/use-scroll-lock';
import { mergeProps } from '@/utils/merge-props';
import type {
	DrawerCloseProps,
	DrawerContentProps,
	DrawerContextValue,
	DrawerHeaderProps,
	DrawerOverlayProps,
	DrawerPortalProps,
	DrawerRootProps,
} from './Drawer.types';

const DrawerContext = createContext<DrawerContextValue | null>(null);

function useDrawerContext() {
	const context = useContext(DrawerContext);
	if (!context) {
		throw new globalThis.Error('Drawer compound components must be used within Drawer.Root');
	}
	return context;
}

const Root: React.FC<DrawerRootProps> = ({ open: controlledOpen, defaultOpen = false, onOpenChange, children }) => {
	const [open, setOpen] = useControllableState({
		value: controlledOpen,
		defaultValue: defaultOpen,
		onChange: onOpenChange,
	});

	useKeyboard({
		Escape: () => {
			if (open) setOpen(false);
		},
	});

	useScrollLock(open);

	return (
		<DrawerContext.Provider value={{ open, onOpenChange: setOpen as (value: boolean) => void }}>
			{children}
		</DrawerContext.Provider>
	);
};

Root.displayName = 'Drawer.Root';

const Portal: React.FC<DrawerPortalProps> = ({ children, container }) => {
	const { open } = useDrawerContext();

	if (!open) return null;

	return createPortal(children, container || document.body);
};

Portal.displayName = 'Drawer.Portal';

const Overlay = React.forwardRef<HTMLDivElement, DrawerOverlayProps>(({ children, className, ...rest }, ref) => {
	const { open, onOpenChange } = useDrawerContext();

	return (
		<div
			ref={ref}
			className={className}
			data-state={open ? 'open' : 'closed'}
			onClick={() => onOpenChange(false)}
			{...rest}>
			{children}
		</div>
	);
});

Overlay.displayName = 'Drawer.Overlay';

const Content = React.forwardRef<HTMLDivElement, DrawerContentProps>(({ children, className, ...rest }, ref) => {
	const { open } = useDrawerContext();
	const internalRef = useRef<HTMLDivElement | null>(null);
	const mergedRef = useMergedRefs<HTMLDivElement>(internalRef, ref);

	useFocusTrap(internalRef, { active: open });

	return (
		<div
			ref={mergedRef}
			role='dialog'
			aria-modal='true'
			tabIndex={-1}
			className={className}
			data-state={open ? 'open' : 'closed'}
			onClick={(e) => e.stopPropagation()}
			{...rest}>
			{children}
		</div>
	);
});

Content.displayName = 'Drawer.Content';

const Header = React.forwardRef<HTMLDivElement, DrawerHeaderProps>(({ children, className, ...rest }, ref) => {
	return (
		<div
			ref={ref}
			className={className}
			{...rest}>
			{children}
		</div>
	);
});

Header.displayName = 'Drawer.Header';

const Close = React.forwardRef<HTMLButtonElement, DrawerCloseProps>(({ children, className, ...rest }, ref) => {
	const { onOpenChange } = useDrawerContext();
	const { handlers, dataAttributes } = useInteractiveState();

	const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

	return (
		<button
			ref={ref}
			type='button'
			className={className}
			{...dataAttributes}
			{...merged}
			onClick={(e) => {
				onOpenChange(false);
				(rest.onClick as ((e: React.MouseEvent<HTMLButtonElement>) => void) | undefined)?.(e);
			}}>
			{children}
		</button>
	);
});

Close.displayName = 'Drawer.Close';

export const Drawer = {
	Root,
	Portal,
	Overlay,
	Content,
	Header,
	Close,
};
