// packages/vue/src/components/skeleton/Skeleton.vue
<script setup lang="ts">
defineOptions({ name: 'Skeleton' })

const props = withDefaults(
	defineProps<{
		loading?: boolean
		ariaLabel?: string
	}>(),
	{
		loading: true,
		ariaLabel: 'Loading',
	},
)
</script>

<template>
	<slot v-if="!loading" />
	<div
		v-else
		role="status"
		aria-busy="true"
		aria-live="polite"
		:aria-label="props.ariaLabel"
		data-loading="" />
</template>

// packages/react/src/components/skeleton/Skeleton.tsx
import React from 'react';
import type { SkeletonProps } from './Skeleton.types';

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
	({ loading = true, className, children, 'aria-label': ariaLabel = 'Loading', ...rest }, ref) => {
		if (!loading) return <>{children}</>;

		return (
			<div
				ref={ref}
				role='status'
				aria-busy='true'
				aria-live='polite'
				aria-label={ariaLabel}
				className={className}
				data-loading=''
				{...rest}
			/>
		);
	},
);
Skeleton.displayName = 'Skeleton';

export { Skeleton };
