// packages/solid/src/components/pagination/Pagination.tsx
import { createContext, createMemo, createSignal, For, splitProps, useContext, type JSX } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	PaginationButtonProps,
	PaginationContextValue,
	PaginationEllipsisProps,
	PaginationItemProps,
	PaginationItemValue,
	PaginationListProps,
	PaginationRootProps,
} from './Pagination.types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function range(start: number, end: number): number[] {
	const out: number[] = [];
	for (let i = start; i <= end; i++) out.push(i);
	return out;
}

/**
 * Build the list of items: a mix of page numbers and 'ellipsis' markers.
 * Mirrors the MUI / shadcn behavior.
 */
export function getPaginationItems(
	totalPages: number,
	page: number,
	siblingCount = 1,
	boundaryCount = 1,
): PaginationItemValue[] {
	if (totalPages <= 1) return totalPages === 1 ? [1] : [];

	const startPages = range(1, Math.min(boundaryCount, totalPages));
	const endPages = range(Math.max(totalPages - boundaryCount + 1, boundaryCount + 1), totalPages);

	const siblingsStart = Math.max(
		Math.min(page - siblingCount, totalPages - boundaryCount - siblingCount * 2 - 1),
		boundaryCount + 2,
	);
	const siblingsEnd = Math.min(
		Math.max(page + siblingCount, boundaryCount + siblingCount * 2 + 2),
		endPages.length > 0 ? endPages[0] - 2 : totalPages - 1,
	);

	const items: PaginationItemValue[] = [
		...startPages,
		...(siblingsStart > boundaryCount + 2
			? (['ellipsis'] as const)
			: boundaryCount + 1 < totalPages - boundaryCount
				? [boundaryCount + 1]
				: []),
		...range(siblingsStart, siblingsEnd),
		...(siblingsEnd < totalPages - boundaryCount - 1
			? (['ellipsis'] as const)
			: totalPages - boundaryCount > boundaryCount
				? [totalPages - boundaryCount]
				: []),
		...endPages,
	];

	return items;
}

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PaginationContext = createContext<PaginationContextValue | null>(null);

function usePaginationContext() {
	const ctx = useContext(PaginationContext);
	if (!ctx) throw new Error('Pagination compound components must be used within Pagination.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: PaginationRootProps) {
	const [local, rest] = splitProps(props, [
		'totalPages',
		'page',
		'defaultPage',
		'onChange',
		'siblingCount',
		'boundaryCount',
		'children',
		'class',
		'aria-label',
	]);

	const [uncontrolled, setUncontrolled] = createSignal<number>(local.defaultPage ?? 1);
	const isControlled = () => local.page !== undefined;
	const page = () => (isControlled() ? (local.page as number) : uncontrolled());
	const totalPages = () => local.totalPages;
	const ariaLabel = () => local['aria-label'] ?? 'Pagination';

	const goTo = (next: number) => {
		const clamped = Math.min(Math.max(next, 1), Math.max(totalPages(), 1));
		if (clamped === page()) return;
		if (!isControlled()) setUncontrolled(clamped);
		local.onChange?.(clamped);
	};

	const prev = () => goTo(page() - 1);
	const next = () => goTo(page() + 1);

	const items = createMemo(() =>
		getPaginationItems(totalPages(), page(), local.siblingCount ?? 1, local.boundaryCount ?? 1),
	);

	const ctxValue: PaginationContextValue = {
		get page() {
			return page();
		},
		get totalPages() {
			return totalPages();
		},
		get items() {
			return items();
		},
		get canPrev() {
			return page() > 1;
		},
		get canNext() {
			return page() < totalPages();
		},
		goTo,
		prev,
		next,
	};

	return (
		<PaginationContext.Provider value={ctxValue}>
			<nav
				aria-label={ariaLabel()}
				class={local.class}
				{...rest}>
				{local.children}
			</nav>
		</PaginationContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Items render-prop — emits the computed item sequence
// ---------------------------------------------------------------------------

interface PaginationItemsProps {
	children: (item: PaginationItemValue, index: number) => JSX.Element;
}

function Items(props: PaginationItemsProps) {
	const ctx = usePaginationContext();
	return (
		<For each={ctx.items}>
			{(item, i) => {
				// eslint-disable-next-line solid/reactivity
				return props.children(item, i());
			}}
		</For>
	);
}

// ---------------------------------------------------------------------------
// Subcomponents
// ---------------------------------------------------------------------------

function List(props: PaginationListProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	return (
		<ul
			class={local.class}
			{...rest}>
			{local.children}
		</ul>
	);
}

function Item(props: PaginationItemProps) {
	const [local, rest] = splitProps(props, ['page', 'disabled', 'children', 'class', 'onClick']);
	const ctx = usePaginationContext();
	const state = createInteractiveState({
		get disabled() {
			return !!local.disabled;
		},
	});

	const active = () => ctx.page === local.page;

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.goTo(local.page);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			// onClick on li bubbles from the button. We treat it as a "click on the page button".
			(userOnClick as (event: MouseEvent) => void)(e);
		}
	};

	return (
		<li
			class={local.class}
			{...rest}>
			<button
				type='button'
				disabled={local.disabled}
				aria-current={active() ? 'page' : undefined}
				aria-label={`Page ${local.page}`}
				data-active={active() ? '' : undefined}
				{...state.dataAttributes}
				onMouseEnter={state.handlers.onMouseEnter}
				onMouseLeave={state.handlers.onMouseLeave}
				onPointerDown={state.handlers.onPointerDown}
				onPointerUp={state.handlers.onPointerUp}
				onFocus={state.handlers.onFocus}
				onBlur={state.handlers.onBlur}
				onKeyDown={state.handlers.onKeyDown}
				onKeyUp={state.handlers.onKeyUp}
				onClick={handleClick}>
				{local.children ?? local.page}
			</button>
		</li>
	);
}

function Ellipsis(props: PaginationEllipsisProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	return (
		<li
			role='presentation'
			aria-hidden='true'
			class={local.class}
			{...rest}>
			{local.children ?? '…'}
		</li>
	);
}

function makeNavButton(direction: 'prev' | 'next', label: string) {
	return function NavButton(props: PaginationButtonProps) {
		const [local, rest] = splitProps(props, ['disabled', 'children', 'class', 'onClick']);
		const ctx = usePaginationContext();
		const isDisabled = () =>
			!!local.disabled || (direction === 'prev' ? !ctx.canPrev : !ctx.canNext);
		const state = createInteractiveState({
			get disabled() {
				return isDisabled();
			},
		});
		const merged = mergeProps(rest, state.handlers);

		const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
			if (direction === 'prev') ctx.prev();
			else ctx.next();
			const userOnClick = local.onClick;
			if (typeof userOnClick === 'function') {
				(userOnClick as (event: typeof e) => void)(e);
			}
		};

		return (
			<button
				type='button'
				disabled={isDisabled()}
				aria-label={label}
				class={local.class}
				{...state.dataAttributes}
				{...merged}
				onClick={handleClick}>
				{local.children}
			</button>
		);
	};
}

const Previous = makeNavButton('prev', 'Previous page');
const Next = makeNavButton('next', 'Next page');

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Pagination = { Root, List, Items, Item, Previous, Next, Ellipsis };

// packages/react/src/components/pagination/Pagination.tsx
import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	PaginationButtonProps,
	PaginationContextValue,
	PaginationEllipsisProps,
	PaginationItemProps,
	PaginationItemValue,
	PaginationListProps,
	PaginationRootProps,
} from './Pagination.types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function range(start: number, end: number): number[] {
	const out: number[] = [];
	for (let i = start; i <= end; i++) out.push(i);
	return out;
}

/**
 * Build the list of items: a mix of page numbers and 'ellipsis' markers.
 * Mirrors the MUI / shadcn behavior.
 */
export function getPaginationItems(
	totalPages: number,
	page: number,
	siblingCount = 1,
	boundaryCount = 1,
): PaginationItemValue[] {
	if (totalPages <= 1) return totalPages === 1 ? [1] : [];

	const startPages = range(1, Math.min(boundaryCount, totalPages));
	const endPages = range(Math.max(totalPages - boundaryCount + 1, boundaryCount + 1), totalPages);

	const siblingsStart = Math.max(
		Math.min(page - siblingCount, totalPages - boundaryCount - siblingCount * 2 - 1),
		boundaryCount + 2,
	);
	const siblingsEnd = Math.min(
		Math.max(page + siblingCount, boundaryCount + siblingCount * 2 + 2),
		endPages.length > 0 ? endPages[0] - 2 : totalPages - 1,
	);

	const items: PaginationItemValue[] = [
		...startPages,
		...(siblingsStart > boundaryCount + 2
			? (['ellipsis'] as const)
			: boundaryCount + 1 < totalPages - boundaryCount
				? [boundaryCount + 1]
				: []),
		...range(siblingsStart, siblingsEnd),
		...(siblingsEnd < totalPages - boundaryCount - 1
			? (['ellipsis'] as const)
			: totalPages - boundaryCount > boundaryCount
				? [totalPages - boundaryCount]
				: []),
		...endPages,
	];

	return items;
}

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PaginationContext = createContext<PaginationContextValue | null>(null);

function usePaginationContext() {
	const ctx = useContext(PaginationContext);
	if (!ctx) throw new globalThis.Error('Pagination compound components must be used within Pagination.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLElement, PaginationRootProps>(
	(
		{
			totalPages,
			page: controlledPage,
			defaultPage = 1,
			onChange,
			siblingCount = 1,
			boundaryCount = 1,
			children,
			className,
			'aria-label': ariaLabel = 'Pagination',
			...rest
		},
		ref,
	) => {
		const [uncontrolled, setUncontrolled] = useState<number>(defaultPage);
		const isControlled = controlledPage !== undefined;
		const page = isControlled ? (controlledPage as number) : uncontrolled;

		const goTo = useCallback(
			(next: number) => {
				const clamped = Math.min(Math.max(next, 1), Math.max(totalPages, 1));
				if (clamped === page) return;
				if (!isControlled) setUncontrolled(clamped);
				onChange?.(clamped);
			},
			[isControlled, onChange, page, totalPages],
		);

		const prev = useCallback(() => goTo(page - 1), [goTo, page]);
		const next = useCallback(() => goTo(page + 1), [goTo, page]);

		const items = useMemo(
			() => getPaginationItems(totalPages, page, siblingCount, boundaryCount),
			[totalPages, page, siblingCount, boundaryCount],
		);

		const ctx = useMemo<PaginationContextValue>(
			() => ({
				page,
				totalPages,
				items,
				canPrev: page > 1,
				canNext: page < totalPages,
				goTo,
				prev,
				next,
			}),
			[page, totalPages, items, goTo, prev, next],
		);

		return (
			<PaginationContext.Provider value={ctx}>
				<nav
					ref={ref}
					aria-label={ariaLabel}
					className={className}
					{...rest}>
					{children}
				</nav>
			</PaginationContext.Provider>
		);
	},
);
Root.displayName = 'Pagination.Root';

// ---------------------------------------------------------------------------
// Items render-prop — emits the computed item sequence
// ---------------------------------------------------------------------------

interface PaginationItemsProps {
	children: (item: PaginationItemValue, index: number) => React.ReactNode;
}

const Items: React.FC<PaginationItemsProps> = ({ children }) => {
	const ctx = usePaginationContext();
	return <>{ctx.items.map((item, i) => children(item, i))}</>;
};
Items.displayName = 'Pagination.Items';

// ---------------------------------------------------------------------------
// Subcomponents
// ---------------------------------------------------------------------------

const List = React.forwardRef<HTMLUListElement, PaginationListProps>(({ children, className, ...rest }, ref) => (
	<ul
		ref={ref}
		className={className}
		{...rest}>
		{children}
	</ul>
));
List.displayName = 'Pagination.List';

const Item = React.forwardRef<HTMLLIElement, PaginationItemProps>(
	({ page, disabled = false, children, className, onClick, ...rest }, ref) => {
		const ctx = usePaginationContext();
		const { handlers, dataAttributes } = useInteractiveState({ disabled });
		const merged = mergeProps({ onClick } as Record<string, unknown>, handlers as Record<string, unknown>);
		const active = ctx.page === page;

		return (
			<li ref={ref} className={className} {...rest}>
				<button
					type='button'
					disabled={disabled}
					aria-current={active ? 'page' : undefined}
					aria-label={`Page ${page}`}
					data-active={active ? '' : undefined}
					{...dataAttributes}
					{...(merged as React.ButtonHTMLAttributes<HTMLButtonElement>)}
					onClick={(e) => {
						ctx.goTo(page);
						(merged as { onClick?: React.MouseEventHandler<HTMLButtonElement> }).onClick?.(e);
					}}>
					{children ?? page}
				</button>
			</li>
		);
	},
);
Item.displayName = 'Pagination.Item';

const Ellipsis = React.forwardRef<HTMLLIElement, PaginationEllipsisProps>(
	({ children = '…', className, ...rest }, ref) => (
		<li
			ref={ref}
			role='presentation'
			aria-hidden='true'
			className={className}
			{...rest}>
			{children}
		</li>
	),
);
Ellipsis.displayName = 'Pagination.Ellipsis';

function makeNavButton(direction: 'prev' | 'next', label: string, displayName: string) {
	const Component = React.forwardRef<HTMLButtonElement, PaginationButtonProps>(
		({ disabled = false, children, className, onClick, ...rest }, ref) => {
			const ctx = usePaginationContext();
			const isDisabled = disabled || (direction === 'prev' ? !ctx.canPrev : !ctx.canNext);
			const { handlers, dataAttributes } = useInteractiveState({ disabled: isDisabled });
			const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

			return (
				<button
					ref={ref}
					type='button'
					disabled={isDisabled}
					aria-label={label}
					className={className}
					{...dataAttributes}
					{...merged}
					onClick={(e) => {
						if (direction === 'prev') ctx.prev();
						else ctx.next();
						onClick?.(e);
					}}>
					{children}
				</button>
			);
		},
	);
	Component.displayName = displayName;
	return Component;
}

const Previous = makeNavButton('prev', 'Previous page', 'Pagination.Previous');
const Next = makeNavButton('next', 'Next page', 'Pagination.Next');

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Pagination = { Root, List, Items, Item, Previous, Next, Ellipsis };
