// packages/react/src/components/number-input/NumberInput.tsx
import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	NumberInputContextValue,
	NumberInputDecrementProps,
	NumberInputFieldProps,
	NumberInputIncrementProps,
	NumberInputRootProps,
} from './NumberInput.types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function clamp(v: number, min: number, max: number) {
	return Math.min(Math.max(v, min), max);
}

function decimalsOf(step: number) {
	const s = step.toString();
	const dot = s.indexOf('.');
	return dot === -1 ? 0 : s.length - dot - 1;
}

function round(value: number, decimals: number) {
	const factor = Math.pow(10, decimals);
	return Math.round(value * factor) / factor;
}

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const NumberInputContext = createContext<NumberInputContextValue | null>(null);

function useNumberInputContext() {
	const ctx = useContext(NumberInputContext);
	if (!ctx) throw new globalThis.Error('NumberInput compound components must be used within NumberInput.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, NumberInputRootProps>(
	(
		{
			value: controlledValue,
			defaultValue = null,
			onChange,
			min = Number.NEGATIVE_INFINITY,
			max = Number.POSITIVE_INFINITY,
			step = 1,
			precision: precisionProp,
			disabled = false,
			readOnly = false,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [uncontrolled, setUncontrolled] = useState<number | null>(defaultValue);
		const isControlled = controlledValue !== undefined;
		const value = isControlled ? controlledValue : uncontrolled;
		const precision = precisionProp ?? decimalsOf(step);

		const setValue = useCallback(
			(next: number | null) => {
				const normalized = next === null || Number.isNaN(next) ? null : round(clamp(next, min, max), precision);
				if (!isControlled) setUncontrolled(normalized);
				onChange?.(normalized);
			},
			[isControlled, onChange, min, max, precision],
		);

		const stepBy = useCallback(
			(delta: number) => {
				if (disabled || readOnly) return;
				const base = value ?? 0;
				setValue(base + delta);
			},
			[value, setValue, disabled, readOnly],
		);

		const increment = useCallback(() => stepBy(step), [stepBy, step]);
		const decrement = useCallback(() => stepBy(-step), [stepBy, step]);

		const ctx = useMemo<NumberInputContextValue>(
			() => ({ value, min, max, step, precision, disabled, readOnly, setValue, increment, decrement, stepBy }),
			[value, min, max, step, precision, disabled, readOnly, setValue, increment, decrement, stepBy],
		);

		return (
			<NumberInputContext.Provider value={ctx}>
				<div
					ref={ref}
					className={className}
					data-disabled={disabled ? '' : undefined}
					data-readonly={readOnly ? '' : undefined}
					{...rest}>
					{children}
				</div>
			</NumberInputContext.Provider>
		);
	},
);
Root.displayName = 'NumberInput.Root';

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

const Field = React.forwardRef<HTMLInputElement, NumberInputFieldProps>(
	({ className, onKeyDown, onBlur, ...rest }, ref) => {
		const ctx = useNumberInputContext();
		const [text, setText] = useState<string>(() => (ctx.value === null ? '' : String(ctx.value)));

		// Sync visible text whenever the committed value changes. (Typing alone
		// doesn't change ctx.value — the field commits on blur — so this won't
		// stomp on in-progress user input.)
		React.useEffect(() => {
			setText(ctx.value === null ? '' : String(ctx.value));
		}, [ctx.value]);

		const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
			onKeyDown?.(e);
			if (e.defaultPrevented || ctx.disabled || ctx.readOnly) return;
			if (e.key === 'ArrowUp') {
				e.preventDefault();
				ctx.stepBy(ctx.step);
			} else if (e.key === 'ArrowDown') {
				e.preventDefault();
				ctx.stepBy(-ctx.step);
			} else if (e.key === 'PageUp') {
				e.preventDefault();
				ctx.stepBy(ctx.step * 10);
			} else if (e.key === 'PageDown') {
				e.preventDefault();
				ctx.stepBy(-ctx.step * 10);
			} else if (e.key === 'Home' && Number.isFinite(ctx.min)) {
				e.preventDefault();
				ctx.setValue(ctx.min);
			} else if (e.key === 'End' && Number.isFinite(ctx.max)) {
				e.preventDefault();
				ctx.setValue(ctx.max);
			}
		};

		const commitText = (raw: string) => {
			const trimmed = raw.trim();
			if (trimmed === '' || trimmed === '-' || trimmed === '.') {
				ctx.setValue(null);
				setText('');
				return;
			}
			const parsed = Number(trimmed);
			if (Number.isNaN(parsed)) {
				// Revert to last good value
				setText(ctx.value === null ? '' : String(ctx.value));
				return;
			}
			ctx.setValue(parsed);
		};

		return (
			<input
				ref={ref}
				type='text'
				inputMode='decimal'
				role='spinbutton'
				aria-valuenow={ctx.value ?? undefined}
				aria-valuemin={Number.isFinite(ctx.min) ? ctx.min : undefined}
				aria-valuemax={Number.isFinite(ctx.max) ? ctx.max : undefined}
				disabled={ctx.disabled}
				readOnly={ctx.readOnly}
				value={text}
				className={className}
				{...rest}
				onChange={(e) => setText(e.currentTarget.value)}
				onBlur={(e) => {
					commitText(text);
					onBlur?.(e);
				}}
				onKeyDown={handleKeyDown}
			/>
		);
	},
);
Field.displayName = 'NumberInput.Field';

// ---------------------------------------------------------------------------
// Increment / Decrement
// ---------------------------------------------------------------------------

function makeStepButton(direction: 1 | -1, displayName: string) {
	const Component = React.forwardRef<HTMLButtonElement, NumberInputIncrementProps>(
		({ className, children, onClick, ...rest }, ref) => {
			const ctx = useNumberInputContext();
			const { handlers, dataAttributes } = useInteractiveState({ disabled: ctx.disabled || ctx.readOnly });
			const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

			const atBoundary =
				ctx.value !== null &&
				((direction === 1 && ctx.value >= ctx.max) || (direction === -1 && ctx.value <= ctx.min));

			const isDisabled = ctx.disabled || ctx.readOnly || atBoundary;

			return (
				<button
					ref={ref}
					type='button'
					tabIndex={-1}
					disabled={isDisabled}
					aria-label={direction === 1 ? 'Increment' : 'Decrement'}
					className={className}
					{...dataAttributes}
					{...merged}
					onClick={(e) => {
						if (direction === 1) ctx.increment();
						else ctx.decrement();
						onClick?.(e);
					}}>
					{children}
				</button>
			);
		},
	);
	Component.displayName = displayName;
	return Component;
}

const Increment = makeStepButton(1, 'NumberInput.Increment') as React.ForwardRefExoticComponent<
	NumberInputIncrementProps & React.RefAttributes<HTMLButtonElement>
>;

const Decrement = makeStepButton(-1, 'NumberInput.Decrement') as React.ForwardRefExoticComponent<
	NumberInputDecrementProps & React.RefAttributes<HTMLButtonElement>
>;

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const NumberInput = { Root, Field, Increment, Decrement };

// packages/solid/src/components/number-input/NumberInput.tsx
import { createContext, createEffect, createSignal, splitProps, useContext, type JSX } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	NumberInputContextValue,
	NumberInputDecrementProps,
	NumberInputFieldProps,
	NumberInputIncrementProps,
	NumberInputRootProps,
} from './NumberInput.types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function clamp(v: number, min: number, max: number) {
	return Math.min(Math.max(v, min), max);
}

function decimalsOf(step: number) {
	const s = step.toString();
	const dot = s.indexOf('.');
	return dot === -1 ? 0 : s.length - dot - 1;
}

function round(value: number, decimals: number) {
	const factor = Math.pow(10, decimals);
	return Math.round(value * factor) / factor;
}

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const NumberInputContext = createContext<NumberInputContextValue | null>(null);

function useNumberInputContext() {
	const ctx = useContext(NumberInputContext);
	if (!ctx) throw new Error('NumberInput compound components must be used within NumberInput.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: NumberInputRootProps) {
	const [local, rest] = splitProps(props, [
		'value',
		'defaultValue',
		'onChange',
		'min',
		'max',
		'step',
		'precision',
		'disabled',
		'readOnly',
		'children',
		'class',
	]);

	const [uncontrolled, setUncontrolled] = createSignal<number | null>(local.defaultValue ?? null);
	const isControlled = () => local.value !== undefined;
	const value = () => (isControlled() ? (local.value ?? null) : uncontrolled());

	const min = () => local.min ?? Number.NEGATIVE_INFINITY;
	const max = () => local.max ?? Number.POSITIVE_INFINITY;
	const step = () => local.step ?? 1;
	const precision = () => local.precision ?? decimalsOf(step());

	const setValue = (next: number | null) => {
		const normalized = next === null || Number.isNaN(next) ? null : round(clamp(next, min(), max()), precision());
		if (!isControlled()) setUncontrolled(normalized);
		local.onChange?.(normalized);
	};

	const stepBy = (delta: number) => {
		if (local.disabled || local.readOnly) return;
		const base = value() ?? 0;
		setValue(base + delta);
	};

	const increment = () => stepBy(step());
	const decrement = () => stepBy(-step());

	const ctxValue: NumberInputContextValue = {
		get value() {
			return value();
		},
		get min() {
			return min();
		},
		get max() {
			return max();
		},
		get step() {
			return step();
		},
		get precision() {
			return precision();
		},
		get disabled() {
			return !!local.disabled;
		},
		get readOnly() {
			return !!local.readOnly;
		},
		setValue,
		increment,
		decrement,
		stepBy,
	};

	return (
		<NumberInputContext.Provider value={ctxValue}>
			<div
				class={local.class}
				data-disabled={local.disabled ? '' : undefined}
				data-readonly={local.readOnly ? '' : undefined}
				{...rest}>
				{local.children}
			</div>
		</NumberInputContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

function Field(props: NumberInputFieldProps) {
	const [local, rest] = splitProps(props, ['class', 'onKeyDown', 'onBlur']);
	const ctx = useNumberInputContext();
	const [text, setText] = createSignal<string>(ctx.value === null ? '' : String(ctx.value));

	// Sync visible text whenever the committed value changes externally.
	createEffect(() => {
		setText(ctx.value === null ? '' : String(ctx.value));
	});

	const handleKeyDown: JSX.EventHandler<HTMLInputElement, KeyboardEvent> = (e) => {
		const userOnKeyDown = local.onKeyDown;
		if (typeof userOnKeyDown === 'function') {
			(userOnKeyDown as (event: typeof e) => void)(e);
		}
		if (e.defaultPrevented || ctx.disabled || ctx.readOnly) return;
		if (e.key === 'ArrowUp') {
			e.preventDefault();
			ctx.stepBy(ctx.step);
		} else if (e.key === 'ArrowDown') {
			e.preventDefault();
			ctx.stepBy(-ctx.step);
		} else if (e.key === 'PageUp') {
			e.preventDefault();
			ctx.stepBy(ctx.step * 10);
		} else if (e.key === 'PageDown') {
			e.preventDefault();
			ctx.stepBy(-ctx.step * 10);
		} else if (e.key === 'Home' && Number.isFinite(ctx.min)) {
			e.preventDefault();
			ctx.setValue(ctx.min);
		} else if (e.key === 'End' && Number.isFinite(ctx.max)) {
			e.preventDefault();
			ctx.setValue(ctx.max);
		}
	};

	const commitText = (raw: string) => {
		const trimmed = raw.trim();
		if (trimmed === '' || trimmed === '-' || trimmed === '.') {
			ctx.setValue(null);
			setText('');
			return;
		}
		const parsed = Number(trimmed);
		if (Number.isNaN(parsed)) {
			// Revert to last good value
			setText(ctx.value === null ? '' : String(ctx.value));
			return;
		}
		ctx.setValue(parsed);
	};

	const handleBlur: JSX.EventHandler<HTMLInputElement, FocusEvent> = (e) => {
		commitText(text());
		const userOnBlur = local.onBlur;
		if (typeof userOnBlur === 'function') {
			(userOnBlur as (event: typeof e) => void)(e);
		}
	};

	return (
		<input
			type='text'
			inputMode='decimal'
			role='spinbutton'
			aria-valuenow={ctx.value ?? undefined}
			aria-valuemin={Number.isFinite(ctx.min) ? ctx.min : undefined}
			aria-valuemax={Number.isFinite(ctx.max) ? ctx.max : undefined}
			disabled={ctx.disabled}
			readOnly={ctx.readOnly}
			value={text()}
			class={local.class}
			{...rest}
			onInput={(e) => setText(e.currentTarget.value)}
			onBlur={handleBlur}
			onKeyDown={handleKeyDown}
		/>
	);
}

// ---------------------------------------------------------------------------
// Increment / Decrement
// ---------------------------------------------------------------------------

function makeStepButton(direction: 1 | -1) {
	return function StepButton(props: NumberInputIncrementProps | NumberInputDecrementProps) {
		const [local, rest] = splitProps(props, ['class', 'children', 'onClick']);
		const ctx = useNumberInputContext();
		const state = createInteractiveState({
			get disabled() {
				return ctx.disabled || ctx.readOnly;
			},
		});
		const merged = mergeProps(rest, state.handlers);

		const atBoundary = () =>
			ctx.value !== null &&
			((direction === 1 && ctx.value >= ctx.max) || (direction === -1 && ctx.value <= ctx.min));

		const isDisabled = () => ctx.disabled || ctx.readOnly || atBoundary();

		const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
			if (direction === 1) ctx.increment();
			else ctx.decrement();
			const userOnClick = local.onClick;
			if (typeof userOnClick === 'function') {
				(userOnClick as (event: typeof e) => void)(e);
			}
		};

		return (
			<button
				type='button'
				tabIndex={-1}
				disabled={isDisabled()}
				aria-label={direction === 1 ? 'Increment' : 'Decrement'}
				class={local.class}
				{...state.dataAttributes}
				{...merged}
				onClick={handleClick}>
				{local.children}
			</button>
		);
	};
}

const Increment = makeStepButton(1);
const Decrement = makeStepButton(-1);

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const NumberInput = { Root, Field, Increment, Decrement };
