// packages/solid/src/components/list/List.tsx
import { splitProps } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import type { ListProps } from './List.types';

function List(props: ListProps) {
	const [local, rest] = splitProps(props, ['isOrdered', 'type', 'size', 'class', 'children']);
	const tag = () => (local.isOrdered ? 'ol' : 'ul');

	return (
		<Dynamic
			component={tag()}
			class={local.class}
			data-type={local.type}
			data-size={local.size}
			data-striped={local.type === 'striped' ? '' : undefined}
			data-divider={local.type === 'divider' ? '' : undefined}
			{...rest}>
			{local.children}
		</Dynamic>
	);
}

export { List };

// packages/vue/src/components/list/List.vue
<script setup lang="ts">
defineOptions({ name: 'List' })

const props = withDefaults(
	defineProps<{
		isOrdered?: boolean
		type?: string
		size?: string
	}>(),
	{ isOrdered: false },
)
</script>

<template>
	<component
		:is="props.isOrdered ? 'ol' : 'ul'"
		:data-type="type"
		:data-size="size"
		:data-striped="type === 'striped' ? '' : undefined"
		:data-divider="type === 'divider' ? '' : undefined"
	>
		<slot />
	</component>
</template>
