// packages/react/src/components/code-block/CodeBlock.tsx
import React, { createContext, useContext, useMemo } from 'react';
import { useCopyToClipboard } from '@/hooks/use-copy-to-clipboard';
import type {
	CodeBlockCodeProps,
	CodeBlockContextValue,
	CodeBlockCopyButtonProps,
	CodeBlockLine,
	CodeBlockLinesProps,
	CodeBlockRootProps,
} from './CodeBlock.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CodeBlockContext = createContext<CodeBlockContextValue | null>(null);

function useCodeBlockContext() {
	const ctx = useContext(CodeBlockContext);
	if (!ctx) throw new globalThis.Error('CodeBlock sub-components must be used within CodeBlock.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, CodeBlockRootProps>(
	(
		{
			code,
			language,
			diff,
			highlightLines,
			startLine = 1,
			copyResetAfter = 2000,
			className,
			children,
			...rest
		},
		ref,
	) => {
		const { copy: copyText, copied } = useCopyToClipboard({ resetAfter: copyResetAfter });

		const lines = useMemo<CodeBlockLine[]>(() => {
			const highlightSet = new Set(highlightLines ?? []);
			// Split on newlines but drop a single trailing empty line so a code
			// string ending in "\n" doesn't render a phantom blank row.
			const raw = code.split('\n');
			if (raw.length > 1 && raw[raw.length - 1] === '') raw.pop();
			return raw.map((content, i) => {
				const number = startLine + i;
				return {
					number,
					content,
					diff: diff?.[number],
					highlighted: highlightSet.has(number),
				};
			});
		}, [code, diff, highlightLines, startLine]);

		const ctx = useMemo<CodeBlockContextValue>(
			() => ({
				code,
				language,
				lines,
				copied,
				copy: () => void copyText(code),
			}),
			[code, language, lines, copied, copyText],
		);

		return (
			<CodeBlockContext.Provider value={ctx}>
				<div
					ref={ref}
					className={className}
					data-language={language || undefined}
					{...rest}>
					{children}
				</div>
			</CodeBlockContext.Provider>
		);
	},
);

Root.displayName = 'CodeBlock.Root';

// ---------------------------------------------------------------------------
// Code (pre/code wrapper)
// ---------------------------------------------------------------------------

const Code = React.forwardRef<HTMLPreElement, CodeBlockCodeProps>(({ className, children, ...rest }, ref) => {
	const ctx = useCodeBlockContext();
	return (
		<pre
			ref={ref}
			className={className}
			data-language={ctx.language || undefined}
			{...rest}>
			<code data-language={ctx.language || undefined}>{children}</code>
		</pre>
	);
});

Code.displayName = 'CodeBlock.Code';

// ---------------------------------------------------------------------------
// Lines (render-prop over each line)
// ---------------------------------------------------------------------------

const Lines: React.FC<CodeBlockLinesProps> = ({ children }) => {
	const ctx = useCodeBlockContext();
	return (
		<>
			{ctx.lines.map((line) => (
				<span
					key={line.number}
					data-line=''
					data-line-number={line.number}
					data-diff={line.diff}
					data-highlighted={line.highlighted ? '' : undefined}
					style={{ display: 'block' }}>
					{children({ line })}
				</span>
			))}
		</>
	);
};

Lines.displayName = 'CodeBlock.Lines';

// ---------------------------------------------------------------------------
// CopyButton
// ---------------------------------------------------------------------------

const CopyButton = React.forwardRef<HTMLButtonElement, CodeBlockCopyButtonProps>(
	({ className, children, onClick, ...rest }, ref) => {
		const ctx = useCodeBlockContext();
		return (
			<button
				ref={ref}
				type='button'
				aria-label={ctx.copied ? 'Copied' : 'Copy code'}
				className={className}
				data-copied={ctx.copied ? '' : undefined}
				{...rest}
				onClick={(e) => {
					ctx.copy();
					onClick?.(e);
				}}>
				{typeof children === 'function' ? children({ copied: ctx.copied }) : children}
			</button>
		);
	},
);

CopyButton.displayName = 'CodeBlock.CopyButton';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const CodeBlock = {
	Root,
	Code,
	Lines,
	CopyButton,
};

// packages/solid/src/components/code-block/CodeBlock.tsx
'use client';

import { createContext, useContext, splitProps, mergeProps as solidMergeProps, For, type JSX } from 'solid-js';
import { createCopyToClipboard } from '@/primitives/create-copy-to-clipboard';
import type {
	CodeBlockCodeProps,
	CodeBlockContextValue,
	CodeBlockCopyButtonProps,
	CodeBlockLine,
	CodeBlockLinesProps,
	CodeBlockRootProps,
} from './CodeBlock.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CodeBlockContext = createContext<CodeBlockContextValue | null>(null);

function useCodeBlockContext() {
	const ctx = useContext(CodeBlockContext);
	if (!ctx) throw new Error('CodeBlock sub-components must be used within CodeBlock.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: CodeBlockRootProps) {
	const merged = solidMergeProps({ startLine: 1, copyResetAfter: 2000 }, props);
	const [local, rest] = splitProps(merged, [
		'code',
		'language',
		'diff',
		'highlightLines',
		'startLine',
		'copyResetAfter',
		'class',
		'children',
	]);

	// `resetAfter` is read once at setup (the primitive captures it), matching React.
	// eslint-disable-next-line solid/reactivity
	const { copy: copyText, copied } = createCopyToClipboard({ resetAfter: local.copyResetAfter });

	const lines = (): CodeBlockLine[] => {
		const highlightSet = new Set(local.highlightLines ?? []);
		// Split on newlines but drop a single trailing empty line so a code
		// string ending in "\n" doesn't render a phantom blank row.
		const raw = local.code.split('\n');
		if (raw.length > 1 && raw[raw.length - 1] === '') raw.pop();
		return raw.map((content, i) => {
			const number = local.startLine + i;
			return {
				number,
				content,
				diff: local.diff?.[number],
				highlighted: highlightSet.has(number),
			};
		});
	};

	const ctx: CodeBlockContextValue = {
		get code() {
			return local.code;
		},
		get language() {
			return local.language;
		},
		get lines() {
			return lines();
		},
		get copied() {
			return copied();
		},
		copy: () => void copyText(local.code),
	};

	return (
		<CodeBlockContext.Provider value={ctx}>
			<div
				class={local.class}
				data-language={local.language || undefined}
				{...rest}>
				{local.children}
			</div>
		</CodeBlockContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Code (pre/code wrapper)
// ---------------------------------------------------------------------------

function Code(props: CodeBlockCodeProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	const ctx = useCodeBlockContext();
	return (
		<pre
			class={local.class}
			data-language={ctx.language || undefined}
			{...rest}>
			<code data-language={ctx.language || undefined}>{local.children}</code>
		</pre>
	);
}

// ---------------------------------------------------------------------------
// Lines (render-prop over each line)
// ---------------------------------------------------------------------------

function Lines(props: CodeBlockLinesProps) {
	const ctx = useCodeBlockContext();
	return (
		<For each={ctx.lines}>
			{(line) => (
				<span
					data-line=''
					data-line-number={line.number}
					data-diff={line.diff}
					data-highlighted={line.highlighted ? '' : undefined}
					style={{ display: 'block' }}>
					{props.children({ line })}
				</span>
			)}
		</For>
	);
}

// ---------------------------------------------------------------------------
// CopyButton
// ---------------------------------------------------------------------------

function CopyButton(props: CodeBlockCopyButtonProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'onClick']);
	const ctx = useCodeBlockContext();

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.copy();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			aria-label={ctx.copied ? 'Copied' : 'Copy code'}
			class={local.class}
			data-copied={ctx.copied ? '' : undefined}
			{...rest}
			onClick={handleClick}>
			{typeof local.children === 'function' ? local.children({ copied: ctx.copied }) : local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const CodeBlock = {
	Root,
	Code,
	Lines,
	CopyButton,
};

export { Root, Code, Lines, CopyButton };
