// packages/react/src/components/input/Input.tsx
import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import { Helper } from '@/utils/helper';
import type {
	InputContextValue,
	InputErrorProps,
	InputFieldProps,
	InputLabelProps,
	InputRootProps,
} from './Input.types';

const InputContext = createContext<InputContextValue | null>(null);

function useInputContext() {
	const context = useContext(InputContext);
	if (!context) {
		throw new globalThis.Error('Input compound components must be used within Input.Root');
	}
	return context;
}

const Root = React.forwardRef<HTMLDivElement, InputRootProps>(
	(
		{
			value: controlledValue,
			defaultValue = '',
			onChange,
			onFocus,
			onBlur,
			invalidType = '',
			errorMessage = {},
			isRequired = false,
			isSuccess = false,
			id,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
		const isControlled = controlledValue !== undefined;
		const value = isControlled ? controlledValue : uncontrolledValue;
		const [isActive, setIsActive] = useState(false);
		const inputId = useMemo(() => id || Helper.generateUUID(), [id]);

		const handleChange = useCallback(
			(newValue: string) => {
				if (!isControlled) setUncontrolledValue(newValue);
				onChange?.(newValue);
			},
			[isControlled, onChange],
		);

		const handleFocus = useCallback(() => {
			setIsActive(true);
			onFocus?.();
		}, [onFocus]);

		const handleBlur = useCallback(() => {
			setIsActive(false);
			onBlur?.();
		}, [onBlur]);

		const contextValue: InputContextValue = {
			value,
			inputId,
			isActive,
			invalidType,
			isSuccess,
			isRequired,
			errorMessage,
			handleChange,
			handleFocus,
			handleBlur,
		};

		return (
			<InputContext.Provider value={contextValue}>
				<div
					ref={ref}
					className={className}
					{...rest}>
					{children}
				</div>
			</InputContext.Provider>
		);
	},
);

Root.displayName = 'Input.Root';

const Field = React.forwardRef<HTMLInputElement, InputFieldProps>(({ className, ...rest }, ref) => {
	const ctx = useInputContext();

	return (
		<input
			ref={ref}
			id={ctx.inputId}
			value={ctx.value}
			required={ctx.isRequired}
			className={className}
			aria-required={ctx.isRequired || undefined}
			aria-invalid={ctx.invalidType ? true : undefined}
			data-invalid={ctx.invalidType ? '' : undefined}
			data-active={ctx.isActive ? '' : undefined}
			data-success={ctx.isSuccess ? '' : undefined}
			onFocus={ctx.handleFocus}
			onBlur={ctx.handleBlur}
			onChange={(e) => ctx.handleChange(e.target.value)}
			{...rest}
		/>
	);
});

Field.displayName = 'Input.Field';

const Label = React.forwardRef<HTMLLabelElement, InputLabelProps>(({ children, className, ...rest }, ref) => {
	const ctx = useInputContext();

	return (
		<label
			ref={ref}
			htmlFor={ctx.inputId}
			className={className}
			{...rest}>
			{ctx.isRequired && <span>*</span>}
			{children}
		</label>
	);
});

Label.displayName = 'Input.Label';

const Error = React.forwardRef<HTMLElement, InputErrorProps>(({ children, className, ...rest }, ref) => {
	const ctx = useInputContext();

	if (!ctx.invalidType) return null;

	const message = children ?? ctx.errorMessage[ctx.invalidType];

	return (
		<small
			ref={ref}
			role='alert'
			className={className}
			{...rest}>
			{message}
		</small>
	);
});

Error.displayName = 'Input.Error';

export const Input = {
	Root,
	Field,
	Label,
	Error,
};

// packages/solid/src/components/input/Input.tsx
import { createContext, createMemo, createSignal, Show, splitProps, useContext } from 'solid-js';
import { Helper } from '@/utils/helper';
import type {
	InputContextValue,
	InputErrorProps,
	InputFieldProps,
	InputLabelProps,
	InputRootProps,
} from './Input.types';

const InputContext = createContext<InputContextValue | null>(null);

function useInputContext() {
	const context = useContext(InputContext);
	if (!context) {
		throw new Error('Input compound components must be used within Input.Root');
	}
	return context;
}

function Root(props: InputRootProps) {
	const [local, rest] = splitProps(props, [
		'value',
		'defaultValue',
		'onChange',
		'onFocus',
		'onBlur',
		'invalidType',
		'errorMessage',
		'isRequired',
		'isSuccess',
		'id',
		'children',
		'class',
	]);

	const [uncontrolledValue, setUncontrolledValue] = createSignal(local.defaultValue ?? '');
	const [isActive, setIsActive] = createSignal(false);
	const isControlled = () => local.value !== undefined;
	const value = () => (isControlled() ? (local.value ?? '') : uncontrolledValue());

	// Memoize the generated UUID so it stays stable when `id` is unset.
	const inputId = createMemo(() => local.id || Helper.generateUUID());

	const handleChange = (newValue: string) => {
		if (!isControlled()) setUncontrolledValue(newValue);
		local.onChange?.(newValue);
	};

	const handleFocus = () => {
		setIsActive(true);
		local.onFocus?.();
	};

	const handleBlur = () => {
		setIsActive(false);
		local.onBlur?.();
	};

	const contextValue: InputContextValue = {
		get value() {
			return value();
		},
		get inputId() {
			return inputId();
		},
		get isActive() {
			return isActive();
		},
		get invalidType() {
			return local.invalidType ?? '';
		},
		get isSuccess() {
			return !!local.isSuccess;
		},
		get isRequired() {
			return !!local.isRequired;
		},
		get errorMessage() {
			return local.errorMessage ?? {};
		},
		handleChange,
		handleFocus,
		handleBlur,
	};

	return (
		<InputContext.Provider value={contextValue}>
			<div
				class={local.class}
				{...(rest as object)}>
				{local.children}
			</div>
		</InputContext.Provider>
	);
}

function Field(props: InputFieldProps) {
	const [local, rest] = splitProps(props, ['class']);
	const ctx = useInputContext();

	return (
		<input
			id={ctx.inputId}
			value={ctx.value}
			required={ctx.isRequired}
			class={local.class}
			aria-required={ctx.isRequired || undefined}
			aria-invalid={ctx.invalidType ? true : undefined}
			data-invalid={ctx.invalidType ? '' : undefined}
			data-active={ctx.isActive ? '' : undefined}
			data-success={ctx.isSuccess ? '' : undefined}
			onFocus={() => ctx.handleFocus()}
			onBlur={() => ctx.handleBlur()}
			onInput={(e) => ctx.handleChange(e.currentTarget.value)}
			{...rest}
		/>
	);
}

function Label(props: InputLabelProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useInputContext();

	return (
		<label
			for={ctx.inputId}
			class={local.class}
			{...(rest as object)}>
			<Show when={ctx.isRequired}>
				<span>*</span>
			</Show>
			{local.children}
		</label>
	);
}

function ErrorMessage(props: InputErrorProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useInputContext();

	return (
		<Show when={ctx.invalidType}>
			<small
				role='alert'
				class={local.class}
				{...(rest as object)}>
				{local.children ?? ctx.errorMessage[ctx.invalidType]}
			</small>
		</Show>
	);
}

export const Input = {
	Root,
	Field,
	Label,
	Error: ErrorMessage,
};
