// packages/react/src/components/popover/Popover.tsx
import React, { createContext, useCallback, useContext, useMemo, useRef } from 'react';
import { useClickOutside } from '@/hooks/use-click-outside';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useId } from '@/hooks/use-id';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { useKeyboard } from '@/hooks/use-keyboard';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import { mergeProps } from '@/utils/merge-props';
import type {
	PopoverCloseProps,
	PopoverContentProps,
	PopoverContextValue,
	PopoverRootProps,
	PopoverTriggerProps,
} from './Popover.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PopoverContext = createContext<PopoverContextValue | null>(null);

function usePopoverContext() {
	const context = useContext(PopoverContext);
	if (!context) {
		throw new globalThis.Error('Popover compound components must be used within Popover.Root');
	}
	return context;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, PopoverRootProps>(
	(
		{
			open: controlledOpen,
			defaultOpen = false,
			onOpenChange,
			closeOnOutsideClick = true,
			closeOnEscape = true,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [open, setOpenState] = useControllableState({
			value: controlledOpen,
			defaultValue: defaultOpen,
			onChange: onOpenChange,
		});

		const internalRef = useRef<HTMLDivElement | null>(null);
		const mergedRef = useMergedRefs<HTMLDivElement>(internalRef, ref);

		const setOpen = useCallback((value: boolean) => setOpenState(value), [setOpenState]);

		useClickOutside(internalRef, () => {
			if (open && closeOnOutsideClick) setOpen(false);
		});

		useKeyboard(
			{
				Escape: () => {
					if (open) setOpen(false);
				},
			},
			{ event: 'keyup', enabled: closeOnEscape },
		);

		const triggerId = useId('popover-trigger');
		const contentId = useId('popover-content');

		const ctx = useMemo<PopoverContextValue>(
			() => ({ open, setOpen, triggerId, contentId }),
			[open, setOpen, triggerId, contentId],
		);

		return (
			<PopoverContext.Provider value={ctx}>
				<div
					ref={mergedRef}
					className={className}
					data-state={open ? 'open' : 'closed'}
					{...rest}>
					{children}
				</div>
			</PopoverContext.Provider>
		);
	},
);
Root.displayName = 'Popover.Root';

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLButtonElement, PopoverTriggerProps>(
	({ children, className, onClick, ...rest }, ref) => {
		const { open, setOpen, triggerId, contentId } = usePopoverContext();
		const { handlers, dataAttributes } = useInteractiveState();
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		return (
			<button
				ref={ref}
				id={triggerId}
				type='button'
				className={className}
				aria-haspopup='dialog'
				aria-expanded={open}
				aria-controls={contentId}
				data-state={open ? 'open' : 'closed'}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					setOpen(!open);
					onClick?.(e);
				}}>
				{children}
			</button>
		);
	},
);
Trigger.displayName = 'Popover.Trigger';

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLDivElement, PopoverContentProps>(
	({ side = 'bottom', align = 'center', forceMount = false, className, children, ...rest }, ref) => {
		const { open, triggerId, contentId } = usePopoverContext();

		if (!open && !forceMount) return null;

		return (
			<div
				ref={ref}
				id={contentId}
				role='dialog'
				aria-labelledby={triggerId}
				className={className}
				hidden={!open && forceMount ? true : undefined}
				data-state={open ? 'open' : 'closed'}
				data-side={side}
				data-align={align}
				{...rest}>
				{children}
			</div>
		);
	},
);
Content.displayName = 'Popover.Content';

// ---------------------------------------------------------------------------
// Close
// ---------------------------------------------------------------------------

const Close = React.forwardRef<HTMLButtonElement, PopoverCloseProps>(
	({ children, className, onClick, ...rest }, ref) => {
		const { setOpen } = usePopoverContext();
		const { handlers, dataAttributes } = useInteractiveState();
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		return (
			<button
				ref={ref}
				type='button'
				className={className}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					setOpen(false);
					onClick?.(e);
				}}>
				{children}
			</button>
		);
	},
);
Close.displayName = 'Popover.Close';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Popover = { Root, Trigger, Content, Close };

// packages/solid/src/components/popover/Popover.tsx
import { createContext, splitProps, useContext, Show, type JSX } from 'solid-js';
import { createClickOutside } from '@/primitives/create-click-outside';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createId } from '@/primitives/create-id';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { createKeyboard } from '@/primitives/create-keyboard';
import { createMergedRefs } from '@/primitives/create-merged-refs';
import { mergeProps } from '@/utils/merge-props';
import type {
	PopoverCloseProps,
	PopoverContentProps,
	PopoverContextValue,
	PopoverRootProps,
	PopoverTriggerProps,
} from './Popover.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PopoverContext = createContext<PopoverContextValue | null>(null);

function usePopoverContext() {
	const ctx = useContext(PopoverContext);
	if (!ctx) {
		throw new Error('Popover compound components must be used within Popover.Root');
	}
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: PopoverRootProps) {
	const [local, rest] = splitProps(props, [
		'open',
		'defaultOpen',
		'onOpenChange',
		'closeOnOutsideClick',
		'closeOnEscape',
		'children',
		'class',
		'ref',
	]);

	const [open, setOpenState] = createControllableState<boolean>({
		get value() {
			return local.open;
		},
		defaultValue: local.defaultOpen ?? false,
		get onChange() {
			return local.onOpenChange;
		},
	});

	let internalEl: HTMLDivElement | undefined;
	const mergedRef = createMergedRefs<HTMLDivElement>(
		(el) => (internalEl = el),
		(el) => (local.ref as ((el: HTMLDivElement) => void) | undefined)?.(el),
	);

	const setOpen = (value: boolean) => setOpenState(value);

	createClickOutside(
		() => internalEl,
		() => {
			if (open() && (local.closeOnOutsideClick ?? true)) setOpen(false);
		},
	);

	createKeyboard(
		{
			Escape: () => {
				if (open()) setOpen(false);
			},
		},
		{
			event: 'keyup',
			get enabled() {
				return local.closeOnEscape ?? true;
			},
		},
	);

	const triggerId = createId('popover-trigger');
	const contentId = createId('popover-content');

	const ctx: PopoverContextValue = {
		get open() {
			return !!open();
		},
		setOpen,
		get triggerId() {
			return triggerId;
		},
		get contentId() {
			return contentId;
		},
	};

	return (
		<PopoverContext.Provider value={ctx}>
			<div
				ref={mergedRef}
				class={local.class}
				data-state={open() ? 'open' : 'closed'}
				{...rest}>
				{local.children}
			</div>
		</PopoverContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: PopoverTriggerProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = usePopoverContext();
	const state = createInteractiveState();

	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.setOpen(!ctx.open);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			id={ctx.triggerId}
			type='button'
			class={local.class}
			aria-haspopup='dialog'
			aria-expanded={ctx.open}
			aria-controls={ctx.contentId}
			data-state={ctx.open ? 'open' : 'closed'}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function Content(props: PopoverContentProps) {
	const [local, rest] = splitProps(props, ['side', 'align', 'forceMount', 'class', 'children']);
	const ctx = usePopoverContext();

	const side = () => local.side ?? 'bottom';
	const align = () => local.align ?? 'center';
	const forceMount = () => local.forceMount ?? false;

	return (
		<Show when={ctx.open || forceMount()}>
			<div
				id={ctx.contentId}
				role='dialog'
				aria-labelledby={ctx.triggerId}
				class={local.class}
				hidden={!ctx.open && forceMount() ? true : undefined}
				data-state={ctx.open ? 'open' : 'closed'}
				data-side={side()}
				data-align={align()}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Close
// ---------------------------------------------------------------------------

function Close(props: PopoverCloseProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = usePopoverContext();
	const state = createInteractiveState();

	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.setOpen(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			class={local.class}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Popover = { Root, Trigger, Content, Close };
