// packages/solid/src/context/wire-ui-context.ts
'use client';

import { createContext, useContext, type Accessor } from 'solid-js';
import { defaultMessages, type WireUIMessages } from '@/utils/i18n/messages';

/** Locale used when no `<WireUIProvider>` (or explicit prop) sets one. */
export const DEFAULT_LOCALE = 'en-US';

export interface WireUIContextValue {
	/** BCP 47 locale tag (e.g. `en-US`, `de-DE`). */
	readonly locale: string;
	/** Fully-resolved message catalog (defaults merged with overrides). */
	readonly messages: WireUIMessages;
}

export const WireUIContext = createContext<WireUIContextValue | null>(null);

// Reused when no provider is mounted so consumers never branch on `null`. The
// getters keep it shaped like a live context value (and tree-shake-friendly).
const FALLBACK: WireUIContextValue = {
	get locale() {
		return DEFAULT_LOCALE;
	},
	get messages() {
		return defaultMessages;
	},
};

/**
 * The nearest Wire UI context, or a default (en-US + English messages) value
 * when no `<WireUIProvider>` is mounted. `locale` / `messages` are reactive
 * getters — read them inside a tracking scope (JSX, a memo, an accessor) to
 * follow provider changes.
 */
export function useWireUI(): WireUIContextValue {
	return useContext(WireUIContext) ?? FALLBACK;
}

/**
 * The active locale as an accessor. A component's own `locale` prop (passed as
 * an accessor) always wins; otherwise the nearest provider's locale, then
 * `en-US`.
 */
export function useWireUILocale(localeProp?: () => string | undefined): Accessor<string> {
	const ctx = useWireUI();
	return () => localeProp?.() ?? ctx.locale;
}

/** The resolved message catalog as an accessor. */
export function useWireUIMessages(): Accessor<WireUIMessages> {
	const ctx = useWireUI();
	return () => ctx.messages;
}

// packages/react/src/context/wire-ui-context.ts
'use client';

import { createContext, useContext } from 'react';
import { defaultMessages, type WireUIMessages } from '@/utils/i18n/messages';

/** Locale used when no `<WireUIProvider>` (or explicit prop) sets one. */
export const DEFAULT_LOCALE = 'en-US';

export interface WireUIContextValue {
	/** BCP 47 locale tag (e.g. `en-US`, `de-DE`). */
	locale: string;
	/** Fully-resolved message catalog (defaults merged with overrides). */
	messages: WireUIMessages;
}

export const WireUIContext = createContext<WireUIContextValue | null>(null);

/**
 * The active locale. A `localeProp` (a component's own `locale` prop) always
 * wins; otherwise the nearest provider's locale, then `en-US`.
 */
export function useWireUILocale(localeProp?: string): string {
	const ctx = useContext(WireUIContext);
	return localeProp ?? ctx?.locale ?? DEFAULT_LOCALE;
}

/**
 * The resolved message catalog. Falls back to the English defaults when no
 * provider is mounted.
 */
export function useWireUIMessages(): WireUIMessages {
	return useContext(WireUIContext)?.messages ?? defaultMessages;
}

/** Both the active locale and resolved messages in one call. */
export function useWireUI(): WireUIContextValue {
	const ctx = useContext(WireUIContext);
	return ctx ?? { locale: DEFAULT_LOCALE, messages: defaultMessages };
}
