// packages/react/src/components/tooltip/Tooltip.tsx
import React, { createContext, useContext } from 'react';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useTimeout } from '@/hooks/use-timeout';
import type { TooltipContextValue, TooltipRootProps, TooltipTriggerProps, TooltipContentProps } from './Tooltip.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const TooltipContext = createContext<TooltipContextValue>({
	open: false,
	setOpen: () => {},
});

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = ({
	open: controlledOpen,
	defaultOpen = false,
	onOpenChange,
	delayDuration = 300,
	children,
}: TooltipRootProps) => {
	const [open, setOpenState] = useControllableState({
		value: controlledOpen,
		defaultValue: defaultOpen,
		onChange: onOpenChange,
	});
	const { start, stop } = useTimeout(() => setOpenState(true), delayDuration, { autoStart: false });

	const setOpen = (value: boolean) => {
		if (value) {
			start();
		} else {
			stop();
			setOpenState(false);
		}
	};

	return (
		<TooltipContext.Provider value={{ open, setOpen }}>
			<span style={{ position: 'relative', display: 'inline-block' }}>{children}</span>
		</TooltipContext.Provider>
	);
};

Root.displayName = 'Tooltip.Root';

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLSpanElement, TooltipTriggerProps>(
	({ children, onMouseEnter, onMouseLeave, onFocus, onBlur, ...rest }, ref) => {
		const { setOpen } = useContext(TooltipContext);

		return (
			<span
				ref={ref}
				onMouseEnter={(e) => {
					setOpen(true);
					onMouseEnter?.(e);
				}}
				onMouseLeave={(e) => {
					setOpen(false);
					onMouseLeave?.(e);
				}}
				onFocus={(e) => {
					setOpen(true);
					onFocus?.(e);
				}}
				onBlur={(e) => {
					setOpen(false);
					onBlur?.(e);
				}}
				{...rest}>
				{children}
			</span>
		);
	},
);

Trigger.displayName = 'Tooltip.Trigger';

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLSpanElement, TooltipContentProps>(
	({ side = 'top', className, children, style, ...rest }, ref) => {
		const { open } = useContext(TooltipContext);

		const positionStyle: React.CSSProperties = {
			position: 'absolute',
			zIndex: 50,
			pointerEvents: 'none',
			...(side === 'top' && {
				bottom: '100%',
				left: '50%',
				transform: 'translateX(-50%)',
				marginBottom: 8,
			}),
			...(side === 'bottom' && {
				top: '100%',
				left: '50%',
				transform: 'translateX(-50%)',
				marginTop: 8,
			}),
			...(side === 'left' && {
				right: '100%',
				top: '50%',
				transform: 'translateY(-50%)',
				marginRight: 8,
			}),
			...(side === 'right' && {
				left: '100%',
				top: '50%',
				transform: 'translateY(-50%)',
				marginLeft: 8,
			}),
		};

		return (
			<span
				ref={ref}
				role='tooltip'
				data-state={open ? 'open' : 'closed'}
				data-side={side}
				className={className}
				style={{ ...positionStyle, ...style }}
				{...rest}>
				{children}
			</span>
		);
	},
);

Content.displayName = 'Tooltip.Content';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Tooltip = { Root, Trigger, Content };

// packages/solid/src/components/tooltip/Tooltip.tsx
import { createContext, splitProps, useContext, type JSX } from 'solid-js';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createTimeout } from '@/primitives/create-timeout';
import type {
	TooltipContentProps,
	TooltipContextValue,
	TooltipRootProps,
	TooltipTriggerProps,
} from './Tooltip.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const TooltipContext = createContext<TooltipContextValue>({
	open: false,
	setOpen: () => {},
});

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: TooltipRootProps) {
	const [open, setOpenState] = createControllableState<boolean>({
		get value() {
			return props.open;
		},
		defaultValue: props.defaultOpen ?? false,
		get onChange() {
			return props.onOpenChange;
		},
	});

	const { start, stop } = createTimeout(() => setOpenState(true), () => props.delayDuration ?? 300, {
		autoStart: false,
	});

	const setOpen = (value: boolean) => {
		if (value) {
			start();
		} else {
			stop();
			setOpenState(false);
		}
	};

	const ctxValue: TooltipContextValue = {
		get open() {
			return !!open();
		},
		setOpen,
	};

	return (
		<TooltipContext.Provider value={ctxValue}>
			<span style={{ position: 'relative', display: 'inline-block' }}>{props.children}</span>
		</TooltipContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: TooltipTriggerProps) {
	const [local, rest] = splitProps(props, ['children', 'onMouseEnter', 'onMouseLeave', 'onFocus', 'onBlur']);
	const ctx = useContext(TooltipContext);

	const callUserHandler = <E,>(handler: unknown, e: E) => {
		if (typeof handler === 'function') (handler as (event: E) => void)(e);
	};

	const handleMouseEnter: JSX.EventHandler<HTMLSpanElement, MouseEvent> = (e) => {
		ctx.setOpen(true);
		callUserHandler(local.onMouseEnter, e);
	};
	const handleMouseLeave: JSX.EventHandler<HTMLSpanElement, MouseEvent> = (e) => {
		ctx.setOpen(false);
		callUserHandler(local.onMouseLeave, e);
	};
	const handleFocus: JSX.EventHandler<HTMLSpanElement, FocusEvent> = (e) => {
		ctx.setOpen(true);
		callUserHandler(local.onFocus, e);
	};
	const handleBlur: JSX.EventHandler<HTMLSpanElement, FocusEvent> = (e) => {
		ctx.setOpen(false);
		callUserHandler(local.onBlur, e);
	};

	return (
		<span
			onMouseEnter={handleMouseEnter}
			onMouseLeave={handleMouseLeave}
			onFocus={handleFocus}
			onBlur={handleBlur}
			{...rest}>
			{local.children}
		</span>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function Content(props: TooltipContentProps) {
	const [local, rest] = splitProps(props, ['side', 'class', 'children', 'style']);
	const ctx = useContext(TooltipContext);
	const side = () => local.side ?? 'top';

	const positionStyle = (): JSX.CSSProperties => {
		const s = side();
		const base: JSX.CSSProperties = {
			position: 'absolute',
			'z-index': 50,
			'pointer-events': 'none',
		};
		if (s === 'top') {
			return { ...base, bottom: '100%', left: '50%', transform: 'translateX(-50%)', 'margin-bottom': '8px' };
		}
		if (s === 'bottom') {
			return { ...base, top: '100%', left: '50%', transform: 'translateX(-50%)', 'margin-top': '8px' };
		}
		if (s === 'left') {
			return { ...base, right: '100%', top: '50%', transform: 'translateY(-50%)', 'margin-right': '8px' };
		}
		return { ...base, left: '100%', top: '50%', transform: 'translateY(-50%)', 'margin-left': '8px' };
	};

	const mergedStyle = () => {
		const userStyle = local.style;
		if (typeof userStyle === 'string' || !userStyle) return positionStyle();
		return { ...positionStyle(), ...(userStyle as JSX.CSSProperties) };
	};

	return (
		<span
			role='tooltip'
			data-state={ctx.open ? 'open' : 'closed'}
			data-side={side()}
			class={local.class}
			style={mergedStyle()}
			{...rest}>
			{local.children}
		</span>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Tooltip = { Root, Trigger, Content };

export { Root, Trigger, Content };
