// packages/react/src/components/slider/Slider.tsx
'use client';

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import { getDirection, useDirection } from '@/hooks/use-direction';
import type { SliderImplProps, SliderOrientation, SliderProps, SliderValue } from './Slider.types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function clamp(v: number, min: number, max: number) {
	return Math.min(Math.max(v, min), max);
}

function snapToStep(value: number, min: number, step: number) {
	const stepped = Math.round((value - min) / step) * step + min;
	return Number.isFinite(stepped) ? stepped : value;
}

function getDecimals(step: number) {
	const s = step.toString();
	const dot = s.indexOf('.');
	return dot === -1 ? 0 : s.length - dot - 1;
}

function roundFixed(value: number, decimals: number) {
	const factor = Math.pow(10, decimals);
	return Math.round(value * factor) / factor;
}

function arraysEqual(a: SliderValue, b: SliderValue) {
	if (a.length !== b.length) return false;
	for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
	return true;
}

// ---------------------------------------------------------------------------
// Slider
// ---------------------------------------------------------------------------

const SliderImpl = React.forwardRef<HTMLDivElement, SliderImplProps>((props, ref) => {
	const {
		min = 0,
		max = 100,
		step = 1,
		orientation = 'horizontal',
		disabled = false,
		inverted = false,
		className,
		children: _children,
		// Strip props that don't belong on the underlying <div>
		value: _v,
		defaultValue: _dv,
		onChange: _oc,
		range: _r,
		...rest
	} = props;
	void _v;
	void _dv;
	void _oc;
	void _r;
	void _children;

	const range = props.range === true;

	// Accessible name supplied by the consumer. The wrapper carries it for the
	// group (range mode), but the `role="slider"` thumbs are the actual ARIA
	// input fields and must each expose a name of their own.
	const ariaLabel = (rest as { 'aria-label'?: string })['aria-label'];
	const ariaLabelledBy = (rest as { 'aria-labelledby'?: string })['aria-labelledby'];

	// --- Controlled / uncontrolled value state -------------------------------
	const initial: SliderValue = range
		? ((props.defaultValue as [number, number] | undefined) ?? [min, max])
		: [(props.defaultValue as number | undefined) ?? min];

	const [uncontrolled, setUncontrolled] = useState<SliderValue>(() => {
		const decimals = getDecimals(step);
		return initial.map((v) => roundFixed(clamp(snapToStep(v, min, step), min, max), decimals));
	});

	const isControlled = props.value !== undefined;
	const controlledValue: SliderValue | undefined = (() => {
		if (props.value === undefined) return undefined;
		return Array.isArray(props.value) ? props.value : [props.value];
	})();
	const value: SliderValue = isControlled ? (controlledValue as SliderValue) : uncontrolled;

	const decimals = getDecimals(step);

	const emit = useCallback(
		(next: SliderValue) => {
			const decimalsLocal = getDecimals(step);
			const normalized = next.map((v) => roundFixed(clamp(snapToStep(v, min, step), min, max), decimalsLocal));
			if (range) {
				// Keep ordering: lower thumb cannot pass upper thumb
				if (normalized[0] > normalized[1]) [normalized[0], normalized[1]] = [normalized[1], normalized[0]];
			}
			if (arraysEqual(normalized, value)) return;
			if (!isControlled) setUncontrolled(normalized);
			if (range) (props.onChange as ((v: [number, number]) => void) | undefined)?.([normalized[0], normalized[1]]);
			else (props.onChange as ((v: number) => void) | undefined)?.(normalized[0]);
		},
		[isControlled, min, max, step, range, props.onChange, value],
	);

	// --- Track / thumb interaction ------------------------------------------
	const trackRef = useRef<HTMLDivElement | null>(null);
	const draggingRef = useRef<{ thumbIndex: number } | null>(null);
	const rtl = useDirection(trackRef) === 'rtl';

	const setMergedRef = useMergedRefs<HTMLDivElement>(trackRef, ref);

	const valueFromPoint = useCallback(
		(clientX: number, clientY: number): number => {
			const el = trackRef.current;
			if (!el) return min;
			const rect = el.getBoundingClientRect();
			const isHorizontal = orientation === 'horizontal';
			const start = isHorizontal ? rect.left : rect.top;
			const length = isHorizontal ? rect.width : rect.height;
			const point = isHorizontal ? clientX : clientY;
			let pct = (point - start) / length;
			if (!isHorizontal) pct = inverted ? pct : 1 - pct; // vertical default = bottom→top
			else {
				// In RTL the horizontal axis is mirrored: the track's start (min) sits on
				// the right, so the fraction measured from the physical left must flip.
				const rtl = getDirection(el) === 'rtl';
				if (inverted !== rtl) pct = 1 - pct;
			}
			pct = clamp(pct, 0, 1);
			return min + pct * (max - min);
		},
		[orientation, min, max, inverted],
	);

	const closestThumb = useCallback(
		(target: number): number => {
			if (!range) return 0;
			const da = Math.abs(target - value[0]);
			const db = Math.abs(target - value[1]);
			return da <= db ? 0 : 1;
		},
		[range, value],
	);

	const updateThumb = useCallback(
		(thumbIndex: number, target: number) => {
			const next = value.slice();
			next[thumbIndex] = target;
			emit(next);
		},
		[value, emit],
	);

	const handlePointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
		if (disabled) return;
		const target = valueFromPoint(e.clientX, e.clientY);
		const thumbIndex = closestThumb(target);
		draggingRef.current = { thumbIndex };
		(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);
		updateThumb(thumbIndex, target);
	};

	const handlePointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
		if (!draggingRef.current) return;
		const target = valueFromPoint(e.clientX, e.clientY);
		updateThumb(draggingRef.current.thumbIndex, target);
	};

	const handlePointerUp = (e: React.PointerEvent<HTMLDivElement>) => {
		if (!draggingRef.current) return;
		(e.currentTarget as HTMLElement).releasePointerCapture?.(e.pointerId);
		draggingRef.current = null;
	};

	// Cancel drag on unmount.
	useEffect(() => () => { draggingRef.current = null; }, []);

	// --- Keyboard ------------------------------------------------------------
	const handleThumbKeyDown = (thumbIndex: number) => (e: React.KeyboardEvent<HTMLSpanElement>) => {
		if (disabled) return;
		const horizontal = orientation === 'horizontal';
		// RTL mirrors the horizontal axis, so the arrow that increases the value flips.
		const flipH = horizontal && inverted !== (getDirection(e.currentTarget) === 'rtl');
		const incKey = horizontal ? (flipH ? 'ArrowLeft' : 'ArrowRight') : (inverted ? 'ArrowDown' : 'ArrowUp');
		const decKey = horizontal ? (flipH ? 'ArrowRight' : 'ArrowLeft') : (inverted ? 'ArrowUp' : 'ArrowDown');
		const big = step * 10;

		let delta = 0;
		if (e.key === incKey) delta = step;
		else if (e.key === decKey) delta = -step;
		else if (e.key === 'PageUp') delta = big;
		else if (e.key === 'PageDown') delta = -big;
		else if (e.key === 'Home') {
			e.preventDefault();
			updateThumb(thumbIndex, min);
			return;
		} else if (e.key === 'End') {
			e.preventDefault();
			updateThumb(thumbIndex, max);
			return;
		} else return;

		e.preventDefault();
		updateThumb(thumbIndex, value[thumbIndex] + delta);
	};

	// --- Render --------------------------------------------------------------
	const pct = useMemo(() => value.map((v) => ((v - min) / (max - min)) * 100), [value, min, max]);
	const fillStart = range ? Math.min(pct[0], pct[1]) : 0;
	const fillEnd = range ? Math.max(pct[0], pct[1]) : pct[0];

	const isHorizontal = orientation === 'horizontal';
	// In RTL the horizontal axis is mirrored. Folding that into `inverted` keeps the
	// LTR render path byte-for-byte unchanged.
	const placeInverted = isHorizontal ? inverted !== rtl : inverted;
	const fillStyle: React.CSSProperties = isHorizontal
		? placeInverted
			? { right: `${fillStart}%`, width: `${fillEnd - fillStart}%`, top: 0, bottom: 0 }
			: { left: `${fillStart}%`, width: `${fillEnd - fillStart}%`, top: 0, bottom: 0 }
		: inverted
			? { top: `${fillStart}%`, height: `${fillEnd - fillStart}%`, left: 0, right: 0 }
			: { bottom: `${fillStart}%`, height: `${fillEnd - fillStart}%`, left: 0, right: 0 };

	const thumbStyle = (i: number): React.CSSProperties => {
		const p = pct[i];
		if (isHorizontal) {
			return placeInverted
				? { right: `${p}%`, top: '50%', transform: 'translate(50%, -50%)' }
				: { left: `${p}%`, top: '50%', transform: 'translate(-50%, -50%)' };
		}
		return inverted
			? { top: `${p}%`, left: '50%', transform: 'translate(-50%, -50%)' }
			: { bottom: `${p}%`, left: '50%', transform: 'translate(-50%, 50%)' };
	};

	return (
		<div
			ref={setMergedRef}
			role={range ? 'group' : undefined}
			aria-label={range ? ariaLabel : undefined}
			aria-labelledby={range ? ariaLabelledBy : undefined}
			className={className}
			data-orientation={orientation}
			data-disabled={disabled ? '' : undefined}
			onPointerDown={handlePointerDown}
			onPointerMove={handlePointerMove}
			onPointerUp={handlePointerUp}
			onPointerCancel={handlePointerUp}
			style={{ position: 'relative', userSelect: 'none', touchAction: 'none', ...(rest as { style?: React.CSSProperties }).style }}
			{...stripStyleAndChildren(rest as Record<string, unknown>)}>
			<span data-part='track' style={{ position: 'absolute', inset: 0 }} />
			<span data-part='fill' style={{ position: 'absolute', ...fillStyle }} />
			{value.map((v, i) => {
				// Each thumb is an ARIA input field and needs its own accessible
				// name. In single mode it inherits the consumer's label directly.
				// In range mode the group carries the overall label, so each thumb
				// gets a distinguishing name. `aria-labelledby` (single mode) takes
				// precedence over `aria-label` when both are supplied.
				const thumbLabelledBy = !range ? ariaLabelledBy : undefined;
				const thumbLabel = thumbLabelledBy
					? undefined
					: range
						? [i === 0 ? 'Minimum' : 'Maximum', ariaLabel].filter(Boolean).join(' ')
						: ariaLabel;
				return (
					<span
						key={i}
						role='slider'
						tabIndex={disabled ? -1 : 0}
						aria-label={thumbLabel || undefined}
						aria-labelledby={thumbLabelledBy}
						aria-valuemin={min}
						aria-valuemax={max}
						aria-valuenow={roundFixed(v, decimals)}
						aria-orientation={orientation}
						aria-disabled={disabled || undefined}
						data-part='thumb'
						data-thumb-index={i}
						data-disabled={disabled ? '' : undefined}
						onKeyDown={handleThumbKeyDown(i)}
						style={{ position: 'absolute', ...thumbStyle(i) }}
					/>
				);
			})}
		</div>
	);
});

SliderImpl.displayName = 'Slider';

// `style`, `aria-label`, and `aria-labelledby` are extracted and applied to the
// thumb(s) (and the group wrapper in range mode); pass everything else through.
function stripStyleAndChildren<T extends Record<string, unknown>>(props: T): Omit<T, 'style' | 'aria-label' | 'aria-labelledby'> {
	const { style: _s, ['aria-label']: _a, ['aria-labelledby']: _al, ...rest } = props;
	void _s;
	void _a;
	void _al;
	return rest as Omit<T, 'style' | 'aria-label' | 'aria-labelledby'>;
}

export const Slider = SliderImpl as React.ForwardRefExoticComponent<
	SliderProps & React.RefAttributes<HTMLDivElement>
>;

function _orientationGuard(_o: SliderOrientation) { /* keeps SliderOrientation imported for declaration files */ }
void _orientationGuard;

// packages/vue/src/components/slider/Slider.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, useAttrs, type CSSProperties } from 'vue';
import { getDirection, useDirection } from '@/composables/use-direction';
import type { SliderOrientation, SliderValue } from './Slider.types';

// `aria-label` / `aria-labelledby` arrive as fallthrough attributes. They name
// the `role="slider"` thumbs (the actual ARIA input fields), so we read them
// here and keep them off the root wrapper in single mode.
defineOptions({ name: 'Slider', inheritAttrs: false })

const props = withDefaults(defineProps<{
	/** Minimum value. */
	min?: number;
	/** Maximum value. */
	max?: number;
	/** Step increment. */
	step?: number;
	/** Layout orientation. */
	orientation?: SliderOrientation;
	/** Disable the slider. */
	disabled?: boolean;
	/** Inverted (right-to-left or top-to-bottom). */
	inverted?: boolean;
	/** Enable two-thumb range mode. With `range`, `value` becomes `[start, end]`. */
	range?: boolean;
	/** Controlled value — a number in single mode, `[start, end]` in range mode. */
	value?: number | [number, number];
	/** Initial value, uncontrolled — a number in single mode, `[start, end]` in range mode. */
	defaultValue?: number | [number, number];
	/** Called when the value changes. */
	onChange?: (value: number | [number, number]) => void;
}>(), {
	min: 0,
	max: 100,
	step: 1,
	orientation: 'horizontal',
	disabled: false,
	inverted: false,
	range: false,
	value: undefined,
	defaultValue: undefined,
	onChange: undefined,
})

const attrs = useAttrs()
const ariaLabelAttr = computed(() => attrs['aria-label'] as string | undefined)
const ariaLabelledByAttr = computed(() => attrs['aria-labelledby'] as string | undefined)

// Everything except the ARIA name attributes falls through to the root wrapper;
// the names themselves are applied to the group / thumbs explicitly.
const rootAttrs = computed(() => {
	const { ['aria-label']: _a, ['aria-labelledby']: _al, ...rest } = attrs
	void _a
	void _al
	return rest
})

// --- Helpers ---------------------------------------------------------------
function clamp(v: number, min: number, max: number) {
	return Math.min(Math.max(v, min), max)
}

function snapToStep(value: number, min: number, step: number) {
	const stepped = Math.round((value - min) / step) * step + min
	return Number.isFinite(stepped) ? stepped : value
}

function getDecimals(step: number) {
	const s = step.toString()
	const dot = s.indexOf('.')
	return dot === -1 ? 0 : s.length - dot - 1
}

function roundFixed(value: number, decimals: number) {
	const factor = Math.pow(10, decimals)
	return Math.round(value * factor) / factor
}

function arraysEqual(a: SliderValue, b: SliderValue) {
	if (a.length !== b.length) return false
	for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false
	return true
}

const isRange = computed(() => props.range === true)

// --- Controlled / uncontrolled value state ---------------------------------
function makeInitial(): SliderValue {
	const decimals = getDecimals(props.step)
	const raw: SliderValue = isRange.value
		? ((props.defaultValue as [number, number] | undefined) ?? [props.min, props.max])
		: [(props.defaultValue as number | undefined) ?? props.min]
	return raw.map((v) => roundFixed(clamp(snapToStep(v, props.min, props.step), props.min, props.max), decimals))
}

const uncontrolled = ref<SliderValue>(makeInitial())

const isControlled = computed(() => props.value !== undefined)
const controlledValue = computed<SliderValue | undefined>(() => {
	if (props.value === undefined) return undefined
	return Array.isArray(props.value) ? props.value : [props.value]
})
const thumbValues = computed<SliderValue>(() => (isControlled.value ? (controlledValue.value as SliderValue) : uncontrolled.value))

const decimals = computed(() => getDecimals(props.step))

function emit(next: SliderValue) {
	const d = getDecimals(props.step)
	const normalized = next.map((v) => roundFixed(clamp(snapToStep(v, props.min, props.step), props.min, props.max), d))
	if (isRange.value && normalized[0] > normalized[1]) [normalized[0], normalized[1]] = [normalized[1], normalized[0]]
	if (arraysEqual(normalized, thumbValues.value)) return
	if (!isControlled.value) uncontrolled.value = normalized
	if (isRange.value) (props.onChange as ((v: [number, number]) => void) | undefined)?.([normalized[0], normalized[1]])
	else (props.onChange as ((v: number) => void) | undefined)?.(normalized[0])
}

// --- Track / thumb interaction ---------------------------------------------
const trackRef = ref<HTMLDivElement | null>(null)
const direction = useDirection(trackRef)
const rtl = computed(() => direction.value === 'rtl')
let dragging: { thumbIndex: number } | null = null

function valueFromPoint(clientX: number, clientY: number): number {
	const el = trackRef.value
	if (!el) return props.min
	const rect = el.getBoundingClientRect()
	const isHorizontal = props.orientation === 'horizontal'
	const start = isHorizontal ? rect.left : rect.top
	const length = isHorizontal ? rect.width : rect.height
	const point = isHorizontal ? clientX : clientY
	let pct = (point - start) / length
	if (!isHorizontal) pct = props.inverted ? pct : 1 - pct // vertical default = bottom→top
	else {
		// In RTL the horizontal axis is mirrored: the track's start (min) sits on
		// the right, so the fraction measured from the physical left must flip.
		const isRtl = getDirection(el) === 'rtl'
		if (props.inverted !== isRtl) pct = 1 - pct
	}
	pct = clamp(pct, 0, 1)
	return props.min + pct * (props.max - props.min)
}

function closestThumb(target: number): number {
	if (!isRange.value) return 0
	const da = Math.abs(target - thumbValues.value[0])
	const db = Math.abs(target - thumbValues.value[1])
	return da <= db ? 0 : 1
}

function updateThumb(thumbIndex: number, target: number) {
	const next = thumbValues.value.slice()
	next[thumbIndex] = target
	emit(next)
}

function handlePointerDown(e: PointerEvent) {
	if (props.disabled) return
	const target = valueFromPoint(e.clientX, e.clientY)
	const thumbIndex = closestThumb(target)
	dragging = { thumbIndex }
	;(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId)
	updateThumb(thumbIndex, target)
}

function handlePointerMove(e: PointerEvent) {
	if (!dragging) return
	const target = valueFromPoint(e.clientX, e.clientY)
	updateThumb(dragging.thumbIndex, target)
}

function handlePointerUp(e: PointerEvent) {
	if (!dragging) return
	;(e.currentTarget as HTMLElement).releasePointerCapture?.(e.pointerId)
	dragging = null
}

onUnmounted(() => { dragging = null })

// --- Keyboard --------------------------------------------------------------
function onThumbKeyDown(e: KeyboardEvent, thumbIndex: number) {
	if (props.disabled) return
	const horizontal = props.orientation === 'horizontal'
	// RTL mirrors the horizontal axis, so the arrow that increases the value flips.
	const flipH = horizontal && props.inverted !== (getDirection(e.currentTarget as Element) === 'rtl')
	const incKey = horizontal ? (flipH ? 'ArrowLeft' : 'ArrowRight') : (props.inverted ? 'ArrowDown' : 'ArrowUp')
	const decKey = horizontal ? (flipH ? 'ArrowRight' : 'ArrowLeft') : (props.inverted ? 'ArrowUp' : 'ArrowDown')
	const big = props.step * 10

	let delta = 0
	if (e.key === incKey) delta = props.step
	else if (e.key === decKey) delta = -props.step
	else if (e.key === 'PageUp') delta = big
	else if (e.key === 'PageDown') delta = -big
	else if (e.key === 'Home') {
		e.preventDefault()
		updateThumb(thumbIndex, props.min)
		return
	} else if (e.key === 'End') {
		e.preventDefault()
		updateThumb(thumbIndex, props.max)
		return
	} else return

	e.preventDefault()
	updateThumb(thumbIndex, thumbValues.value[thumbIndex] + delta)
}

// --- Render ----------------------------------------------------------------
const pct = computed(() => thumbValues.value.map((v) => ((v - props.min) / (props.max - props.min)) * 100))
const fillStart = computed(() => (isRange.value ? Math.min(pct.value[0], pct.value[1]) : 0))
const fillEnd = computed(() => (isRange.value ? Math.max(pct.value[0], pct.value[1]) : pct.value[0]))
const isHorizontal = computed(() => props.orientation === 'horizontal')

const rootStyle: CSSProperties = { position: 'relative', userSelect: 'none', touchAction: 'none' }

// In RTL the horizontal axis is mirrored. Folding that into `inverted` keeps the
// LTR render path unchanged.
const placeInverted = computed(() => (isHorizontal.value ? props.inverted !== rtl.value : props.inverted))

const fillStyle = computed<CSSProperties>(() => {
	const start = fillStart.value
	const end = fillEnd.value
	if (isHorizontal.value) {
		return placeInverted.value
			? { position: 'absolute', right: `${start}%`, width: `${end - start}%`, top: 0, bottom: 0 }
			: { position: 'absolute', left: `${start}%`, width: `${end - start}%`, top: 0, bottom: 0 }
	}
	return props.inverted
		? { position: 'absolute', top: `${start}%`, height: `${end - start}%`, left: 0, right: 0 }
		: { position: 'absolute', bottom: `${start}%`, height: `${end - start}%`, left: 0, right: 0 }
})

function thumbStyle(i: number): CSSProperties {
	const p = pct.value[i]
	if (isHorizontal.value) {
		return placeInverted.value
			? { position: 'absolute', right: `${p}%`, top: '50%', transform: 'translate(50%, -50%)' }
			: { position: 'absolute', left: `${p}%`, top: '50%', transform: 'translate(-50%, -50%)' }
	}
	return props.inverted
		? { position: 'absolute', top: `${p}%`, left: '50%', transform: 'translate(-50%, -50%)' }
		: { position: 'absolute', bottom: `${p}%`, left: '50%', transform: 'translate(-50%, 50%)' }
}

// The wrapper carries the accessible name for the group (range mode only);
// the `role="slider"` thumbs are the actual ARIA input fields and each expose
// a name of their own.
const ariaLabel = computed(() => (isRange.value ? ariaLabelAttr.value : undefined))
const ariaLabelledBy = computed(() => (isRange.value ? ariaLabelledByAttr.value : undefined))

// Each thumb is an ARIA input field and needs its own accessible name. In
// single mode it inherits the consumer's label directly; in range mode the
// group carries the overall label, so each thumb gets a distinguishing name.
// `aria-labelledby` (single mode) takes precedence over `aria-label`.
function thumbLabelledBy(): string | undefined {
	return !isRange.value ? ariaLabelledByAttr.value : undefined
}

function thumbLabel(i: number): string | undefined {
	if (thumbLabelledBy()) return undefined
	if (isRange.value) {
		return [i === 0 ? 'Minimum' : 'Maximum', ariaLabelAttr.value].filter(Boolean).join(' ') || undefined
	}
	return ariaLabelAttr.value
}
</script>

<template>
	<div
		ref="trackRef"
		v-bind="rootAttrs"
		:role="isRange ? 'group' : undefined"
		:aria-label="ariaLabel"
		:aria-labelledby="ariaLabelledBy"
		:data-orientation="orientation"
		:data-disabled="disabled ? '' : undefined"
		:style="rootStyle"
		@pointerdown="handlePointerDown"
		@pointermove="handlePointerMove"
		@pointerup="handlePointerUp"
		@pointercancel="handlePointerUp"
	>
		<span data-part="track" :style="{ position: 'absolute', inset: 0 }" />
		<span data-part="fill" :style="fillStyle" />
		<span
			v-for="(v, i) in thumbValues"
			:key="i"
			role="slider"
			:tabindex="disabled ? -1 : 0"
			:aria-label="thumbLabel(i) || undefined"
			:aria-labelledby="thumbLabelledBy()"
			:aria-valuemin="min"
			:aria-valuemax="max"
			:aria-valuenow="roundFixed(v, decimals)"
			:aria-orientation="orientation"
			:aria-disabled="disabled || undefined"
			data-part="thumb"
			:data-thumb-index="i"
			:data-disabled="disabled ? '' : undefined"
			:style="thumbStyle(i)"
			@keydown="(e: KeyboardEvent) => onThumbKeyDown(e, i)"
		/>
	</div>
</template>
