// src/components/card/Card.tsx
import React from 'react'
import type { CardProps } from './Card.types'

const Card = React.forwardRef<HTMLDivElement, CardProps>(
	({ color, size, className, children, ...rest }, ref) => {
		return (
			<div ref={ref} className={className} data-color={color} data-size={size} {...rest}>
				{children}
			</div>
		)
	},
)

Card.displayName = 'Card'

export { Card }

// packages/solid/src/components/card/Card.tsx
import { splitProps } from 'solid-js';
import type { CardProps } from './Card.types';

function Card(props: CardProps) {
	const [local, rest] = splitProps(props, ['color', 'size', 'class', 'children']);

	return (
		<div
			class={local.class}
			data-color={local.color}
			data-size={local.size}
			{...rest}>
			{local.children}
		</div>
	);
}

export { Card };
