// packages/solid/src/components/menu-bar/MenuBar.tsx
import { createContext, createEffect, createSignal, onCleanup, onMount, Show, splitProps, useContext, type JSX } from 'solid-js';
import { createClickOutside } from '@/primitives/create-click-outside';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	MenuBarContentProps,
	MenuBarContextValue,
	MenuBarItemProps,
	MenuBarMenuContextValue,
	MenuBarMenuProps,
	MenuBarRootProps,
	MenuBarSeparatorProps,
	MenuBarTriggerProps,
} from './MenuBar.types';

// ---------------------------------------------------------------------------
// Contexts
// ---------------------------------------------------------------------------

const MenuBarContext = createContext<MenuBarContextValue | null>(null);
const MenuContext = createContext<MenuBarMenuContextValue | null>(null);

function useBarContext() {
	const ctx = useContext(MenuBarContext);
	if (!ctx) throw new Error('MenuBar compound components must be used within MenuBar.Root');
	return ctx;
}

function useMenuContext() {
	const ctx = useContext(MenuContext);
	if (!ctx) throw new Error('MenuBar.Trigger / Content must be used within MenuBar.Menu');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: MenuBarRootProps) {
	const [local, rest] = splitProps(props, ['value', 'defaultValue', 'onValueChange', 'children', 'class']);

	const [uncontrolled, setUncontrolled] = createSignal<string | null>(local.defaultValue ?? null);
	const isControlled = () => local.value !== undefined;
	const openMenu = () => (isControlled() ? (local.value as string | null) : uncontrolled());

	const order: string[] = [];

	const setOpenMenu = (next: string | null) => {
		if (!isControlled()) setUncontrolled(next);
		local.onValueChange?.(next);
	};

	const registerMenu = (id: string) => {
		if (!order.includes(id)) order.push(id);
	};
	const unregisterMenu = (id: string) => {
		const idx = order.indexOf(id);
		if (idx >= 0) order.splice(idx, 1);
	};
	const getMenuOrder = () => order.slice();

	let rootEl: HTMLDivElement | undefined;

	createClickOutside(
		() => rootEl,
		() => {
			if (openMenu()) setOpenMenu(null);
		},
	);

	createEffect(() => {
		const handle = (e: KeyboardEvent) => {
			if (e.key === 'Escape' && openMenu()) setOpenMenu(null);
		};
		window.addEventListener('keyup', handle);
		onCleanup(() => window.removeEventListener('keyup', handle));
	});

	const ctxValue: MenuBarContextValue = {
		get openMenu() {
			return openMenu();
		},
		setOpenMenu,
		registerMenu,
		unregisterMenu,
		getMenuOrder,
	};

	return (
		<MenuBarContext.Provider value={ctxValue}>
			<div
				ref={rootEl}
				role='menubar'
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</MenuBarContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Menu
// ---------------------------------------------------------------------------

function Menu(props: MenuBarMenuProps) {
	const [local, rest] = splitProps(props, ['value', 'children', 'class']);
	const bar = useBarContext();
	const open = () => bar.openMenu === local.value;

	onMount(() => {
		bar.registerMenu(local.value);
		onCleanup(() => bar.unregisterMenu(local.value));
	});

	const close = () => bar.setOpenMenu(null);
	const open_ = () => bar.setOpenMenu(local.value);
	const toggle = () => bar.setOpenMenu(open() ? null : local.value);

	const menuCtx: MenuBarMenuContextValue = {
		get value() {
			return local.value;
		},
		get open() {
			return open();
		},
		close,
		open_,
		toggle,
	};

	return (
		<MenuContext.Provider value={menuCtx}>
			<div
				class={local.class}
				data-state={open() ? 'open' : 'closed'}
				{...rest}>
				{local.children}
			</div>
		</MenuContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: MenuBarTriggerProps) {
	const [local, rest] = splitProps(props, ['disabled', 'children', 'class', 'onClick', 'onPointerEnter']);
	const bar = useBarContext();
	const menu = useMenuContext();
	const state = createInteractiveState({
		get disabled() {
			return !!local.disabled;
		},
	});
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		menu.toggle();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	const handlePointerEnter: JSX.EventHandler<HTMLButtonElement, PointerEvent> = (e) => {
		// If any other menu is open, hovering switches focus to this one.
		if (bar.openMenu && bar.openMenu !== menu.value) bar.setOpenMenu(menu.value);
		const userOnPointerEnter = local.onPointerEnter;
		if (typeof userOnPointerEnter === 'function') {
			(userOnPointerEnter as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			disabled={local.disabled}
			aria-haspopup='menu'
			aria-expanded={menu.open}
			class={local.class}
			data-state={menu.open ? 'open' : 'closed'}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}
			onPointerEnter={handlePointerEnter}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function Content(props: MenuBarContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const menu = useMenuContext();

	return (
		<Show when={menu.open}>
			<div
				role='menu'
				class={local.class}
				data-state='open'
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

function Item(props: MenuBarItemProps) {
	const [local, rest] = splitProps(props, ['disabled', 'onSelect', 'children', 'class', 'onClick', 'onKeyDown']);
	const menu = useMenuContext();
	const state = createInteractiveState({
		get disabled() {
			return !!local.disabled;
		},
	});
	const merged = mergeProps(rest, state.handlers);

	const select = () => {
		if (local.disabled) return;
		local.onSelect?.();
		menu.close();
	};

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		select();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (e) => {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			select();
		}
		const userOnKeyDown = local.onKeyDown;
		if (typeof userOnKeyDown === 'function') {
			(userOnKeyDown as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			role='menuitem'
			tabIndex={local.disabled ? -1 : 0}
			aria-disabled={local.disabled || undefined}
			class={local.class}
			data-disabled={local.disabled ? '' : undefined}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}
			onKeyDown={handleKeyDown}>
			{local.children}
		</div>
	);
}

function Separator(props: MenuBarSeparatorProps) {
	const [local, rest] = splitProps(props, ['class']);
	return (
		<div
			role='separator'
			class={local.class}
			{...rest}
		/>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const MenuBar = { Root, Menu, Trigger, Content, Item, Separator };

// packages/react/src/components/menu-bar/MenuBar.tsx
import React, {
	createContext,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useRef,
	useState,
} from 'react';
import { useClickOutside } from '@/hooks/use-click-outside';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	MenuBarContentProps,
	MenuBarContextValue,
	MenuBarItemProps,
	MenuBarMenuContextValue,
	MenuBarMenuProps,
	MenuBarRootProps,
	MenuBarSeparatorProps,
	MenuBarTriggerProps,
} from './MenuBar.types';

// ---------------------------------------------------------------------------
// Contexts
// ---------------------------------------------------------------------------

const MenuBarContext = createContext<MenuBarContextValue | null>(null);
const MenuContext = createContext<MenuBarMenuContextValue | null>(null);

function useBarContext() {
	const ctx = useContext(MenuBarContext);
	if (!ctx) throw new globalThis.Error('MenuBar compound components must be used within MenuBar.Root');
	return ctx;
}

function useMenuContext() {
	const ctx = useContext(MenuContext);
	if (!ctx) throw new globalThis.Error('MenuBar.Trigger / Content must be used within MenuBar.Menu');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, MenuBarRootProps>(
	({ value: controlledValue, defaultValue = null, onValueChange, children, className, ...rest }, ref) => {
		const [uncontrolled, setUncontrolled] = useState<string | null>(defaultValue);
		const isControlled = controlledValue !== undefined;
		const openMenu = isControlled ? (controlledValue as string | null) : uncontrolled;

		const orderRef = useRef<string[]>([]);

		const setOpenMenu = useCallback(
			(next: string | null) => {
				if (!isControlled) setUncontrolled(next);
				onValueChange?.(next);
			},
			[isControlled, onValueChange],
		);

		const registerMenu = useCallback((id: string) => {
			if (!orderRef.current.includes(id)) orderRef.current.push(id);
		}, []);

		const unregisterMenu = useCallback((id: string) => {
			orderRef.current = orderRef.current.filter((v) => v !== id);
		}, []);

		const getMenuOrder = useCallback(() => orderRef.current.slice(), []);

		const internalRef = useRef<HTMLDivElement | null>(null);
		const setMergedRef = (el: HTMLDivElement | null) => {
			internalRef.current = el;
			if (typeof ref === 'function') ref(el);
			else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el;
		};

		useClickOutside(internalRef, () => {
			if (openMenu) setOpenMenu(null);
		});

		useEffect(() => {
			const handle = (e: KeyboardEvent) => {
				if (e.key === 'Escape' && openMenu) setOpenMenu(null);
			};
			window.addEventListener('keyup', handle);
			return () => window.removeEventListener('keyup', handle);
		}, [openMenu, setOpenMenu]);

		const ctx = useMemo<MenuBarContextValue>(
			() => ({ openMenu, setOpenMenu, registerMenu, unregisterMenu, getMenuOrder }),
			[openMenu, setOpenMenu, registerMenu, unregisterMenu, getMenuOrder],
		);

		return (
			<MenuBarContext.Provider value={ctx}>
				<div
					ref={setMergedRef}
					role='menubar'
					className={className}
					{...rest}>
					{children}
				</div>
			</MenuBarContext.Provider>
		);
	},
);
Root.displayName = 'MenuBar.Root';

// ---------------------------------------------------------------------------
// Menu (single dropdown column — File, Edit, etc)
// ---------------------------------------------------------------------------

const Menu = React.forwardRef<HTMLDivElement, MenuBarMenuProps>(
	({ value, children, className, ...rest }, ref) => {
		const bar = useBarContext();
		const open = bar.openMenu === value;

		useEffect(() => {
			bar.registerMenu(value);
			return () => bar.unregisterMenu(value);
		}, [value, bar]);

		const close = useCallback(() => bar.setOpenMenu(null), [bar]);
		const open_ = useCallback(() => bar.setOpenMenu(value), [bar, value]);
		const toggle = useCallback(() => bar.setOpenMenu(open ? null : value), [bar, open, value]);

		const menuCtx = useMemo<MenuBarMenuContextValue>(
			() => ({ value, open, close, open_, toggle }),
			[value, open, close, open_, toggle],
		);

		return (
			<MenuContext.Provider value={menuCtx}>
				<div
					ref={ref}
					className={className}
					data-state={open ? 'open' : 'closed'}
					{...rest}>
					{children}
				</div>
			</MenuContext.Provider>
		);
	},
);
Menu.displayName = 'MenuBar.Menu';

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLButtonElement, MenuBarTriggerProps>(
	({ disabled = false, children, className, onClick, onPointerEnter, ...rest }, ref) => {
		const bar = useBarContext();
		const menu = useMenuContext();
		const { handlers, dataAttributes } = useInteractiveState({ disabled });
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		return (
			<button
				ref={ref}
				type='button'
				disabled={disabled}
				aria-haspopup='menu'
				aria-expanded={menu.open}
				className={className}
				data-state={menu.open ? 'open' : 'closed'}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					menu.toggle();
					onClick?.(e);
				}}
				onPointerEnter={(e) => {
					// If any other menu is open, hovering switches focus to this one.
					if (bar.openMenu && bar.openMenu !== menu.value) bar.setOpenMenu(menu.value);
					onPointerEnter?.(e);
				}}>
				{children}
			</button>
		);
	},
);
Trigger.displayName = 'MenuBar.Trigger';

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLDivElement, MenuBarContentProps>(
	({ children, className, ...rest }, ref) => {
		const menu = useMenuContext();
		if (!menu.open) return null;

		return (
			<div
				ref={ref}
				role='menu'
				className={className}
				data-state='open'
				{...rest}>
				{children}
			</div>
		);
	},
);
Content.displayName = 'MenuBar.Content';

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

const Item = React.forwardRef<HTMLDivElement, MenuBarItemProps>(
	({ disabled = false, onSelect, children, className, onClick, onKeyDown, ...rest }, ref) => {
		const menu = useMenuContext();
		const { handlers, dataAttributes } = useInteractiveState({ disabled });
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		const select = () => {
			if (disabled) return;
			onSelect?.();
			menu.close();
		};

		return (
			<div
				ref={ref}
				role='menuitem'
				tabIndex={disabled ? -1 : 0}
				aria-disabled={disabled || undefined}
				className={className}
				data-disabled={disabled ? '' : undefined}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					select();
					onClick?.(e);
				}}
				onKeyDown={(e) => {
					if (e.key === 'Enter' || e.key === ' ') {
						e.preventDefault();
						select();
					}
					onKeyDown?.(e);
				}}>
				{children}
			</div>
		);
	},
);
Item.displayName = 'MenuBar.Item';

const Separator = React.forwardRef<HTMLDivElement, MenuBarSeparatorProps>(({ className, ...rest }, ref) => (
	<div
		ref={ref}
		role='separator'
		className={className}
		{...rest}
	/>
));
Separator.displayName = 'MenuBar.Separator';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const MenuBar = { Root, Menu, Trigger, Content, Item, Separator };
