// packages/solid/src/components/modal/Modal.tsx
'use client';

import { createContext, Show, splitProps, useContext, type JSX } from 'solid-js';
import { Portal as SolidPortal } from 'solid-js/web';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createFocusTrap } from '@/primitives/create-focus-trap';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { createKeyboard } from '@/primitives/create-keyboard';
import { createMergedRefs } from '@/primitives/create-merged-refs';
import { createScrollLock } from '@/primitives/create-scroll-lock';
import { mergeProps } from '@/utils/merge-props';
import type {
	ModalCloseProps,
	ModalContentProps,
	ModalContextValue,
	ModalOverlayProps,
	ModalPortalProps,
	ModalRootProps,
} from './Modal.types';

const ModalContext = createContext<ModalContextValue | null>(null);

function useModalContext() {
	const context = useContext(ModalContext);
	if (!context) {
		throw new Error('Modal compound components must be used within Modal.Root');
	}
	return context;
}

function Root(props: ModalRootProps) {
	const [open, setOpen] = createControllableState<boolean>({
		get value() {
			return props.open;
		},
		defaultValue: props.defaultOpen ?? false,
		get onChange() {
			return props.onOpenChange;
		},
	});

	createKeyboard({
		Escape: () => {
			if (open()) setOpen(false);
		},
	});

	createScrollLock(() => open());

	const ctxValue: ModalContextValue = {
		get open() {
			return open();
		},
		onOpenChange: (value: boolean) => setOpen(value),
	};

	return <ModalContext.Provider value={ctxValue}>{props.children}</ModalContext.Provider>;
}

function Portal(props: ModalPortalProps) {
	const ctx = useModalContext();

	return (
		<Show when={ctx.open}>
			<SolidPortal mount={props.container}>{props.children}</SolidPortal>
		</Show>
	);
}

function Overlay(props: ModalOverlayProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useModalContext();

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Content(props: ModalContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick', 'ref']);
	const ctx = useModalContext();
	let contentEl: HTMLDivElement | undefined;
	const mergedRef = createMergedRefs<HTMLDivElement>(
		(el) => (contentEl = el),
		(el) => (local.ref as ((el: HTMLDivElement) => void) | undefined)?.(el),
	);

	createFocusTrap(() => contentEl, {
		get active() {
			return ctx.open;
		},
	});

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		e.stopPropagation();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			ref={mergedRef}
			role='dialog'
			aria-modal='true'
			tabIndex={-1}
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Close(props: ModalCloseProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useModalContext();
	const state = createInteractiveState();
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			class={local.class}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

export const Modal = {
	Root,
	Portal,
	Overlay,
	Content,
	Close,
};

export { Root, Portal, Overlay, Content, Close };

// packages/react/src/components/modal/Modal.tsx
import React, { createContext, useContext, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useFocusTrap } from '@/hooks/use-focus-trap';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { useKeyboard } from '@/hooks/use-keyboard';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import { useScrollLock } from '@/hooks/use-scroll-lock';
import { mergeProps } from '@/utils/merge-props';
import type {
	ModalCloseProps,
	ModalContentProps,
	ModalContextValue,
	ModalOverlayProps,
	ModalPortalProps,
	ModalRootProps,
} from './Modal.types';

const ModalContext = createContext<ModalContextValue | null>(null);

function useModalContext() {
	const context = useContext(ModalContext);
	if (!context) {
		throw new globalThis.Error('Modal compound components must be used within Modal.Root');
	}
	return context;
}

const Root: React.FC<ModalRootProps> = ({ open: controlledOpen, defaultOpen = false, onOpenChange, children }) => {
	const [open, setOpen] = useControllableState({
		value: controlledOpen,
		defaultValue: defaultOpen,
		onChange: onOpenChange,
	});

	useKeyboard({
		Escape: () => {
			if (open) setOpen(false);
		},
	});

	useScrollLock(open);

	return (
		<ModalContext.Provider value={{ open, onOpenChange: setOpen as (value: boolean) => void }}>
			{children}
		</ModalContext.Provider>
	);
};

Root.displayName = 'Modal.Root';

const Portal: React.FC<ModalPortalProps> = ({ children, container }) => {
	const { open } = useModalContext();

	if (!open) return null;

	return createPortal(children, container || document.body);
};

Portal.displayName = 'Modal.Portal';

const Overlay = React.forwardRef<HTMLDivElement, ModalOverlayProps>(({ children, className, ...rest }, ref) => {
	const { open, onOpenChange } = useModalContext();

	return (
		<div
			ref={ref}
			className={className}
			data-state={open ? 'open' : 'closed'}
			onClick={() => onOpenChange(false)}
			{...rest}>
			{children}
		</div>
	);
});

Overlay.displayName = 'Modal.Overlay';

const Content = React.forwardRef<HTMLDivElement, ModalContentProps>(({ children, className, ...rest }, ref) => {
	const { open } = useModalContext();
	const internalRef = useRef<HTMLDivElement | null>(null);
	const mergedRef = useMergedRefs<HTMLDivElement>(internalRef, ref);

	useFocusTrap(internalRef, { active: open });

	return (
		<div
			ref={mergedRef}
			role='dialog'
			aria-modal='true'
			tabIndex={-1}
			className={className}
			data-state={open ? 'open' : 'closed'}
			onClick={(e) => e.stopPropagation()}
			{...rest}>
			{children}
		</div>
	);
});

Content.displayName = 'Modal.Content';

const Close = React.forwardRef<HTMLButtonElement, ModalCloseProps>(({ children, className, ...rest }, ref) => {
	const { onOpenChange } = useModalContext();
	const { handlers, dataAttributes } = useInteractiveState();

	const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

	return (
		<button
			ref={ref}
			type='button'
			className={className}
			{...dataAttributes}
			{...merged}
			onClick={(e) => {
				onOpenChange(false);
				(rest.onClick as ((e: React.MouseEvent<HTMLButtonElement>) => void) | undefined)?.(e);
			}}>
			{children}
		</button>
	);
});

Close.displayName = 'Modal.Close';

export const Modal = {
	Root,
	Portal,
	Overlay,
	Content,
	Close,
};
