// packages/solid/src/components/drawer/Drawer.tsx
import { createContext, createEffect, createSignal, onCleanup, Show, splitProps, useContext, type JSX } from 'solid-js';
import { Portal as SolidPortal } from 'solid-js/web';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	DrawerCloseProps,
	DrawerContentProps,
	DrawerContextValue,
	DrawerHeaderProps,
	DrawerOverlayProps,
	DrawerPortalProps,
	DrawerRootProps,
} from './Drawer.types';

const DrawerContext = createContext<DrawerContextValue | null>(null);

function useDrawerContext() {
	const context = useContext(DrawerContext);
	if (!context) {
		throw new Error('Drawer compound components must be used within Drawer.Root');
	}
	return context;
}

function Root(props: DrawerRootProps) {
	const [uncontrolledOpen, setUncontrolledOpen] = createSignal(props.defaultOpen ?? false);
	const isControlled = () => props.open !== undefined;
	const open = () => (isControlled() ? !!props.open : uncontrolledOpen());

	const handleOpenChange = (value: boolean) => {
		if (!isControlled()) setUncontrolledOpen(value);
		props.onOpenChange?.(value);
	};

	createEffect(() => {
		const handleEscape = (event: KeyboardEvent) => {
			if (event.key === 'Escape' && open()) {
				handleOpenChange(false);
			}
		};
		window.addEventListener('keydown', handleEscape);
		onCleanup(() => window.removeEventListener('keydown', handleEscape));
	});

	const ctxValue: DrawerContextValue = {
		get open() {
			return open();
		},
		onOpenChange: handleOpenChange,
	};

	return <DrawerContext.Provider value={ctxValue}>{props.children}</DrawerContext.Provider>;
}

function Portal(props: DrawerPortalProps) {
	const ctx = useDrawerContext();

	return (
		<Show when={ctx.open}>
			<SolidPortal mount={props.container}>{props.children}</SolidPortal>
		</Show>
	);
}

function Overlay(props: DrawerOverlayProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useDrawerContext();

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Content(props: DrawerContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useDrawerContext();

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		e.stopPropagation();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			role='dialog'
			aria-modal='true'
			class={local.class}
			data-state={ctx.open ? 'open' : 'closed'}
			onClick={handleClick}
			{...rest}>
			{local.children}
		</div>
	);
}

function Header(props: DrawerHeaderProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	return (
		<div
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

function Close(props: DrawerCloseProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const ctx = useDrawerContext();
	const state = createInteractiveState();
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.onOpenChange(false);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			class={local.class}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

export const Drawer = {
	Root,
	Portal,
	Overlay,
	Content,
	Header,
	Close,
};

// src/components/drawer/Drawer.tsx
import React, { createContext, useCallback, useContext, useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { useInteractiveState } from '@/hooks/use-interactive-state'
import { mergeProps } from '@/utils/merge-props'
import type {
	DrawerCloseProps,
	DrawerContentProps,
	DrawerContextValue,
	DrawerHeaderProps,
	DrawerOverlayProps,
	DrawerPortalProps,
	DrawerRootProps,
} from './Drawer.types'

const DrawerContext = createContext<DrawerContextValue | null>(null)

function useDrawerContext() {
	const context = useContext(DrawerContext)
	if (!context) {
		throw new globalThis.Error('Drawer compound components must be used within Drawer.Root')
	}
	return context
}

const Root: React.FC<DrawerRootProps> = ({
	open: controlledOpen,
	defaultOpen = false,
	onOpenChange,
	children,
}) => {
	const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen)
	const isControlled = controlledOpen !== undefined
	const open = isControlled ? controlledOpen : uncontrolledOpen

	const handleOpenChange = useCallback(
		(value: boolean) => {
			if (!isControlled) {
				setUncontrolledOpen(value)
			}
			onOpenChange?.(value)
		},
		[isControlled, onOpenChange],
	)

	useEffect(() => {
		const handleEscape = (event: KeyboardEvent) => {
			if (event.key === 'Escape' && open) {
				handleOpenChange(false)
			}
		}

		window.addEventListener('keydown', handleEscape)
		return () => window.removeEventListener('keydown', handleEscape)
	}, [open, handleOpenChange])

	return (
		<DrawerContext.Provider value={{ open, onOpenChange: handleOpenChange }}>
			{children}
		</DrawerContext.Provider>
	)
}

Root.displayName = 'Drawer.Root'

const Portal: React.FC<DrawerPortalProps> = ({ children, container }) => {
	const { open } = useDrawerContext()

	if (!open) return null

	return createPortal(children, container || document.body)
}

Portal.displayName = 'Drawer.Portal'

const Overlay = React.forwardRef<HTMLDivElement, DrawerOverlayProps>(
	({ children, className, ...rest }, ref) => {
		const { open, onOpenChange } = useDrawerContext()

		return (
			<div
				ref={ref}
				className={className}
				data-state={open ? 'open' : 'closed'}
				onClick={() => onOpenChange(false)}
				{...rest}
			>
				{children}
			</div>
		)
	},
)

Overlay.displayName = 'Drawer.Overlay'

const Content = React.forwardRef<HTMLDivElement, DrawerContentProps>(
	({ children, className, ...rest }, ref) => {
		const { open } = useDrawerContext()

		return (
			<div
				ref={ref}
				role="dialog"
				aria-modal="true"
				className={className}
				data-state={open ? 'open' : 'closed'}
				onClick={(e) => e.stopPropagation()}
				{...rest}
			>
				{children}
			</div>
		)
	},
)

Content.displayName = 'Drawer.Content'

const Header = React.forwardRef<HTMLDivElement, DrawerHeaderProps>(
	({ children, className, ...rest }, ref) => {
		return (
			<div ref={ref} className={className} {...rest}>
				{children}
			</div>
		)
	},
)

Header.displayName = 'Drawer.Header'

const Close = React.forwardRef<HTMLButtonElement, DrawerCloseProps>(
	({ children, className, ...rest }, ref) => {
		const { onOpenChange } = useDrawerContext()
		const { handlers, dataAttributes } = useInteractiveState()

		const merged = mergeProps(
			rest as Record<string, unknown>,
			handlers as Record<string, unknown>,
		)

		return (
			<button
				ref={ref}
				type="button"
				className={className}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					onOpenChange(false)
					;(
						rest.onClick as
							| ((e: React.MouseEvent<HTMLButtonElement>) => void)
							| undefined
					)?.(e)
				}}
			>
				{children}
			</button>
		)
	},
)

Close.displayName = 'Drawer.Close'

export const Drawer = {
	Root,
	Portal,
	Overlay,
	Content,
	Header,
	Close,
}
