// packages/react/src/context/wire-ui-provider.tsx
'use client';

import React, { useContext, useMemo } from 'react';
import { defaultMessages, mergeMessages, type PartialMessages } from '@/utils/i18n/messages';
import { DEFAULT_LOCALE, WireUIContext, type WireUIContextValue } from './wire-ui-context';

export interface WireUIProviderProps {
	/**
	 * BCP 47 locale tag propagated to Calendar, DatePicker, NumberInput, Timeago
	 * and any other locale-aware component. Defaults to `en-US`. When nested, a
	 * child provider that omits `locale` inherits the parent's.
	 */
	locale?: string;
	/**
	 * Partial overrides for the built-in (English) strings. Merged per-namespace
	 * over the defaults, and over any parent provider's overrides when nested.
	 */
	messages?: PartialMessages;
	children?: React.ReactNode;
}

/**
 * Provides a locale and translatable strings to Wire UI components. Optional —
 * components fall back to `en-US` and their English defaults without it.
 *
 * @example
 * <WireUIProvider locale="de-DE" messages={{ calendar: { nextMonth: 'Nächster Monat' } }}>
 *   <App />
 * </WireUIProvider>
 */
export function WireUIProvider({ locale, messages, children }: WireUIProviderProps) {
	const parent = useContext(WireUIContext);

	const value = useMemo<WireUIContextValue>(() => {
		const base = parent?.messages ?? defaultMessages;
		return {
			locale: locale ?? parent?.locale ?? DEFAULT_LOCALE,
			messages: mergeMessages(base, messages),
		};
	}, [parent, locale, messages]);

	return <WireUIContext.Provider value={value}>{children}</WireUIContext.Provider>;
}
WireUIProvider.displayName = 'WireUIProvider';

// packages/vue/src/context/WireUIProvider.vue
<script setup lang="ts">
import { computed, inject, provide } from 'vue'
import { defaultMessages, mergeMessages, type PartialMessages } from '@/utils/i18n/messages'
import { DEFAULT_LOCALE, WireUIContextKey, type WireUIContextValue } from './wire-ui-context'

defineOptions({ name: 'WireUIProvider', inheritAttrs: false })

const props = defineProps<{
	/**
	 * BCP 47 locale tag propagated to Calendar, DatePicker, NumberInput, Timeago
	 * and any other locale-aware component. Defaults to `en-US`. When nested, a
	 * child provider that omits `locale` inherits the parent's.
	 */
	locale?: string
	/**
	 * Partial overrides for the built-in (English) strings. Merged per-namespace
	 * over the defaults, and over any parent provider's overrides when nested.
	 */
	messages?: PartialMessages
}>()

// A parent provider, if any — child inherits its locale and layers messages.
const parent = inject(WireUIContextKey, null)

const locale = computed(() => props.locale ?? parent?.locale.value ?? DEFAULT_LOCALE)
const messages = computed(() => mergeMessages(parent?.messages.value ?? defaultMessages, props.messages))

provide(WireUIContextKey, { locale, messages } satisfies WireUIContextValue)
</script>

<template>
	<slot />
</template>
