// packages/react/src/components/skeleton/Skeleton.tsx
import React from 'react';
import type { SkeletonProps } from './Skeleton.types';

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
	({ loading = true, className, children, 'aria-label': ariaLabel = 'Loading', ...rest }, ref) => {
		if (!loading) return <>{children}</>;

		return (
			<div
				ref={ref}
				role='status'
				aria-busy='true'
				aria-live='polite'
				aria-label={ariaLabel}
				className={className}
				data-loading=''
				{...rest}
			/>
		);
	},
);
Skeleton.displayName = 'Skeleton';

export { Skeleton };

// packages/solid/src/components/skeleton/Skeleton.tsx
import { Show, splitProps } from 'solid-js';
import type { SkeletonProps } from './Skeleton.types';

function Skeleton(props: SkeletonProps) {
	const [local, rest] = splitProps(props, ['loading', 'class', 'children', 'aria-label']);
	const loading = () => local.loading ?? true;
	const ariaLabel = () => local['aria-label'] ?? 'Loading';

	return (
		<Show
			when={loading()}
			fallback={local.children}>
			<div
				role='status'
				aria-busy='true'
				aria-live='polite'
				aria-label={ariaLabel()}
				class={local.class}
				data-loading=''
				{...rest}
			/>
		</Show>
	);
}

export { Skeleton };
