// src/components/accordion/Accordion.tsx
import React, { createContext, useCallback, useContext, useState } from 'react'
import { useInteractiveState } from '@/hooks/use-interactive-state'
import { mergeProps } from '@/utils/merge-props'
import type {
	AccordionContextValue,
	AccordionContentProps,
	AccordionItemContextValue,
	AccordionItemProps,
	AccordionRootProps,
	AccordionTriggerProps,
} from './Accordion.types'

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const AccordionContext = createContext<AccordionContextValue | null>(null)
const AccordionItemContext = createContext<AccordionItemContextValue | null>(null)

function useAccordionContext() {
	const ctx = useContext(AccordionContext)
	if (!ctx)
		throw new globalThis.Error('Accordion sub-components must be used within Accordion.Root')
	return ctx
}

function useAccordionItemContext() {
	const ctx = useContext(AccordionItemContext)
	if (!ctx)
		throw new globalThis.Error('Accordion.Trigger/Content must be used within Accordion.Item')
	return ctx
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, AccordionRootProps>(
	({ disabled = false, className, children, ...rest }, ref) => {
		// ── Single ──────────────────────────────────────────────────────────────
		if (rest.type === 'single') {
			const {
				type: _type,
				value: controlledValue,
				defaultValue,
				onChange,
				collapsible = false,
				...divRest
			} = rest

			// eslint-disable-next-line react-hooks/rules-of-hooks
			const [uncontrolledValue, setUncontrolledValue] = useState<string>(defaultValue ?? '')
			const isControlled = controlledValue !== undefined
			const openValue = isControlled ? controlledValue : uncontrolledValue

			// eslint-disable-next-line react-hooks/rules-of-hooks
			const isOpen = useCallback((v: string) => openValue === v, [openValue])

			// eslint-disable-next-line react-hooks/rules-of-hooks
			const toggle = useCallback(
				(v: string) => {
					const next = openValue === v ? (collapsible ? '' : openValue) : v
					if (!isControlled) setUncontrolledValue(next)
					onChange?.(next)
				},
				[openValue, collapsible, isControlled, onChange],
			)

			return (
				<AccordionContext.Provider value={{ isOpen, toggle, disabled }}>
					<div ref={ref} className={className} {...divRest}>
						{children}
					</div>
				</AccordionContext.Provider>
			)
		}

		// ── Multiple ─────────────────────────────────────────────────────────────
		const { type: _type, value: controlledValue, defaultValue, onChange, ...divRest } = rest

		// eslint-disable-next-line react-hooks/rules-of-hooks
		const [uncontrolledValues, setUncontrolledValues] = useState<string[]>(defaultValue ?? [])
		const isControlled = controlledValue !== undefined
		const openValues = isControlled ? controlledValue : uncontrolledValues

		// eslint-disable-next-line react-hooks/rules-of-hooks
		const isOpen = useCallback((v: string) => openValues.includes(v), [openValues])

		// eslint-disable-next-line react-hooks/rules-of-hooks
		const toggle = useCallback(
			(v: string) => {
				const next = openValues.includes(v)
					? openValues.filter((x) => x !== v)
					: [...openValues, v]
				if (!isControlled) setUncontrolledValues(next)
				onChange?.(next)
			},
			[openValues, isControlled, onChange],
		)

		return (
			<AccordionContext.Provider value={{ isOpen, toggle, disabled }}>
				<div ref={ref} className={className} {...divRest}>
					{children}
				</div>
			</AccordionContext.Provider>
		)
	},
)

Root.displayName = 'Accordion.Root'

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

const Item = React.forwardRef<HTMLDivElement, AccordionItemProps>(
	({ value, disabled = false, className, children, ...rest }, ref) => {
		const ctx = useAccordionContext()
		const isDisabled = disabled || ctx.disabled
		const isOpen = ctx.isOpen(value)

		return (
			<AccordionItemContext.Provider value={{ value, isOpen, disabled: isDisabled }}>
				<div
					ref={ref}
					className={className}
					data-state={isOpen ? 'open' : 'closed'}
					data-disabled={isDisabled ? '' : undefined}
					{...rest}
				>
					{children}
				</div>
			</AccordionItemContext.Provider>
		)
	},
)

Item.displayName = 'Accordion.Item'

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

const Trigger = React.forwardRef<HTMLButtonElement, AccordionTriggerProps>(
	({ children, className, onClick, ...rest }, ref) => {
		const { isOpen, disabled, value } = useAccordionItemContext()
		const { toggle } = useAccordionContext()
		const { handlers, dataAttributes } = useInteractiveState({ disabled })

		const merged = mergeProps(
			rest as Record<string, unknown>,
			handlers as Record<string, unknown>,
		)

		return (
			<button
				ref={ref}
				type="button"
				disabled={disabled}
				aria-expanded={isOpen}
				data-state={isOpen ? 'open' : 'closed'}
				data-disabled={disabled ? '' : undefined}
				className={className}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					toggle(value)
					onClick?.(e)
				}}
			>
				{children}
			</button>
		)
	},
)

Trigger.displayName = 'Accordion.Trigger'

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLDivElement, AccordionContentProps>(
	({ forceMount = false, children, className, ...rest }, ref) => {
		const { isOpen } = useAccordionItemContext()

		if (!forceMount && !isOpen) return null

		return (
			<div
				ref={ref}
				role="region"
				hidden={forceMount && !isOpen ? true : undefined}
				className={className}
				data-state={isOpen ? 'open' : 'closed'}
				{...rest}
			>
				{children}
			</div>
		)
	},
)

Content.displayName = 'Accordion.Content'

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Accordion = {
	Root,
	Item,
	Trigger,
	Content,
}

// packages/solid/src/components/accordion/Accordion.tsx
import { createContext, createSignal, useContext, splitProps, Show, type JSX } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	AccordionContextValue,
	AccordionContentProps,
	AccordionItemContextValue,
	AccordionItemProps,
	AccordionRootProps,
	AccordionTriggerProps,
} from './Accordion.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const AccordionContext = createContext<AccordionContextValue | null>(null);
const AccordionItemContext = createContext<AccordionItemContextValue | null>(null);

function useAccordionContext() {
	const ctx = useContext(AccordionContext);
	if (!ctx) throw new Error('Accordion sub-components must be used within Accordion.Root');
	return ctx;
}

function useAccordionItemContext() {
	const ctx = useContext(AccordionItemContext);
	if (!ctx) throw new Error('Accordion.Trigger/Content must be used within Accordion.Item');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: AccordionRootProps) {
	// Cast to widen the discriminated union for splitProps — `collapsible` only
	// exists on the single variant but is harmless to split on either.
	const [local, rest] = splitProps(props as AccordionRootProps & { collapsible?: boolean }, [
		'type',
		'value',
		'defaultValue',
		'onChange',
		'disabled',
		'collapsible',
		'class',
		'children',
	]);

	// Normalize defaultValue → string[] for unified internal storage.
	const initialValues = (): string[] => {
		const dv = local.defaultValue;
		if (local.type === 'single') {
			return dv ? [dv as string] : [];
		}
		return ((dv as string[] | undefined) ?? []).slice();
	};

	const [uncontrolled, setUncontrolled] = createSignal<string[]>(initialValues());

	const isControlled = () => local.value !== undefined;

	const openValues = (): string[] => {
		if (!isControlled()) return uncontrolled();
		const v = local.value;
		if (local.type === 'single') return v ? [v as string] : [];
		return (v as string[]) ?? [];
	};

	const isOpen = (v: string) => openValues().includes(v);

	const toggle = (v: string) => {
		const current = openValues();

		if (local.type === 'single') {
			const collapsible = !!local.collapsible;
			const isCurrent = current[0] === v;
			let next: string[];
			if (isCurrent) {
				next = collapsible ? [] : current.length ? [current[0]] : [];
			} else {
				next = [v];
			}
			if (!isControlled()) setUncontrolled(next);
			(local.onChange as ((value: string) => void) | undefined)?.(next[0] ?? '');
		} else {
			const next = current.includes(v) ? current.filter((x) => x !== v) : [...current, v];
			if (!isControlled()) setUncontrolled(next);
			(local.onChange as ((value: string[]) => void) | undefined)?.(next);
		}
	};

	const ctxValue: AccordionContextValue = {
		isOpen,
		toggle,
		get disabled() {
			return local.disabled ?? false;
		},
	};

	return (
		<AccordionContext.Provider value={ctxValue}>
			<div
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</AccordionContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Item
// ---------------------------------------------------------------------------

function Item(props: AccordionItemProps) {
	const [local, rest] = splitProps(props, ['value', 'disabled', 'class', 'children']);
	const ctx = useAccordionContext();

	const isItemDisabled = () => !!local.disabled || ctx.disabled;
	const isItemOpen = () => ctx.isOpen(local.value);

	const itemCtxValue: AccordionItemContextValue = {
		get value() {
			return local.value;
		},
		get isOpen() {
			return isItemOpen();
		},
		get disabled() {
			return isItemDisabled();
		},
	};

	return (
		<AccordionItemContext.Provider value={itemCtxValue}>
			<div
				class={local.class}
				data-state={isItemOpen() ? 'open' : 'closed'}
				data-disabled={isItemDisabled() ? '' : undefined}
				{...rest}>
				{local.children}
			</div>
		</AccordionItemContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Trigger
// ---------------------------------------------------------------------------

function Trigger(props: AccordionTriggerProps) {
	const [local, rest] = splitProps(props, ['children', 'class', 'onClick']);
	const itemCtx = useAccordionItemContext();
	const rootCtx = useAccordionContext();

	const state = createInteractiveState({
		get disabled() {
			return itemCtx.disabled;
		},
	});

	// Compose consumer-provided handlers (in `rest`) with the interactive-state
	// handlers — both fire when an event triggers (consumer first, then ours).
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		rootCtx.toggle(itemCtx.value);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			disabled={itemCtx.disabled}
			aria-expanded={itemCtx.isOpen}
			data-state={itemCtx.isOpen ? 'open' : 'closed'}
			data-disabled={itemCtx.disabled ? '' : undefined}
			class={local.class}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

function Content(props: AccordionContentProps) {
	const [local, rest] = splitProps(props, ['forceMount', 'class', 'children']);
	const itemCtx = useAccordionItemContext();

	return (
		<Show when={itemCtx.isOpen || local.forceMount}>
			<div
				role='region'
				hidden={local.forceMount && !itemCtx.isOpen ? true : undefined}
				class={local.class}
				data-state={itemCtx.isOpen ? 'open' : 'closed'}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Accordion = {
	Root,
	Item,
	Trigger,
	Content,
};
