// packages/react/src/components/spinner/Spinner.tsx
import React from 'react';
import type { SpinnerProps } from './Spinner.types';

const Spinner = React.forwardRef<HTMLSpanElement, SpinnerProps>(
	({ label = 'Loading', decorative = true, className, children, ...rest }, ref) => (
		<span
			ref={ref}
			role='status'
			aria-live='polite'
			aria-label={label}
			className={className}
			{...rest}>
			<span aria-hidden={decorative ? 'true' : undefined}>{children}</span>
			<span style={visuallyHidden}>{label}</span>
		</span>
	),
);
Spinner.displayName = 'Spinner';

const visuallyHidden: React.CSSProperties = {
	position: 'absolute',
	width: 1,
	height: 1,
	padding: 0,
	margin: -1,
	overflow: 'hidden',
	clip: 'rect(0,0,0,0)',
	whiteSpace: 'nowrap',
	borderWidth: 0,
};

export { Spinner };

// packages/vue/src/components/spinner/Spinner.vue
<script setup lang="ts">
defineOptions({ name: 'Spinner' })

withDefaults(
	defineProps<{
		label?: string
		decorative?: boolean
	}>(),
	{
		label: 'Loading',
		decorative: true,
	},
)

const visuallyHidden = {
	position: 'absolute' as const,
	width: '1px',
	height: '1px',
	padding: 0,
	margin: '-1px',
	overflow: 'hidden',
	clip: 'rect(0,0,0,0)',
	whiteSpace: 'nowrap' as const,
	borderWidth: 0,
}
</script>

<template>
	<span
		role="status"
		aria-live="polite"
		:aria-label="label">
		<span :aria-hidden="decorative ? 'true' : undefined">
			<slot />
		</span>
		<span :style="visuallyHidden">{{ label }}</span>
	</span>
</template>
