// packages/react/src/components/search/Search.tsx
import React, { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react';
import { useClickOutside } from '@/hooks/use-click-outside';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useDebouncedCallback } from '@/hooks/use-debounce';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import { mergeProps } from '@/utils/merge-props';
import type {
	SearchContentProps,
	SearchContextValue,
	SearchEmptyProps,
	SearchInputProps,
	SearchItemProps,
	SearchOption,
	SearchRootProps,
} from './Search.types';

const SearchContext = createContext<SearchContextValue | null>(null);

function useSearchContext() {
	const context = useContext(SearchContext);
	if (!context) {
		throw new globalThis.Error('Search compound components must be used within Search.Root');
	}
	return context;
}

const Root = React.forwardRef<HTMLDivElement, SearchRootProps>(
	(
		{
			open: controlledOpen,
			defaultOpen = false,
			onOpenChange,
			value: controlledValue,
			defaultSearchValue = '',
			onSearchChange,
			onSelect,
			onSubmitSearch,
			loading = false,
			searchDelay = 1000,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [open, setOpenState] = useControllableState({
			value: controlledOpen,
			defaultValue: defaultOpen,
			onChange: onOpenChange,
		});

		const [searchValue, setSearchValueState] = useControllableState({
			value: controlledValue,
			defaultValue: defaultSearchValue,
			onChange: onSearchChange,
		});

		const [highlightedIndex, setHighlightedIndex] = useState(-1);
		const [itemCount, setItemCount] = useState(0);
		const inputRef = useRef<HTMLInputElement>(null);
		const rootRef = useRef<HTMLDivElement>(null);
		const mergedRootRef = useMergedRefs<HTMLDivElement>(rootRef, ref);

		const submitSearch = useDebouncedCallback(() => onSubmitSearch?.(), searchDelay);

		const handleOpenChange = useCallback(
			(value: boolean) => {
				setOpenState(value);
				if (!value) {
					setHighlightedIndex(-1);
				}
			},
			[setOpenState],
		);

		const handleSearchChange = useCallback(
			(value: string) => {
				setSearchValueState(value);
				submitSearch();
			},
			[setSearchValueState, submitSearch],
		);

		const handleSelect = useCallback(
			(option: SearchOption) => {
				onSelect?.(option);
				setSearchValueState('');
				handleOpenChange(false);
			},
			[onSelect, setSearchValueState, handleOpenChange],
		);

		const registerItem = useCallback(() => {
			const index = itemCount;
			setItemCount((prev) => prev + 1);
			return index;
		}, [itemCount]);

		const unregisterItem = useCallback(() => {
			setItemCount((prev) => Math.max(0, prev - 1));
		}, []);

		useClickOutside(rootRef, () => {
			if (open) {
				handleOpenChange(false);
			}
		});

		const contextValue: SearchContextValue = {
			open,
			onOpenChange: handleOpenChange,
			searchValue,
			onSearchChange: handleSearchChange,
			onSelect: handleSelect,
			loading,
			highlightedIndex,
			setHighlightedIndex,
			itemCount,
			registerItem,
			unregisterItem,
			inputRef,
		};

		return (
			<SearchContext.Provider value={contextValue}>
				<div
					ref={mergedRootRef}
					className={className}
					data-loading={loading ? '' : undefined}
					{...rest}>
					{children}
				</div>
			</SearchContext.Provider>
		);
	},
);

Root.displayName = 'Search.Root';

const Input = React.forwardRef<HTMLInputElement, SearchInputProps>(({ className, ...rest }, ref) => {
	const ctx = useSearchContext();

	const mergedInputRef = useMergedRefs<HTMLInputElement>(ctx.inputRef, ref);

	const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
		switch (e.key) {
			case 'ArrowDown':
				e.preventDefault();
				if (ctx.itemCount > 0) {
					ctx.setHighlightedIndex(ctx.highlightedIndex < ctx.itemCount - 1 ? ctx.highlightedIndex + 1 : 0);
				}
				break;
			case 'ArrowUp':
				e.preventDefault();
				if (ctx.itemCount > 0) {
					ctx.setHighlightedIndex(ctx.highlightedIndex > 0 ? ctx.highlightedIndex - 1 : ctx.itemCount - 1);
				}
				break;
			case 'Escape':
				ctx.onOpenChange(false);
				ctx.inputRef.current?.blur();
				break;
		}
	};

	return (
		<input
			ref={mergedInputRef}
			type='text'
			value={ctx.searchValue}
			className={className}
			onFocus={() => ctx.onOpenChange(true)}
			onChange={(e) => ctx.onSearchChange(e.target.value)}
			onKeyDown={handleKeyDown}
			{...rest}
		/>
	);
});

Input.displayName = 'Search.Input';

const Content = React.forwardRef<HTMLDivElement, SearchContentProps>(({ children, className, ...rest }, ref) => {
	const { open } = useSearchContext();

	if (!open) return null;

	return (
		<div
			ref={ref}
			role='listbox'
			className={className}
			data-state={open ? 'open' : 'closed'}
			{...rest}>
			{children}
		</div>
	);
});

Content.displayName = 'Search.Content';

const Item = React.forwardRef<HTMLDivElement, SearchItemProps>(({ option, children, className, ...rest }, ref) => {
	const ctx = useSearchContext();
	const indexRef = useRef(-1);
	const { handlers, dataAttributes } = useInteractiveState();

	useEffect(() => {
		indexRef.current = ctx.registerItem();
		return () => ctx.unregisterItem();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	const isHighlighted = ctx.highlightedIndex === indexRef.current;

	const handleKeyDown = (e: React.KeyboardEvent) => {
		handlers.onKeyDown(e);
		if (e.key === 'Enter') {
			ctx.onSelect(option);
		}
	};

	const merged = mergeProps(
		rest as Record<string, unknown>,
		{
			...handlers,
			onKeyDown: handleKeyDown,
		} as Record<string, unknown>,
	);

	return (
		<div
			ref={ref}
			role='option'
			aria-selected={isHighlighted}
			className={className}
			data-highlighted={isHighlighted ? '' : undefined}
			{...dataAttributes}
			{...merged}
			onClick={(e) => {
				ctx.onSelect(option);
				(rest.onClick as ((e: React.MouseEvent<HTMLDivElement>) => void) | undefined)?.(e);
			}}
			tabIndex={-1}>
			{children}
		</div>
	);
});

Item.displayName = 'Search.Item';

const Empty = React.forwardRef<HTMLDivElement, SearchEmptyProps>(({ children, className, ...rest }, ref) => {
	const { itemCount, loading } = useSearchContext();

	if (itemCount > 0 || loading) return null;

	return (
		<div
			ref={ref}
			className={className}
			{...rest}>
			{children}
		</div>
	);
});

Empty.displayName = 'Search.Empty';

export const Search = {
	Root,
	Input,
	Content,
	Item,
	Empty,
};

// packages/solid/src/components/search/Search.tsx
import { createContext, createSignal, onCleanup, onMount, Show, splitProps, useContext, type JSX } from 'solid-js';
import { createClickOutside } from '@/primitives/create-click-outside';
import { createControllableState } from '@/primitives/create-controllable-state';
import { createDebouncedCallback } from '@/primitives/create-debounce';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { createMergedRefs } from '@/primitives/create-merged-refs';
import { mergeProps } from '@/utils/merge-props';
import type {
	SearchContentProps,
	SearchContextValue,
	SearchEmptyProps,
	SearchInputProps,
	SearchItemProps,
	SearchOption,
	SearchRootProps,
} from './Search.types';

const SearchContext = createContext<SearchContextValue | null>(null);

function useSearchContext() {
	const context = useContext(SearchContext);
	if (!context) {
		throw new Error('Search compound components must be used within Search.Root');
	}
	return context;
}

function Root(props: SearchRootProps) {
	const [local, rest] = splitProps(props, [
		'open',
		'defaultOpen',
		'onOpenChange',
		'value',
		'defaultSearchValue',
		'onSearchChange',
		'onSelect',
		'onSubmitSearch',
		'loading',
		'searchDelay',
		'children',
		'class',
		'ref',
	]);

	const [open, setOpenState] = createControllableState<boolean>({
		get value() {
			return local.open;
		},
		defaultValue: local.defaultOpen ?? false,
	});

	const [searchValue, setSearchValueState] = createControllableState<string>({
		get value() {
			return local.value;
		},
		defaultValue: local.defaultSearchValue ?? '',
	});

	const [highlightedIndex, setHighlightedIndex] = createSignal(-1);
	const [itemCount, setItemCount] = createSignal(0);
	let inputNode: HTMLInputElement | null = null;
	let rootEl: HTMLDivElement | undefined;
	const mergedRef = createMergedRefs<HTMLDivElement>(
		(el) => (rootEl = el),
		local.ref as ((el: HTMLDivElement) => void) | undefined,
	);

	const submitDebounced = createDebouncedCallback(() => local.onSubmitSearch?.(), local.searchDelay ?? 1000);

	const handleOpenChange = (value: boolean) => {
		setOpenState(value);
		local.onOpenChange?.(value);
		if (!value) setHighlightedIndex(-1);
	};

	const handleSearchChange = (value: string) => {
		setSearchValueState(value);
		local.onSearchChange?.(value);
		submitDebounced();
	};

	const handleSelect = (option: SearchOption) => {
		local.onSelect?.(option);
		setSearchValueState('');
		local.onSearchChange?.('');
		handleOpenChange(false);
	};

	const registerItem = () => {
		const index = itemCount();
		setItemCount((prev) => prev + 1);
		return index;
	};

	const unregisterItem = () => {
		setItemCount((prev) => Math.max(0, prev - 1));
	};

	createClickOutside(
		() => rootEl,
		() => {
			if (open()) handleOpenChange(false);
		},
	);

	const ctxValue: SearchContextValue = {
		get open() {
			return !!open();
		},
		onOpenChange: handleOpenChange,
		get searchValue() {
			return searchValue() ?? '';
		},
		onSearchChange: handleSearchChange,
		onSelect: handleSelect,
		get loading() {
			return !!local.loading;
		},
		get highlightedIndex() {
			return highlightedIndex();
		},
		setHighlightedIndex,
		get itemCount() {
			return itemCount();
		},
		registerItem,
		unregisterItem,
		getInputNode: () => inputNode,
		setInputNode: (node) => {
			inputNode = node;
		},
	};

	return (
		<SearchContext.Provider value={ctxValue}>
			<div
				ref={mergedRef}
				class={local.class}
				data-loading={local.loading ? '' : undefined}
				{...rest}>
				{local.children}
			</div>
		</SearchContext.Provider>
	);
}

function Input(props: SearchInputProps) {
	const [local, rest] = splitProps(props, ['class']);
	const ctx = useSearchContext();

	const handleKeyDown: JSX.EventHandler<HTMLInputElement, KeyboardEvent> = (e) => {
		switch (e.key) {
			case 'ArrowDown':
				e.preventDefault();
				if (ctx.itemCount > 0) {
					ctx.setHighlightedIndex(ctx.highlightedIndex < ctx.itemCount - 1 ? ctx.highlightedIndex + 1 : 0);
				}
				break;
			case 'ArrowUp':
				e.preventDefault();
				if (ctx.itemCount > 0) {
					ctx.setHighlightedIndex(ctx.highlightedIndex > 0 ? ctx.highlightedIndex - 1 : ctx.itemCount - 1);
				}
				break;
			case 'Escape':
				ctx.onOpenChange(false);
				ctx.getInputNode()?.blur();
				break;
		}
	};

	return (
		<input
			ref={(el) => ctx.setInputNode(el)}
			type='text'
			value={ctx.searchValue}
			class={local.class}
			onFocus={() => ctx.onOpenChange(true)}
			onInput={(e) => ctx.onSearchChange(e.currentTarget.value)}
			onKeyDown={handleKeyDown}
			{...rest}
		/>
	);
}

function Content(props: SearchContentProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useSearchContext();

	return (
		<Show when={ctx.open}>
			<div
				role='listbox'
				class={local.class}
				data-state='open'
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

function Item(props: SearchItemProps) {
	const [local, rest] = splitProps(props, ['option', 'children', 'class', 'onClick']);
	const ctx = useSearchContext();
	const state = createInteractiveState();

	let myIndex = -1;
	onMount(() => {
		myIndex = ctx.registerItem();
		onCleanup(() => ctx.unregisterItem());
	});

	const isHighlighted = () => ctx.highlightedIndex === myIndex;

	const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (e) => {
		(state.handlers.onKeyDown as (event: KeyboardEvent) => void)(e);
		if (e.key === 'Enter') {
			ctx.onSelect(local.option);
		}
	};

	const merged = mergeProps(rest, {
		...state.handlers,
		onKeyDown: handleKeyDown,
	});

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		ctx.onSelect(local.option);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<div
			role='option'
			aria-selected={isHighlighted()}
			class={local.class}
			data-highlighted={isHighlighted() ? '' : undefined}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}
			tabIndex={-1}>
			{local.children}
		</div>
	);
}

function Empty(props: SearchEmptyProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useSearchContext();

	return (
		<Show when={ctx.itemCount === 0 && !ctx.loading}>
			<div
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</Show>
	);
}

export const Search = {
	Root,
	Input,
	Content,
	Item,
	Empty,
};
