// packages/react/src/components/spinner/Spinner.tsx
import React from 'react';
import type { SpinnerProps } from './Spinner.types';

const Spinner = React.forwardRef<HTMLSpanElement, SpinnerProps>(
	({ label = 'Loading', decorative = true, className, children, ...rest }, ref) => (
		<span
			ref={ref}
			role='status'
			aria-live='polite'
			aria-label={label}
			className={className}
			{...rest}>
			<span aria-hidden={decorative ? 'true' : undefined}>{children}</span>
			<span style={visuallyHidden}>{label}</span>
		</span>
	),
);
Spinner.displayName = 'Spinner';

const visuallyHidden: React.CSSProperties = {
	position: 'absolute',
	width: 1,
	height: 1,
	padding: 0,
	margin: -1,
	overflow: 'hidden',
	clip: 'rect(0,0,0,0)',
	whiteSpace: 'nowrap',
	borderWidth: 0,
};

export { Spinner };

// packages/solid/src/components/spinner/Spinner.tsx
import { splitProps, type JSX } from 'solid-js';
import type { SpinnerProps } from './Spinner.types';

const visuallyHidden: JSX.CSSProperties = {
	position: 'absolute',
	width: '1px',
	height: '1px',
	padding: 0,
	margin: '-1px',
	overflow: 'hidden',
	clip: 'rect(0,0,0,0)',
	'white-space': 'nowrap',
	'border-width': 0,
};

function Spinner(props: SpinnerProps) {
	const [local, rest] = splitProps(props, ['label', 'decorative', 'class', 'children']);
	const label = () => local.label ?? 'Loading';
	const decorative = () => local.decorative ?? true;

	return (
		<span
			role='status'
			aria-live='polite'
			aria-label={label()}
			class={local.class}
			{...rest}>
			<span aria-hidden={decorative() ? 'true' : undefined}>{local.children}</span>
			<span style={visuallyHidden}>{label()}</span>
		</span>
	);
}

export { Spinner };
