// packages/react/src/components/aspect-ratio/AspectRatio.tsx
import React from 'react';
import type { AspectRatioProps } from './AspectRatio.types';

const AspectRatio = React.forwardRef<HTMLDivElement, AspectRatioProps>(
	({ ratio = 1, children, style, className, ...rest }, ref) => {
		return (
			<div
				ref={ref}
				className={className}
				data-ratio={ratio}
				style={{ position: 'relative', width: '100%', aspectRatio: String(ratio), ...style }}
				{...rest}>
				{children}
			</div>
		);
	},
);
AspectRatio.displayName = 'AspectRatio';

export { AspectRatio };

// packages/vue/src/components/aspect-ratio/AspectRatio.vue
<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ name: 'AspectRatio' })

const props = withDefaults(
	defineProps<{
		ratio?: number
	}>(),
	{
		ratio: 1,
	},
)

const wrapperStyle = computed(() => ({
	position: 'relative' as const,
	width: '100%',
	aspectRatio: String(props.ratio),
}))
</script>

<template>
	<div
		:data-ratio="ratio"
		:style="wrapperStyle">
		<slot />
	</div>
</template>
