// packages/react/src/components/empty-state/EmptyState.tsx
import React from 'react';
import type {
	EmptyStateActionsProps,
	EmptyStateDescriptionProps,
	EmptyStateMediaProps,
	EmptyStateRootProps,
	EmptyStateTitleProps,
} from './EmptyState.types';

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, EmptyStateRootProps>(({ className, children, ...rest }, ref) => (
	<div
		ref={ref}
		role='status'
		className={className}
		{...rest}>
		{children}
	</div>
));

Root.displayName = 'EmptyState.Root';

// ---------------------------------------------------------------------------
// Media (icon / illustration slot)
// ---------------------------------------------------------------------------

const Media = React.forwardRef<HTMLDivElement, EmptyStateMediaProps>(({ className, children, ...rest }, ref) => (
	<div
		ref={ref}
		aria-hidden='true'
		className={className}
		{...rest}>
		{children}
	</div>
));

Media.displayName = 'EmptyState.Media';

// ---------------------------------------------------------------------------
// Title
// ---------------------------------------------------------------------------

const Title = React.forwardRef<HTMLHeadingElement, EmptyStateTitleProps>(({ className, children, ...rest }, ref) => (
	<h3
		ref={ref}
		className={className}
		{...rest}>
		{children}
	</h3>
));

Title.displayName = 'EmptyState.Title';

// ---------------------------------------------------------------------------
// Description
// ---------------------------------------------------------------------------

const Description = React.forwardRef<HTMLParagraphElement, EmptyStateDescriptionProps>(
	({ className, children, ...rest }, ref) => (
		<p
			ref={ref}
			className={className}
			{...rest}>
			{children}
		</p>
	),
);

Description.displayName = 'EmptyState.Description';

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

const Actions = React.forwardRef<HTMLDivElement, EmptyStateActionsProps>(({ className, children, ...rest }, ref) => (
	<div
		ref={ref}
		className={className}
		{...rest}>
		{children}
	</div>
));

Actions.displayName = 'EmptyState.Actions';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const EmptyState = {
	Root,
	Media,
	Title,
	Description,
	Actions,
};

// packages/solid/src/components/empty-state/EmptyState.tsx
import { splitProps } from 'solid-js';
import type {
	EmptyStateActionsProps,
	EmptyStateDescriptionProps,
	EmptyStateMediaProps,
	EmptyStateRootProps,
	EmptyStateTitleProps,
} from './EmptyState.types';

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: EmptyStateRootProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	return (
		<div
			role='status'
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Media (icon / illustration slot)
// ---------------------------------------------------------------------------

function Media(props: EmptyStateMediaProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	return (
		<div
			aria-hidden='true'
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Title
// ---------------------------------------------------------------------------

function Title(props: EmptyStateTitleProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	return (
		<h3
			class={local.class}
			{...rest}>
			{local.children}
		</h3>
	);
}

// ---------------------------------------------------------------------------
// Description
// ---------------------------------------------------------------------------

function Description(props: EmptyStateDescriptionProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	return (
		<p
			class={local.class}
			{...rest}>
			{local.children}
		</p>
	);
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

function Actions(props: EmptyStateActionsProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	return (
		<div
			class={local.class}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const EmptyState = {
	Root,
	Media,
	Title,
	Description,
	Actions,
};
