// packages/solid/src/components/aspect-ratio/AspectRatio.tsx
import { splitProps, type JSX } from 'solid-js';
import type { AspectRatioProps } from './AspectRatio.types';

function AspectRatio(props: AspectRatioProps) {
	const [local, rest] = splitProps(props, ['ratio', 'children', 'style', 'class']);
	const ratio = () => local.ratio ?? 1;

	const mergedStyle = (): JSX.CSSProperties | string | undefined => {
		const ours: JSX.CSSProperties = { position: 'relative', width: '100%', 'aspect-ratio': String(ratio()) };
		const userStyle = local.style;
		if (typeof userStyle === 'string' || !userStyle) return ours;
		return { ...ours, ...(userStyle as JSX.CSSProperties) };
	};

	return (
		<div
			class={local.class}
			data-ratio={ratio()}
			style={mergedStyle()}
			{...rest}>
			{local.children}
		</div>
	);
}

export { AspectRatio };

// packages/react/src/components/aspect-ratio/AspectRatio.tsx
import React from 'react';
import type { AspectRatioProps } from './AspectRatio.types';

const AspectRatio = React.forwardRef<HTMLDivElement, AspectRatioProps>(
	({ ratio = 1, children, style, className, ...rest }, ref) => {
		return (
			<div
				ref={ref}
				className={className}
				data-ratio={ratio}
				style={{ position: 'relative', width: '100%', aspectRatio: String(ratio), ...style }}
				{...rest}>
				{children}
			</div>
		);
	},
);
AspectRatio.displayName = 'AspectRatio';

export { AspectRatio };
