// packages/react/src/components/carousel/Carousel.tsx
import React, { createContext, useCallback, useContext, useMemo, useRef, useState } from 'react';
import { useIsomorphicLayoutEffect } from '@/hooks/use-isomorphic-layout-effect';
import { useMergedRefs } from '@/hooks/use-merged-refs';
import type {
	CarouselContentProps,
	CarouselContextValue,
	CarouselIndicatorsProps,
	CarouselNextProps,
	CarouselPreviousProps,
	CarouselRootProps,
	CarouselSlideProps,
	CarouselViewportProps,
} from './Carousel.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CarouselContext = createContext<CarouselContextValue | null>(null);

function useCarouselContext() {
	const ctx = useContext(CarouselContext);
	if (!ctx) throw new globalThis.Error('Carousel sub-components must be used within Carousel.Root');
	return ctx;
}

function domOrder(a: HTMLElement, b: HTMLElement) {
	return a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, CarouselRootProps>(
	({ orientation = 'horizontal', loop = false, defaultIndex = 0, onIndexChange, className, children, ...rest }, ref) => {
		const vertical = orientation === 'vertical';
		const viewportRef = useRef<HTMLDivElement | null>(null);
		const slidesRef = useRef<HTMLElement[]>([]);
		const [count, setCount] = useState(0);
		const [current, setCurrent] = useState(defaultIndex);

		const onIndexChangeRef = useRef(onIndexChange);
		useIsomorphicLayoutEffect(() => {
			onIndexChangeRef.current = onIndexChange;
		});

		const setCurrentIndex = useCallback((index: number) => {
			setCurrent((prev) => {
				if (prev === index) return prev;
				onIndexChangeRef.current?.(index);
				return index;
			});
		}, []);

		const registerSlide = useCallback((el: HTMLElement) => {
			slidesRef.current.push(el);
			slidesRef.current.sort(domOrder);
			setCount(slidesRef.current.length);
			return () => {
				slidesRef.current = slidesRef.current.filter((e) => e !== el);
				setCount(slidesRef.current.length);
			};
		}, []);

		const offsetOf = useCallback(
			(el: HTMLElement) => {
				const vp = viewportRef.current;
				if (!vp) return 0;
				const vpRect = vp.getBoundingClientRect();
				const rect = el.getBoundingClientRect();
				return vertical ? rect.top - vpRect.top + vp.scrollTop : rect.left - vpRect.left + vp.scrollLeft;
			},
			[vertical],
		);

		const updateCurrent = useCallback(() => {
			const vp = viewportRef.current;
			if (!vp || slidesRef.current.length === 0) return;
			const scroll = vertical ? vp.scrollTop : vp.scrollLeft;
			let best = 0;
			let bestDist = Infinity;
			slidesRef.current.forEach((el, i) => {
				const dist = Math.abs(offsetOf(el) - scroll);
				if (dist < bestDist) {
					bestDist = dist;
					best = i;
				}
			});
			setCurrentIndex(best);
		}, [vertical, offsetOf, setCurrentIndex]);

		const scrollTo = useCallback(
			(index: number, behavior: ScrollBehavior = 'smooth') => {
				const clamped = Math.min(Math.max(index, 0), Math.max(slidesRef.current.length - 1, 0));
				setCurrentIndex(clamped);
				const vp = viewportRef.current;
				const el = slidesRef.current[clamped];
				if (!vp || !el) return;
				const target = offsetOf(el);
				if (typeof vp.scrollTo === 'function') {
					vp.scrollTo(vertical ? { top: target, behavior } : { left: target, behavior });
				} else if (vertical) {
					vp.scrollTop = target;
				} else {
					vp.scrollLeft = target;
				}
			},
			[vertical, offsetOf, setCurrentIndex],
		);

		const scrollNext = useCallback(() => {
			const next = current + 1;
			if (next < count) scrollTo(next);
			else if (loop) scrollTo(0);
		}, [current, count, loop, scrollTo]);

		const scrollPrev = useCallback(() => {
			const prev = current - 1;
			if (prev >= 0) scrollTo(prev);
			else if (loop) scrollTo(count - 1);
		}, [current, count, loop, scrollTo]);

		const ctx = useMemo<CarouselContextValue>(
			() => ({
				orientation,
				loop,
				count,
				current,
				canScrollPrev: loop ? count > 1 : current > 0,
				canScrollNext: loop ? count > 1 : current < count - 1,
				viewportRef,
				registerSlide,
				updateCurrent,
				scrollTo,
				scrollNext,
				scrollPrev,
			}),
			[orientation, loop, count, current, registerSlide, updateCurrent, scrollTo, scrollNext, scrollPrev],
		);

		return (
			<CarouselContext.Provider value={ctx}>
				<div
					ref={ref}
					role='region'
					aria-roledescription='carousel'
					className={className}
					data-orientation={orientation}
					{...rest}>
					{children}
				</div>
			</CarouselContext.Provider>
		);
	},
);

Root.displayName = 'Carousel.Root';

// ---------------------------------------------------------------------------
// Viewport
// ---------------------------------------------------------------------------

const Viewport = React.forwardRef<HTMLDivElement, CarouselViewportProps>(
	({ className, children, style, tabIndex, onScroll, onKeyDown, ...rest }, ref) => {
		const ctx = useCarouselContext();
		const mergedRef = useMergedRefs(ctx.viewportRef, ref);
		const vertical = ctx.orientation === 'vertical';

		return (
			<div
				ref={mergedRef}
				data-carousel-viewport=''
				// The viewport is a scrollable region; make it keyboard-focusable so
				// arrow-key navigation works and axe `scrollable-region-focusable` passes.
				tabIndex={tabIndex ?? 0}
				className={className}
				style={{
					overflowX: vertical ? 'hidden' : 'auto',
					overflowY: vertical ? 'auto' : 'hidden',
					scrollSnapType: `${vertical ? 'y' : 'x'} mandatory`,
					scrollbarWidth: 'none',
					...style,
				}}
				{...rest}
				onScroll={(e) => {
					ctx.updateCurrent();
					onScroll?.(e);
				}}
				onKeyDown={(e) => {
					onKeyDown?.(e);
					if (e.defaultPrevented) return;
					const nextKey = vertical ? 'ArrowDown' : 'ArrowRight';
					const prevKey = vertical ? 'ArrowUp' : 'ArrowLeft';
					if (e.key === nextKey) {
						e.preventDefault();
						ctx.scrollNext();
					} else if (e.key === prevKey) {
						e.preventDefault();
						ctx.scrollPrev();
					}
				}}>
				{children}
			</div>
		);
	},
);

Viewport.displayName = 'Carousel.Viewport';

// ---------------------------------------------------------------------------
// Content (track)
// ---------------------------------------------------------------------------

const Content = React.forwardRef<HTMLDivElement, CarouselContentProps>(({ className, children, style, ...rest }, ref) => {
	const ctx = useCarouselContext();
	return (
		<div
			ref={ref}
			data-carousel-content=''
			className={className}
			style={{ display: 'flex', flexDirection: ctx.orientation === 'vertical' ? 'column' : 'row', ...style }}
			{...rest}>
			{children}
		</div>
	);
});

Content.displayName = 'Carousel.Content';

// ---------------------------------------------------------------------------
// Slide
// ---------------------------------------------------------------------------

const Slide = React.forwardRef<HTMLDivElement, CarouselSlideProps>(({ className, children, style, ...rest }, ref) => {
	const ctx = useCarouselContext();
	const innerRef = useRef<HTMLDivElement | null>(null);
	const mergedRef = useMergedRefs(innerRef, ref);

	const { registerSlide } = ctx;
	useIsomorphicLayoutEffect(() => {
		const el = innerRef.current;
		if (!el) return;
		return registerSlide(el);
	}, [registerSlide]);

	return (
		<div
			ref={mergedRef}
			role='group'
			aria-roledescription='slide'
			data-carousel-slide=''
			className={className}
			style={{ scrollSnapAlign: 'start', flexShrink: 0, ...style }}
			{...rest}>
			{children}
		</div>
	);
});

Slide.displayName = 'Carousel.Slide';

// ---------------------------------------------------------------------------
// Previous / Next
// ---------------------------------------------------------------------------

const Previous = React.forwardRef<HTMLButtonElement, CarouselPreviousProps>(
	({ className, children, onClick, disabled, ...rest }, ref) => {
		const ctx = useCarouselContext();
		return (
			<button
				ref={ref}
				type='button'
				aria-label='Previous slide'
				disabled={disabled ?? !ctx.canScrollPrev}
				className={className}
				{...rest}
				onClick={(e) => {
					ctx.scrollPrev();
					onClick?.(e);
				}}>
				{children}
			</button>
		);
	},
);

Previous.displayName = 'Carousel.Previous';

const Next = React.forwardRef<HTMLButtonElement, CarouselNextProps>(
	({ className, children, onClick, disabled, ...rest }, ref) => {
		const ctx = useCarouselContext();
		return (
			<button
				ref={ref}
				type='button'
				aria-label='Next slide'
				disabled={disabled ?? !ctx.canScrollNext}
				className={className}
				{...rest}
				onClick={(e) => {
					ctx.scrollNext();
					onClick?.(e);
				}}>
				{children}
			</button>
		);
	},
);

Next.displayName = 'Carousel.Next';

// ---------------------------------------------------------------------------
// Indicators
// ---------------------------------------------------------------------------

const Indicators: React.FC<CarouselIndicatorsProps> = ({ children }) => {
	const ctx = useCarouselContext();
	return (
		<>
			{Array.from({ length: ctx.count }, (_, index) =>
				children({ index, selected: index === ctx.current, scrollTo: () => ctx.scrollTo(index) }),
			)}
		</>
	);
};

Indicators.displayName = 'Carousel.Indicators';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Carousel = {
	Root,
	Viewport,
	Content,
	Slide,
	Previous,
	Next,
	Indicators,
};

// Named exports expose the sub-components to Storybook's react-docgen (public API stays `Carousel.*`).
export { Root, Viewport, Content, Slide, Previous, Next, Indicators };

// packages/solid/src/components/carousel/Carousel.tsx
'use client';

import {
	createContext,
	createSignal,
	onCleanup,
	splitProps,
	useContext,
	For,
	type JSX,
} from 'solid-js';
import { createMergedRefs } from '@/primitives/create-merged-refs';
import type {
	CarouselContentProps,
	CarouselContextValue,
	CarouselIndicatorsProps,
	CarouselNextProps,
	CarouselPreviousProps,
	CarouselRootProps,
	CarouselSlideProps,
	CarouselViewportProps,
} from './Carousel.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const CarouselContext = createContext<CarouselContextValue | null>(null);

function useCarouselContext() {
	const ctx = useContext(CarouselContext);
	if (!ctx) throw new Error('Carousel sub-components must be used within Carousel.Root');
	return ctx;
}

function domOrder(a: HTMLElement, b: HTMLElement) {
	return a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: CarouselRootProps & { ref?: (el: HTMLDivElement) => void }) {
	const [local, rest] = splitProps(props, [
		'orientation',
		'loop',
		'defaultIndex',
		'onIndexChange',
		'class',
		'children',
		'ref',
	]);

	const orientation = () => local.orientation ?? 'horizontal';
	const loop = () => local.loop ?? false;
	const vertical = () => orientation() === 'vertical';

	let viewportEl: HTMLDivElement | undefined;
	const slides: HTMLElement[] = [];

	const [count, setCount] = createSignal(0);
	const [current, setCurrent] = createSignal(local.defaultIndex ?? 0);

	const setCurrentIndex = (index: number) => {
		if (current() === index) return;
		setCurrent(index);
		local.onIndexChange?.(index);
	};

	const registerSlide = (el: HTMLElement) => {
		slides.push(el);
		slides.sort(domOrder);
		setCount(slides.length);
		return () => {
			const idx = slides.indexOf(el);
			if (idx !== -1) slides.splice(idx, 1);
			setCount(slides.length);
		};
	};

	const offsetOf = (el: HTMLElement) => {
		const vp = viewportEl;
		if (!vp) return 0;
		const vpRect = vp.getBoundingClientRect();
		const rect = el.getBoundingClientRect();
		return vertical() ? rect.top - vpRect.top + vp.scrollTop : rect.left - vpRect.left + vp.scrollLeft;
	};

	const updateCurrent = () => {
		const vp = viewportEl;
		if (!vp || slides.length === 0) return;
		const scroll = vertical() ? vp.scrollTop : vp.scrollLeft;
		let best = 0;
		let bestDist = Infinity;
		slides.forEach((el, i) => {
			const dist = Math.abs(offsetOf(el) - scroll);
			if (dist < bestDist) {
				bestDist = dist;
				best = i;
			}
		});
		setCurrentIndex(best);
	};

	const scrollTo = (index: number, behavior: ScrollBehavior = 'smooth') => {
		const clamped = Math.min(Math.max(index, 0), Math.max(slides.length - 1, 0));
		setCurrentIndex(clamped);
		const vp = viewportEl;
		const el = slides[clamped];
		if (!vp || !el) return;
		const target = offsetOf(el);
		if (typeof vp.scrollTo === 'function') {
			vp.scrollTo(vertical() ? { top: target, behavior } : { left: target, behavior });
		} else if (vertical()) {
			vp.scrollTop = target;
		} else {
			vp.scrollLeft = target;
		}
	};

	const scrollNext = () => {
		const next = current() + 1;
		if (next < count()) scrollTo(next);
		else if (loop()) scrollTo(0);
	};

	const scrollPrev = () => {
		const prev = current() - 1;
		if (prev >= 0) scrollTo(prev);
		else if (loop()) scrollTo(count() - 1);
	};

	const ctx: CarouselContextValue = {
		get orientation() {
			return orientation();
		},
		get loop() {
			return loop();
		},
		get count() {
			return count();
		},
		get current() {
			return current();
		},
		get canScrollPrev() {
			return loop() ? count() > 1 : current() > 0;
		},
		get canScrollNext() {
			return loop() ? count() > 1 : current() < count() - 1;
		},
		viewportRef: (el) => (viewportEl = el),
		registerSlide,
		updateCurrent,
		scrollTo,
		scrollNext,
		scrollPrev,
	};

	return (
		<CarouselContext.Provider value={ctx}>
			<div
				ref={local.ref}
				role='region'
				aria-roledescription='carousel'
				class={local.class}
				data-orientation={orientation()}
				{...rest}>
				{local.children}
			</div>
		</CarouselContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Viewport
// ---------------------------------------------------------------------------

function Viewport(props: CarouselViewportProps & { ref?: (el: HTMLDivElement) => void }) {
	const [local, rest] = splitProps(props, [
		'class',
		'children',
		'style',
		'tabindex',
		'onScroll',
		'onKeyDown',
		'ref',
	]);
	const ctx = useCarouselContext();
	const mergedRef = createMergedRefs<HTMLDivElement>(ctx.viewportRef, (el) => local.ref?.(el));
	const vertical = () => ctx.orientation === 'vertical';

	const viewportStyle = (): JSX.CSSProperties => {
		const ours: JSX.CSSProperties = {
			'overflow-x': vertical() ? 'hidden' : 'auto',
			'overflow-y': vertical() ? 'auto' : 'hidden',
			'scroll-snap-type': `${vertical() ? 'y' : 'x'} mandatory`,
			'scrollbar-width': 'none',
		};
		const user = local.style;
		if (typeof user === 'string' || !user) return ours;
		return { ...ours, ...(user as JSX.CSSProperties) };
	};

	const handleScroll: JSX.EventHandler<HTMLDivElement, Event> = (e) => {
		ctx.updateCurrent();
		const userOnScroll = local.onScroll;
		if (typeof userOnScroll === 'function') {
			(userOnScroll as (event: typeof e) => void)(e);
		}
	};

	const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (e) => {
		const userOnKeyDown = local.onKeyDown;
		if (typeof userOnKeyDown === 'function') {
			(userOnKeyDown as (event: typeof e) => void)(e);
		}
		if (e.defaultPrevented) return;
		const nextKey = vertical() ? 'ArrowDown' : 'ArrowRight';
		const prevKey = vertical() ? 'ArrowUp' : 'ArrowLeft';
		if (e.key === nextKey) {
			e.preventDefault();
			ctx.scrollNext();
		} else if (e.key === prevKey) {
			e.preventDefault();
			ctx.scrollPrev();
		}
	};

	return (
		<div
			ref={mergedRef}
			data-carousel-viewport=''
			// The viewport is a scrollable region; make it keyboard-focusable so
			// arrow-key navigation works and axe `scrollable-region-focusable` passes.
			tabindex={local.tabindex ?? 0}
			class={local.class}
			style={viewportStyle()}
			{...rest}
			onScroll={handleScroll}
			onKeyDown={handleKeyDown}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Content (track)
// ---------------------------------------------------------------------------

function Content(props: CarouselContentProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'style']);
	const ctx = useCarouselContext();

	const contentStyle = (): JSX.CSSProperties => {
		const ours: JSX.CSSProperties = {
			display: 'flex',
			'flex-direction': ctx.orientation === 'vertical' ? 'column' : 'row',
		};
		const user = local.style;
		if (typeof user === 'string' || !user) return ours;
		return { ...ours, ...(user as JSX.CSSProperties) };
	};

	return (
		<div
			data-carousel-content=''
			class={local.class}
			style={contentStyle()}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Slide
// ---------------------------------------------------------------------------

function Slide(props: CarouselSlideProps & { ref?: (el: HTMLDivElement) => void }) {
	const [local, rest] = splitProps(props, ['class', 'children', 'style', 'ref']);
	const ctx = useCarouselContext();

	let cleanup: (() => void) | undefined;
	const mergedRef = createMergedRefs<HTMLDivElement>(
		(el) => {
			if (el) cleanup = ctx.registerSlide(el);
		},
		(el) => local.ref?.(el),
	);

	onCleanup(() => cleanup?.());

	const slideStyle = (): JSX.CSSProperties => {
		const ours: JSX.CSSProperties = {
			'scroll-snap-align': 'start',
			'flex-shrink': 0,
		};
		const user = local.style;
		if (typeof user === 'string' || !user) return ours;
		return { ...ours, ...(user as JSX.CSSProperties) };
	};

	return (
		<div
			ref={mergedRef}
			role='group'
			aria-roledescription='slide'
			data-carousel-slide=''
			class={local.class}
			style={slideStyle()}
			{...rest}>
			{local.children}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Previous / Next
// ---------------------------------------------------------------------------

function Previous(props: CarouselPreviousProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'onClick', 'disabled']);
	const ctx = useCarouselContext();

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.scrollPrev();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			aria-label='Previous slide'
			disabled={local.disabled ?? !ctx.canScrollPrev}
			class={local.class}
			{...rest}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

function Next(props: CarouselNextProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'onClick', 'disabled']);
	const ctx = useCarouselContext();

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.scrollNext();
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			aria-label='Next slide'
			disabled={local.disabled ?? !ctx.canScrollNext}
			class={local.class}
			{...rest}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Indicators
// ---------------------------------------------------------------------------

function Indicators(props: CarouselIndicatorsProps) {
	const ctx = useCarouselContext();
	const indices = () => Array.from({ length: ctx.count }, (_, index) => index);

	return (
		<For each={indices()}>
			{(index) => {
				// Re-run the render-prop whenever the selected slide changes so
				// consumers that destructure `selected` still see updates (a plain
				// getter would lose reactivity once destructured). Passing a thunk
				// child makes Solid track `ctx.current` and re-evaluate on change.
				const scrollTo = () => ctx.scrollTo(index);
				return <>{() => props.children({ index, selected: index === ctx.current, scrollTo })}</>;
			}}
		</For>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Carousel = {
	Root,
	Viewport,
	Content,
	Slide,
	Previous,
	Next,
	Indicators,
};

// Named exports expose the sub-components to Storybook's docgen (public API stays `Carousel.*`).
export { Root, Viewport, Content, Slide, Previous, Next, Indicators };
