// src/components/badge/Badge.tsx
import React from 'react'
import type { BadgeProps } from './Badge.types'

const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
	({ count = 0, className, ...rest }, ref) => {
		const displayCount = count > 0 ? (count > 9 ? '9+' : count) : 0

		return (
			<span ref={ref} className={className} data-count={count} {...rest}>
				{displayCount}
			</span>
		)
	},
)

Badge.displayName = 'Badge'

export { Badge }

// packages/solid/src/components/badge/Badge.tsx
import { splitProps } from 'solid-js';
import type { BadgeProps } from './Badge.types';

function Badge(props: BadgeProps) {
	const [local, rest] = splitProps(props, ['count', 'class']);
	const count = () => local.count ?? 0;

	const displayCount = () => {
		const c = count();
		if (c > 0) return c > 9 ? '9+' : c;
		return 0;
	};

	return (
		<span
			class={local.class}
			data-count={count()}
			{...rest}>
			{displayCount()}
		</span>
	);
}

export { Badge };
