// packages/react/src/components/radio/Radio.tsx
import React, { createContext, useCallback, useContext, useMemo } from 'react';
import { useControllableState } from '@/hooks/use-controllable-state';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { Helper } from '@/utils/helper';
import type {
	RadioContextValue,
	RadioIndicatorProps,
	RadioItemContextValue,
	RadioItemProps,
	RadioLabelProps,
	RadioRootProps,
} from './Radio.types';

const RadioContext = createContext<RadioContextValue | null>(null);
const RadioItemContext = createContext<RadioItemContextValue | null>(null);

function useRadioContext() {
	const context = useContext(RadioContext);
	if (!context) {
		throw new globalThis.Error('Radio compound components must be used within Radio.Root');
	}
	return context;
}

function useRadioItemContext() {
	const context = useContext(RadioItemContext);
	if (!context) {
		throw new globalThis.Error('Radio.Indicator/Label must be used within Radio.Item');
	}
	return context;
}

const Root = React.forwardRef<HTMLDivElement, RadioRootProps>(
	(
		{
			value: controlledValue,
			defaultValue,
			onChange,
			name,
			children,
			className,
			...rest
		},
		ref,
	) => {
		const [selectedValue, setSelectedValue] = useControllableState<string | number>({
			value: controlledValue,
			defaultValue,
			onChange,
		});

		const groupName = useMemo(() => name || Helper.generateUUID(), [name]);

		const isSelected = useCallback(
			(itemValue: string | number) => {
				if (selectedValue === undefined || selectedValue === null) return false;
				return String(selectedValue) === String(itemValue);
			},
			[selectedValue],
		);

		const select = useCallback(
			(itemValue: string | number) => {
				setSelectedValue(itemValue);
			},
			[setSelectedValue],
		);

		return (
			<RadioContext.Provider value={{ selectedValue, name: groupName, select, isSelected }}>
				<div
					ref={ref}
					role='radiogroup'
					className={className}
					{...rest}>
					{children}
				</div>
			</RadioContext.Provider>
		);
	},
);

Root.displayName = 'Radio.Root';

const Item = React.forwardRef<HTMLInputElement, RadioItemProps>(
	({ value, disabled = false, children, className, onClick, ...rest }, ref) => {
		const ctx = useRadioContext();
		const checked = ctx.isSelected(value);
		const { handlers, dataAttributes } = useInteractiveState({ disabled });

		return (
			<RadioItemContext.Provider value={{ value, disabled, checked }}>
				<div
					className={className}
					data-checked={checked ? '' : undefined}
					{...dataAttributes}
					onMouseEnter={handlers.onMouseEnter}
					onMouseLeave={handlers.onMouseLeave}
					onPointerDown={handlers.onPointerDown}
					onPointerUp={handlers.onPointerUp}
					onClick={(e) => {
						if (!disabled) ctx.select(value);
						onClick?.(e);
					}}
					{...rest}>
					<input
						ref={ref}
						type='radio'
						name={ctx.name}
						value={String(value)}
						checked={checked}
						disabled={disabled}
						onChange={() => ctx.select(value)}
						onFocus={handlers.onFocus}
						onBlur={handlers.onBlur}
						onKeyDown={handlers.onKeyDown}
						onKeyUp={handlers.onKeyUp}
						style={{
							position: 'absolute',
							opacity: 0,
							pointerEvents: 'none',
							width: 0,
							height: 0,
						}}
					/>
					{children}
				</div>
			</RadioItemContext.Provider>
		);
	},
);

Item.displayName = 'Radio.Item';

const Indicator = React.forwardRef<HTMLSpanElement, RadioIndicatorProps>(({ children, className, ...rest }, ref) => {
	const { checked } = useRadioItemContext();

	if (!checked) return null;

	return (
		<span
			ref={ref}
			className={className}
			data-checked=''
			{...rest}>
			{children}
		</span>
	);
});

Indicator.displayName = 'Radio.Indicator';

const Label = React.forwardRef<HTMLLabelElement, RadioLabelProps>(({ children, className, ...rest }, ref) => {
	const { disabled } = useRadioItemContext();

	return (
		<label
			ref={ref}
			className={className}
			data-disabled={disabled ? '' : undefined}
			{...rest}>
			{children}
		</label>
	);
});

Label.displayName = 'Radio.Label';

export const Radio = {
	Root,
	Item,
	Indicator,
	Label,
};

// packages/solid/src/components/radio/Radio.tsx
import { createContext, createMemo, createSignal, Show, splitProps, useContext, type JSX } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { Helper } from '@/utils/helper';
import type {
	RadioContextValue,
	RadioIndicatorProps,
	RadioItemContextValue,
	RadioItemProps,
	RadioLabelProps,
	RadioRootProps,
} from './Radio.types';

const RadioContext = createContext<RadioContextValue | null>(null);
const RadioItemContext = createContext<RadioItemContextValue | null>(null);

function useRadioContext() {
	const context = useContext(RadioContext);
	if (!context) {
		throw new Error('Radio compound components must be used within Radio.Root');
	}
	return context;
}

function useRadioItemContext() {
	const context = useContext(RadioItemContext);
	if (!context) {
		throw new Error('Radio.Indicator/Label must be used within Radio.Item');
	}
	return context;
}

function Root(props: RadioRootProps) {
	const [local, rest] = splitProps(props, ['value', 'defaultValue', 'onChange', 'name', 'children', 'class']);

	const [uncontrolledValue, setUncontrolledValue] = createSignal<string | number | undefined>(local.defaultValue);
	const isControlled = () => local.value !== undefined;
	const selectedValue = () => (isControlled() ? local.value : uncontrolledValue());

	const groupName = createMemo(() => local.name || Helper.generateUUID());

	const isSelected = (itemValue: string | number) => {
		const sv = selectedValue();
		if (sv === undefined || sv === null) return false;
		return String(sv) === String(itemValue);
	};

	const select = (itemValue: string | number) => {
		if (!isControlled()) setUncontrolledValue(itemValue);
		local.onChange?.(itemValue);
	};

	const ctxValue: RadioContextValue = {
		get selectedValue() {
			return selectedValue();
		},
		get name() {
			return groupName();
		},
		select,
		isSelected,
	};

	return (
		<RadioContext.Provider value={ctxValue}>
			<div
				role='radiogroup'
				class={local.class}
				{...(rest as object)}>
				{local.children}
			</div>
		</RadioContext.Provider>
	);
}

function Item(props: RadioItemProps) {
	const [local, rest] = splitProps(props, ['value', 'disabled', 'children', 'class', 'onClick']);
	const ctx = useRadioContext();

	const checked = () => ctx.isSelected(local.value);
	const disabled = () => !!local.disabled;

	const state = createInteractiveState({
		get disabled() {
			return disabled();
		},
	});

	const itemCtxValue: RadioItemContextValue = {
		get value() {
			return local.value;
		},
		get disabled() {
			return disabled();
		},
		get checked() {
			return checked();
		},
	};

	const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
		if (!disabled()) ctx.select(local.value);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<RadioItemContext.Provider value={itemCtxValue}>
			<div
				class={local.class}
				data-checked={checked() ? '' : undefined}
				{...state.dataAttributes}
				onMouseEnter={state.handlers.onMouseEnter}
				onMouseLeave={state.handlers.onMouseLeave}
				onPointerDown={state.handlers.onPointerDown}
				onPointerUp={state.handlers.onPointerUp}
				onClick={handleClick}
				{...(rest as object)}>
				<input
					type='radio'
					name={ctx.name}
					value={String(local.value)}
					checked={checked()}
					disabled={disabled()}
					onChange={() => ctx.select(local.value)}
					onFocus={state.handlers.onFocus}
					onBlur={state.handlers.onBlur}
					onKeyDown={state.handlers.onKeyDown}
					onKeyUp={state.handlers.onKeyUp}
					style={{
						position: 'absolute',
						opacity: 0,
						'pointer-events': 'none',
						width: 0,
						height: 0,
					}}
				/>
				{local.children}
			</div>
		</RadioItemContext.Provider>
	);
}

function Indicator(props: RadioIndicatorProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useRadioItemContext();

	return (
		<Show when={ctx.checked}>
			<span
				class={local.class}
				data-checked=''
				{...(rest as object)}>
				{local.children}
			</span>
		</Show>
	);
}

function Label(props: RadioLabelProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = useRadioItemContext();

	return (
		<label
			class={local.class}
			data-disabled={ctx.disabled ? '' : undefined}
			{...(rest as object)}>
			{local.children}
		</label>
	);
}

export const Radio = {
	Root,
	Item,
	Indicator,
	Label,
};
