// packages/react/bench/render.ssr.bench.tsx
/**
 * SSR render benchmark — measures `renderToStaticMarkup` throughput for each
 * scenario across Wire UI, Radix UI, and Headless UI. Deterministic and
 * CI-friendly: no layout, no portals, pure server render.
 *
 * Run: `npm run bench` (all) or `npm run bench -- render.ssr`.
 */
import { bench, describe } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import { inlineScenarios } from './scenarios';

for (const [name, variants] of Object.entries(inlineScenarios)) {
	describe(`SSR · ${name}`, () => {
		for (const { lib, Component } of variants) {
			bench(lib, () => {
				renderToStaticMarkup(createElement(Component));
			});
		}
	});
}

// packages/solid/bench/render.ssr.bench.tsx
/**
 * SSR render benchmark — measures `renderToString` throughput for each scenario
 * across Wire UI, Kobalte, and Corvu. Deterministic and CI-friendly: no layout,
 * no portals, pure server render.
 *
 * Run: `npm run bench:ssr` (or `npm run bench` for mount + SSR).
 */
import { bench, describe } from 'vitest';
import { renderToString } from 'solid-js/web';
import { inlineScenarios } from './scenarios';
import { ssrRenderable, logSkips } from './harness';

for (const [name, variants] of Object.entries(inlineScenarios)) {
	const runnable = ssrRenderable(name, variants);
	describe(`SSR · ${name}`, () => {
		for (const { lib, Component } of runnable) {
			bench(lib, () => {
				renderToString(() => <Component />);
			});
		}
	});
}

logSkips('ssr');
