// src/components/password/Password.tsx
import React, { createContext, useCallback, useContext, useMemo, useRef, useState } from 'react';
import { Helper } from '@/utils/helper';
import { useInteractiveState } from '@/hooks/use-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import type {
	PasswordContextValue,
	PasswordErrorProps,
	PasswordFieldProps,
	PasswordLabelProps,
	PasswordRootProps,
	PasswordToggleProps,
} from './Password.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PasswordContext = createContext<PasswordContextValue | null>(null);

function usePasswordContext() {
	const ctx = useContext(PasswordContext);
	if (!ctx) throw new globalThis.Error('Password sub-components must be used within Password.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

const Root = React.forwardRef<HTMLDivElement, PasswordRootProps>(
	(
		{
			value: controlledValue,
			defaultValue = '',
			onChange,
			onFocus,
			onBlur,
			isRequired = false,
			errorMessage = {},
			invalidType = '',
			id,
			className,
			children,
			...rest
		},
		ref,
	) => {
		const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
		const isControlled = controlledValue !== undefined;
		const value = isControlled ? controlledValue : uncontrolledValue;

		const [visible, setVisible] = useState(false);
		const fieldRef = useRef<HTMLInputElement>(null);
		const inputId = useMemo(() => id ?? Helper.generateUUID(), [id]);

		const handleChange = useCallback(
			(val: string) => {
				if (!isControlled) setUncontrolledValue(val);
				onChange?.(val);
			},
			[isControlled, onChange],
		);

		const handleFocus = useCallback(() => onFocus?.(), [onFocus]);

		const handleBlur = useCallback(() => onBlur?.(), [onBlur]);

		return (
			<PasswordContext.Provider
				value={{
					inputId,
					value,
					visible,
					isRequired,
					invalidType,
					errorMessage,
					setVisible,
					handleChange,
					handleFocus,
					handleBlur,
					setFieldNode: (node) => {
						(fieldRef as React.MutableRefObject<HTMLInputElement | null>).current = node;
					},
				}}>
				<div
					ref={ref}
					className={className}
					{...rest}>
					{children}
				</div>
			</PasswordContext.Provider>
		);
	},
);

Root.displayName = 'Password.Root';

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

const Field = React.forwardRef<HTMLInputElement, PasswordFieldProps>(({ className, ...rest }, externalRef) => {
	const ctx = usePasswordContext();

	return (
		<input
			ref={(el) => {
				ctx.setFieldNode(el);
				if (typeof externalRef === 'function') externalRef(el);
				else if (externalRef) externalRef.current = el;
			}}
			id={ctx.inputId}
			value={ctx.value}
			type={ctx.visible ? 'text' : 'password'}
			required={ctx.isRequired}
			className={className}
			aria-required={ctx.isRequired || undefined}
			aria-invalid={ctx.invalidType ? true : undefined}
			data-invalid={ctx.invalidType ? '' : undefined}
			data-visible={ctx.visible ? '' : undefined}
			onFocus={ctx.handleFocus}
			onBlur={ctx.handleBlur}
			onChange={(e) => ctx.handleChange(e.target.value)}
			{...rest}
		/>
	);
});

Field.displayName = 'Password.Field';

// ---------------------------------------------------------------------------
// Toggle
// ---------------------------------------------------------------------------

const Toggle = React.forwardRef<HTMLButtonElement, PasswordToggleProps>(
	({ className, children, onClick, ...rest }, ref) => {
		const ctx = usePasswordContext();
		const { handlers, dataAttributes } = useInteractiveState();
		const merged = mergeProps(rest as Record<string, unknown>, handlers as Record<string, unknown>);

		return (
			<button
				ref={ref}
				type='button'
				aria-label={ctx.visible ? 'Hide password' : 'Show password'}
				className={className}
				data-visible={ctx.visible ? '' : undefined}
				{...dataAttributes}
				{...merged}
				onClick={(e) => {
					ctx.setVisible(!ctx.visible);
					onClick?.(e);
				}}>
				{children}
			</button>
		);
	},
);

Toggle.displayName = 'Password.Toggle';

// ---------------------------------------------------------------------------
// Label
// ---------------------------------------------------------------------------

const Label = React.forwardRef<HTMLLabelElement, PasswordLabelProps>(({ children, className, ...rest }, ref) => {
	const { inputId, isRequired } = usePasswordContext();

	return (
		<label
			ref={ref}
			htmlFor={inputId}
			className={className}
			{...rest}>
			{isRequired && <span aria-hidden='true'>*</span>}
			{children}
		</label>
	);
});

Label.displayName = 'Password.Label';

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

const Error = React.forwardRef<HTMLElement, PasswordErrorProps>(({ children, className, ...rest }, ref) => {
	const { invalidType, errorMessage } = usePasswordContext();

	if (!invalidType) return null;

	return (
		<small
			ref={ref}
			role='alert'
			className={className}
			{...rest}>
			{children ?? errorMessage[invalidType]}
		</small>
	);
});

Error.displayName = 'Password.Error';

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Password = { Root, Field, Toggle, Label, Error };

// packages/solid/src/components/password/Password.tsx
import { createContext, createMemo, createSignal, Show, splitProps, useContext, type JSX } from 'solid-js';
import { createInteractiveState } from '@/primitives/create-interactive-state';
import { mergeProps } from '@/utils/merge-props';
import { Helper } from '@/utils/helper';
import type {
	PasswordContextValue,
	PasswordErrorProps,
	PasswordFieldProps,
	PasswordLabelProps,
	PasswordRootProps,
	PasswordToggleProps,
} from './Password.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const PasswordContext = createContext<PasswordContextValue | null>(null);

function usePasswordContext() {
	const ctx = useContext(PasswordContext);
	if (!ctx) throw new Error('Password sub-components must be used within Password.Root');
	return ctx;
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

function Root(props: PasswordRootProps) {
	const [local, rest] = splitProps(props, [
		'value',
		'defaultValue',
		'onChange',
		'onFocus',
		'onBlur',
		'isRequired',
		'errorMessage',
		'invalidType',
		'id',
		'class',
		'children',
	]);

	const [uncontrolledValue, setUncontrolledValue] = createSignal(local.defaultValue ?? '');
	const isControlled = () => local.value !== undefined;
	const value = () => (isControlled() ? (local.value ?? '') : uncontrolledValue());

	const [visible, setVisible] = createSignal(false);
	const inputId = createMemo(() => local.id ?? Helper.generateUUID());

	const handleChange = (val: string) => {
		if (!isControlled()) setUncontrolledValue(val);
		local.onChange?.(val);
	};

	const handleFocus = () => local.onFocus?.();
	const handleBlur = () => local.onBlur?.();

	const ctxValue: PasswordContextValue = {
		get inputId() {
			return inputId();
		},
		get value() {
			return value();
		},
		get visible() {
			return visible();
		},
		get isRequired() {
			return !!local.isRequired;
		},
		get invalidType() {
			return local.invalidType ?? '';
		},
		get errorMessage() {
			return local.errorMessage ?? {};
		},
		setVisible,
		handleChange,
		handleFocus,
		handleBlur,
	};

	return (
		<PasswordContext.Provider value={ctxValue}>
			<div
				class={local.class}
				{...rest}>
				{local.children}
			</div>
		</PasswordContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Field
// ---------------------------------------------------------------------------

function Field(props: PasswordFieldProps) {
	const [local, rest] = splitProps(props, ['class']);
	const ctx = usePasswordContext();

	return (
		<input
			id={ctx.inputId}
			value={ctx.value}
			type={ctx.visible ? 'text' : 'password'}
			required={ctx.isRequired}
			class={local.class}
			aria-required={ctx.isRequired || undefined}
			aria-invalid={ctx.invalidType ? true : undefined}
			data-invalid={ctx.invalidType ? '' : undefined}
			data-visible={ctx.visible ? '' : undefined}
			onFocus={() => ctx.handleFocus()}
			onBlur={() => ctx.handleBlur()}
			onInput={(e) => ctx.handleChange(e.currentTarget.value)}
			{...rest}
		/>
	);
}

// ---------------------------------------------------------------------------
// Toggle
// ---------------------------------------------------------------------------

function Toggle(props: PasswordToggleProps) {
	const [local, rest] = splitProps(props, ['class', 'children', 'onClick']);
	const ctx = usePasswordContext();
	const state = createInteractiveState();
	const merged = mergeProps(rest, state.handlers);

	const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
		ctx.setVisible(!ctx.visible);
		const userOnClick = local.onClick;
		if (typeof userOnClick === 'function') {
			(userOnClick as (event: typeof e) => void)(e);
		}
	};

	return (
		<button
			type='button'
			aria-label={ctx.visible ? 'Hide password' : 'Show password'}
			class={local.class}
			data-visible={ctx.visible ? '' : undefined}
			{...state.dataAttributes}
			{...merged}
			onClick={handleClick}>
			{local.children}
		</button>
	);
}

// ---------------------------------------------------------------------------
// Label
// ---------------------------------------------------------------------------

function Label(props: PasswordLabelProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = usePasswordContext();

	return (
		<label
			for={ctx.inputId}
			class={local.class}
			{...rest}>
			<Show when={ctx.isRequired}>
				<span aria-hidden='true'>*</span>
			</Show>
			{local.children}
		</label>
	);
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

function ErrorMessage(props: PasswordErrorProps) {
	const [local, rest] = splitProps(props, ['children', 'class']);
	const ctx = usePasswordContext();

	return (
		<Show when={ctx.invalidType}>
			<small
				role='alert'
				class={local.class}
				{...rest}>
				{local.children ?? ctx.errorMessage[ctx.invalidType]}
			</small>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const Password = { Root, Field, Toggle, Label, Error: ErrorMessage };
