// packages/react/src/components/avatar/Avatar.tsx
import React, { createContext, useContext, useEffect, useState } from 'react';
import type { AvatarFallbackProps, AvatarImageProps, AvatarImageStatus, AvatarRootProps } from './Avatar.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

interface AvatarContextValue {
	imageStatus: AvatarImageStatus;
	setImageStatus: (status: AvatarImageStatus) => void;
}

const AvatarContext = createContext<AvatarContextValue | null>(null);

function useAvatarContext(): AvatarContextValue {
	const ctx = useContext(AvatarContext);
	if (!ctx) {
		throw new globalThis.Error('[wire-ui] Avatar sub-components must be used inside <Avatar.Root>');
	}
	return ctx;
}

// ---------------------------------------------------------------------------
// Avatar.Root
// ---------------------------------------------------------------------------

/**
 * The container for the Avatar. Exposes `data-status` reflecting the current
 * image load state: `"loading"`, `"loaded"`, or `"error"`.
 *
 * @example
 * <Avatar.Root className="...">
 *   <Avatar.Image src="..." alt="Jane Doe" />
 *   <Avatar.Fallback>JD</Avatar.Fallback>
 * </Avatar.Root>
 */
const AvatarRoot = React.forwardRef<HTMLDivElement, AvatarRootProps>(({ children, ...rest }, ref) => {
	const [imageStatus, setImageStatus] = useState<AvatarImageStatus>('loading');

	return (
		<AvatarContext.Provider value={{ imageStatus, setImageStatus }}>
			<div
				ref={ref}
				data-status={imageStatus}
				{...rest}>
				{children}
			</div>
		</AvatarContext.Provider>
	);
});

AvatarRoot.displayName = 'Avatar.Root';

// ---------------------------------------------------------------------------
// Avatar.Image
// ---------------------------------------------------------------------------

/**
 * The avatar image. Automatically reports its load state back to `Avatar.Root`
 * via context — the Root's `data-status` updates to `"loaded"` or `"error"`.
 *
 * Hidden (not rendered) when `src` is empty/undefined so the Fallback shows
 * immediately without a broken-image icon.
 */
const AvatarImage = React.forwardRef<HTMLImageElement, AvatarImageProps>(
	({ src, onLoad, onError, style, ...rest }, ref) => {
		const { imageStatus, setImageStatus } = useAvatarContext();

		useEffect(() => {
			if (!src) {
				setImageStatus('error');
			} else {
				setImageStatus('loading');
			}
		}, [src, setImageStatus]);

		if (!src) return null;

		return (
			<img
				ref={ref}
				src={src}
				data-status={imageStatus}
				style={{ display: imageStatus === 'loaded' ? undefined : 'none', ...style }}
				onLoad={(e) => {
					setImageStatus('loaded');
					onLoad?.(e);
				}}
				onError={(e) => {
					setImageStatus('error');
					onError?.(e);
				}}
				{...rest}
			/>
		);
	},
);

AvatarImage.displayName = 'Avatar.Image';

// ---------------------------------------------------------------------------
// Avatar.Fallback
// ---------------------------------------------------------------------------

/**
 * Rendered when the image is still loading or has failed.
 * Supply `delayMs` to avoid a flash of the fallback during fast loads.
 *
 * @example
 * // Initials fallback
 * <Avatar.Fallback>JD</Avatar.Fallback>
 *
 * // Overflow count fallback
 * <Avatar.Fallback>+5</Avatar.Fallback>
 *
 * // Delayed — only shows if image takes > 300ms
 * <Avatar.Fallback delayMs={300}>JD</Avatar.Fallback>
 */
const AvatarFallback = React.forwardRef<HTMLSpanElement, AvatarFallbackProps>(
	({ delayMs = 0, children, ...rest }, ref) => {
		const { imageStatus } = useAvatarContext();
		const [canRender, setCanRender] = useState(delayMs === 0);

		useEffect(() => {
			if (delayMs > 0) {
				const timer = setTimeout(() => setCanRender(true), delayMs);
				return () => clearTimeout(timer);
			}
		}, [delayMs]);

		if (imageStatus === 'loaded') return null;
		if (!canRender) return null;

		return (
			<span
				ref={ref}
				{...rest}>
				{children}
			</span>
		);
	},
);

AvatarFallback.displayName = 'Avatar.Fallback';

// ---------------------------------------------------------------------------
// Compound export
// ---------------------------------------------------------------------------

export const Avatar = Object.assign(AvatarRoot, {
	Root: AvatarRoot,
	Image: AvatarImage,
	Fallback: AvatarFallback,
});

// packages/solid/src/components/avatar/Avatar.tsx
import { createContext, createEffect, createSignal, onCleanup, Show, splitProps, useContext, type JSX } from 'solid-js';
import type { AvatarFallbackProps, AvatarImageProps, AvatarImageStatus, AvatarRootProps } from './Avatar.types';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

interface AvatarContextValue {
	readonly imageStatus: AvatarImageStatus;
	setImageStatus: (status: AvatarImageStatus) => void;
}

const AvatarContext = createContext<AvatarContextValue | null>(null);

function useAvatarContext(): AvatarContextValue {
	const ctx = useContext(AvatarContext);
	if (!ctx) {
		throw new Error('[wire-ui] Avatar sub-components must be used inside <Avatar.Root>');
	}
	return ctx;
}

// ---------------------------------------------------------------------------
// Avatar.Root
// ---------------------------------------------------------------------------

/**
 * The container for the Avatar. Exposes `data-status` reflecting the current
 * image load state: `"loading"`, `"loaded"`, or `"error"`.
 *
 * @example
 * <Avatar.Root class="...">
 *   <Avatar.Image src="..." alt="Jane Doe" />
 *   <Avatar.Fallback>JD</Avatar.Fallback>
 * </Avatar.Root>
 */
function Root(props: AvatarRootProps) {
	const [local, rest] = splitProps(props, ['children']);
	const [imageStatus, setImageStatus] = createSignal<AvatarImageStatus>('loading');

	const ctxValue: AvatarContextValue = {
		get imageStatus() {
			return imageStatus();
		},
		setImageStatus,
	};

	return (
		<AvatarContext.Provider value={ctxValue}>
			<div
				data-status={imageStatus()}
				{...rest}>
				{local.children}
			</div>
		</AvatarContext.Provider>
	);
}

// ---------------------------------------------------------------------------
// Avatar.Image
// ---------------------------------------------------------------------------

/**
 * The avatar image. Automatically reports its load state back to `Avatar.Root`
 * via context — the Root's `data-status` updates to `"loaded"` or `"error"`.
 *
 * Hidden (not rendered) when `src` is empty/undefined so the Fallback shows
 * immediately without a broken-image icon.
 */
function AvatarImage(props: AvatarImageProps) {
	const [local, rest] = splitProps(props, ['src', 'onLoad', 'onError', 'style']);
	const ctx = useAvatarContext();

	createEffect(() => {
		if (!local.src) {
			ctx.setImageStatus('error');
		} else {
			ctx.setImageStatus('loading');
		}
	});

	const mergedStyle = (): JSX.CSSProperties | string | undefined => {
		const ourStyle: JSX.CSSProperties = ctx.imageStatus === 'loaded' ? {} : { display: 'none' };
		const userStyle = local.style;
		if (typeof userStyle === 'string' || !userStyle) return ourStyle;
		return { ...ourStyle, ...(userStyle as JSX.CSSProperties) };
	};

	const handleLoad: JSX.EventHandler<HTMLImageElement, Event> = (e) => {
		ctx.setImageStatus('loaded');
		const userOnLoad = local.onLoad;
		if (typeof userOnLoad === 'function') (userOnLoad as (event: typeof e) => void)(e);
	};

	const handleError: JSX.EventHandler<HTMLImageElement, Event> = (e) => {
		ctx.setImageStatus('error');
		const userOnError = local.onError;
		if (typeof userOnError === 'function') (userOnError as (event: typeof e) => void)(e);
	};

	return (
		<Show when={local.src}>
			<img
				src={local.src}
				data-status={ctx.imageStatus}
				style={mergedStyle()}
				onLoad={handleLoad}
				onError={handleError}
				{...rest}
			/>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Avatar.Fallback
// ---------------------------------------------------------------------------

/**
 * Rendered when the image is still loading or has failed.
 * Supply `delayMs` to avoid a flash of the fallback during fast loads.
 *
 * @example
 * <Avatar.Fallback delayMs={300}>JD</Avatar.Fallback>
 */
function Fallback(props: AvatarFallbackProps) {
	const [local, rest] = splitProps(props, ['delayMs', 'children']);
	const ctx = useAvatarContext();
	const delayMs = () => local.delayMs ?? 0;
	const [canRender, setCanRender] = createSignal(delayMs() === 0);

	createEffect(() => {
		const ms = delayMs();
		if (ms > 0) {
			const timer = setTimeout(() => setCanRender(true), ms);
			onCleanup(() => clearTimeout(timer));
		}
	});

	return (
		<Show when={ctx.imageStatus !== 'loaded' && canRender()}>
			<span {...rest}>{local.children}</span>
		</Show>
	);
}

// ---------------------------------------------------------------------------
// Compound export — Avatar is callable as Root and exposes sub-components
// ---------------------------------------------------------------------------

export const Avatar = Object.assign(Root, {
	Root,
	Image: AvatarImage,
	Fallback,
});
