// packages/vue/src/components/image/Image.vue
<script setup lang="ts">
import { ref } from 'vue'

defineOptions({ name: 'WireImage' })

const props = defineProps<{
	src: string
	alt?: string
	position?: string
	onImageLoaded?: () => void
}>()

const loaded = ref(false)

function handleLoad() {
	loaded.value = true
	props.onImageLoaded?.()
}

function handleError() {
	loaded.value = true
	props.onImageLoaded?.()
}
</script>

<template>
	<div :data-position="position">
		<div v-if="!loaded" data-part="loader" />
		<img
			:src="src"
			:alt="alt"
			data-part="image"
			:data-loaded="loaded || undefined"
			:style="!loaded ? { display: 'none' } : undefined"
			@load="handleLoad"
			@error="handleError"
		/>
	</div>
</template>

// packages/react/src/components/image/Image.tsx
import React, { useState } from 'react';
import type { ImageProps } from './Image.types';

const Image = React.forwardRef<HTMLDivElement, ImageProps>(
	({ src, alt, position, onImageLoaded, className, ...rest }, ref) => {
		const [loaded, setLoaded] = useState(false);

		const handleLoad = () => {
			setLoaded(true);
			onImageLoaded?.();
		};

		const handleError = () => {
			setLoaded(true);
			onImageLoaded?.();
		};

		return (
			<div
				ref={ref}
				className={className}
				data-position={position}
				{...rest}>
				{!loaded && <div data-part='loader' />}
				<img
					src={src}
					alt={alt}
					data-part='image'
					data-loaded={loaded || undefined}
					style={!loaded ? { display: 'none' } : undefined}
					onLoad={handleLoad}
					onError={handleError}
				/>
			</div>
		);
	},
);

Image.displayName = 'Image';

export { Image };
